### ISSUE TITLE
xsk_socket__create() failed with ENOTSUP when run in gcloud with kernel 5.0

### ISSUE THREAD

**Issue by msherif1234** [libbpf/libbpf#112]
Hi All: 
I am using libbpf version 0.0.4 , and trying to create AFXDP single socket I was able to see the code working only when I had ubuntu 5.3 or higher but anything lower than that resulted in socket_creation failure with errno 95, I captured my testing results here :-

- v5.0.0-1022-gke | Failed | ENOTSUP
- v5.1.0 | Failed | ENOTSUP
- v5.2.0 | Failed | ENOTSUP
- v5.3.0 | Passed |  
- v5.4.2 | Passed

when I traced the code it failed during socket bind
695         sxdp.sxdp_family = PF_XDP;
696         sxdp.sxdp_ifindex = xsk->ifindex;
697         sxdp.sxdp_queue_id = xsk->queue_id;
698         if (umem->refcount > 1) {
699                 sxdp.sxdp_flags = XDP_SHARED_UMEM;
700                 sxdp.sxdp_shared_umem_fd = umem->fd;
701         } else {
702                 sxdp.sxdp_flags = xsk->config.bind_flags;
703         }
704 
**_705         err = bind(xsk->fd, (struct sockaddr *)&sxdp, sizeof(sxdp));_**
706         if (err) {
707                 err = -errno;
708                 goto out_mmap_tx;
709         }

are the older kernels missing some patches , is there anyway I can get the above to work with gcloud 5.0 ?
here is the output of uname -a for reference
_Linux snort-xmt46 5.0.0-1022-gke #22~18.04.3-Ubuntu SMP Thu Oct 10 19:41:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux_

Also is there any dependancies between a specific libbpf version and the kernel we are using ? is it documented anywhere ?

Thanks,
Mohamed

**Comment by anakryiko** [comment]
@msherif1234, the best place to ask such question would be bpf@vger.kernel.org, there should be people that will be able to help you with this.
