### ISSUE TITLE
Dash in filename prevents bpf object file from loading

### ISSUE THREAD

**Issue by vl409** [libbpf/libbpf#122]
If file is named with dash, for example, "b-lah.o", 
the following code:
```
rc = bpf_prog_load("bpf/b-lah.o", BPF_PROG_TYPE_SOCKET_FILTER, &pobj, &prog_fd);
```
fails with:
```
libbpf: failed to create map (name: 'b-lah.rodata'): Invalid argument(-22)
libbpf: failed to load object 'bpf/b-lah.o'
```

Just renaming the file to "blah.o" makes it load fine.

To reproduce the issue, the function call (probably with arguments) is required;
Example file:

```
$ cat bpf-prog.c 

#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

#include <linux/in.h>
#include <linux/types.h>
#include <linux/string.h>
#include <linux/if_ether.h>
#include <linux/if_packet.h>
#include <linux/ip.h>
#include <linux/tcp.h>
#include <linux/udp.h>


SEC("socket")
int tryme(struct __sk_buff *skb)
{
    const char buf[10] = "foo:%d!\n";
    bpf_trace_printk(buf, sizeof(buf), 3); // if this line is commented, works
    return 0;
}

char _license[] SEC("license") = "GPL";
```
libbpf-0.0.6 is used on gentoo with 5.5.2 kernel

**Comment by yonghong-song** [comment]
The kernel enforces that the map name cannot have '-'. The map created from read-only section (string "foo:%d!\n") will have name like objname.readonly. libbpf can remove offending characters '-' but it won't represent the object file name any more. Maybe you can just change your obj file name?

**Comment by vl409** [comment]
Thank you for the response!
Of course, I can change the filename. 
It is a bit unexpected that file name has any relation to the resulting code.
Imagine that some library, for example "libgnutls-openssl.so" cannot load due to dash in it.
I suggest that this should be either documented somewhere or the warning 
or error can be produced by libbpf saying that filename contains bad characters.

**Comment by anakryiko** [comment]
Fixed by https://github.com/libbpf/libbpf/commit/c772c9cbde2cb8d12674d67cc179ef3a5aa42159
