### ISSUE TITLE
undefined reference to symbol 'gzopen64@@ZLIB_1.2.3.3'

### ISSUE THREAD

**Issue by Bresenham** [libbpf/libbpf#128]
I am compiling this tutorial: https://github.com/xdp-project/xdp-tutorial/tree/master/advanced03-AF_XDP

but I replaced the `libbpf`-folder with the content of this repository. Everything compiles fine until this error:

```
/usr/bin/ld: ../libbpf/src/libbpf.a(libbpf.o): undefined reference to symbol 'gzopen64@@ZLIB_1.2.3.3'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
../common/common.mk:107: recipe for target 'af_xdp_user' failed
```

Any ideas?

The tutorial code compiles fine with `libbpf` as a submodule (as `xdp-tutorial` is supplying it)

**Comment by anakryiko** [comment]
I suspect it's because xdp-tutorial's common/common.mk is missing -lz in LIBS variable. I suggest opening PR or issue against https://github.com/xdp-project/xdp-tutorial directly.

**Comment by Bresenham** [comment]
Thank you so much, this solved the problem!

**Comment by anaveed81** [comment]
Just for completeness, the issue is with the library version. Even if your code compiles fine by adding -lz flag in the LD_FLAGS variable of common.mk file, it will not execute because the tutorial code has not been updated to use the latest Libbpf version.

**Comment by omarerc** [comment]
I have the same problem. I updated the libbpf version and then updated the depreciated functions. 

/usr/bin/ld: ../libbpf/src//libbpf.a(libbpf.o): undefined reference to symbol 'gzopen64@@ZLIB_1.2.3.3'
/usr/bin/ld: /usr/lib64/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [../common//common.mk:107: xdp_pass_user] Error 1

**Comment by anakryiko** [comment]
@omarerc please ask at https://github.com/xdp-project/xdp-tutorial your zlib is too old or something like that given gzopen64 API isn't available
