### ISSUE TITLE
Why does libbpf hide `struct xsk_umem` thus preventing XDP_SHARED_UMEM?

### ISSUE THREAD

**Issue by Bresenham** [libbpf/libbpf#136]
I want to try XDP_SHARED_UMEM: https://www.kernel.org/doc/html/latest/networking/af_xdp.html#xdp-shared-umem-bind-flag

So what the article says is, that in case one wants to use this feature he has to set `XDP_SHARED_UMEM` option and provide the original fd of the socket via a `struct sockaddr_xdp sxdp`.

I took a look at `xsk.c`. The function `xsk_socket__create` does this for the user of the library by checking `umem->refcount`. In order for this to work, two or more programs need the same `struct xsk_umem`.

In my "architecture" I have this main program which loads the AF-XDP kernel program, sets up a shared memory and then launches several other programs depending on how many packet streams have to be processed - each one with their own AF-XDP socket.

My original idea was to create a separate program (the one who manages the UMEM) which also opens the first AF-XDP socket and every other program then uses this socket and its umem as `SHARED_UMEM`. So I thought that this manage-program would copy the content of its `struct xsk_umem` into the shared memory and then all other sub-processes can load this shared-memory and pass it to their call of `xsk_socket__create`.

But I don't think that's possible because the definition of `struct xsk_umem` is hidden in `xsk.c`.

How do you expect a user of your library to implement the `XDP_SHARED_UMEM` feature?

**Comment by anakryiko** [comment]
Adding bpf@vger.kernel.org, it's a better place to ask questions about bpf
and libbpf.

**Comment by anakryiko** [comment]
@Bresenham, can you please post your questions to bpf@vger.kernel.org? Github is mostly a mirror of libbpf, source of truth of which is in kernel. bpf@vger.kernel.org has all the folks working on BPF and libbpf, so you'll get more attention and better answers there.

Github issues are kept open in this repo mostly to catch issues with packaging of libbpf and other Github version-specific problems.
