### ISSUE TITLE
Is it possible to do SHARED_UMEM between processes?

### ISSUE THREAD

**Issue by Bresenham** [libbpf/libbpf#138]
I am struggling with my project to get SHARED_UMEM running between two or more processes. I made some changes to the lib in order to be able to copy `struct xsk_umem` into shared memory and reuse the umem on the sub-process.

But now I get the error:

`symbol lookup error: /lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: _dl_allocate_tls, version GLIBC_PRIVATE`

In my opinion, a working example for SHARED_UMEM is strongly required. The only information I find about this topic is an e-mail from Nov, 2019 in the linux mailing list and two sentences from here : https://www.kernel.org/doc/html/latest/networking/af_xdp.html#xdp-shared-umem-bind-flag

Please!!

Edit: For example, do I still have to call

```
	ret = xsk_ring_prod__reserve(&umem->fq,
				     XSK_RING_PROD__DEFAULT_NUM_DESCS,
				     &idx);
```

Because if I do this I get: 

`Inconsistency detected by ld.so: dl-fini.c: 87: _dl_fini: Assertion `ns != LM_ID_BASE || i == nloaded' failed!`

**Comment by anakryiko** [comment]
Adding bpf@vger.kernel.org, it's a better place to ask questions about
bpf and libbpf.

**Comment by anakryiko** [comment]
@Bresenham, can you please post your questions to bpf@vger.kernel.org? Github is mostly a mirror of libbpf, source of truth of which is in kernel. bpf@vger.kernel.org has all the folks working on BPF and libbpf, so you'll get more attention and better answers there.

Github issues are kept open in this repo mostly to catch issues with packaging of libbpf and other Github version-specific problems.
