### ISSUE TITLE
/* 4096 bytes */ ?

### ISSUE THREAD

**Issue by glennWang** [libbpf/libbpf#142]
What the meaning of `/* 4096 bytes */`  in this line?

https://github.com/libbpf/libbpf/blob/b91f53ec5f1aba2a9d01dc00c4434063abd921e8/src/xsk.h#L191

**Comment by anakryiko** [comment]
I think it hints that `(1 << XSK_UMEM__DEFAULT_FRAME_SHIFT) == 4096`

**Comment by glennWang** [comment]
You are right.

I have made a low level mistake.
