### ISSUE TITLE
how to provide vmlinux btf information to bpf app on non-btf aware kernel

### ISSUE THREAD

**Issue by vibrys** [libbpf/libbpf#146]
Hallo libbpf developers

I've just compiled runqslower using linux-5.6
As I understand CORE feature it'd be possible to run it on kernel-5.0 as long as vmlinux btf information could be provided "externally". (IMO pahole could be used to convert dwarf vmlinux to btf?)

Is there a way for libbpf to "consume" such external source?

regards

**Comment by anakryiko** [comment]
Yes, you can provide your own path to ELF file with BTF in it by using bpf_object__load_xattr and setting .target_btf_path in bpf_object_load_attr struct. You are right that pahole can be used to get vmlinux ELF file with .BTF section built-in. If that doesn't fit your use case, would you mind writing an email into bpf@vger.kernel.org mailing list (which is the main mailing list for BPF and libbpf-related topics), describing your use case and problem. Thanks!

**Comment by vibrys** [comment]
I'll try to go this path
Thank YOu for the answer
