### ISSUE TITLE
xsk_prod_nb_free

### ISSUE THREAD

**Issue by glennWang** [libbpf/libbpf#148]
Who can explain the principle and implementation method of this function?

Or can someone recommend the article on AF_XDP source code?

I want to learn AF_XDP.   But it's hard for me to read the af_xdp source code directly.

https://github.com/libbpf/libbpf/blob/b91f53ec5f1aba2a9d01dc00c4434063abd921e8/src/xsk.h#L85

**Comment by anakryiko** [comment]
Please send email with your question to bpf@vger.kernel.org, that's a BPF-related kernel mailing list, where lots of people will be able to help you with this.
