### ISSUE TITLE
Can AF_XDP support multithread concurrent receive packet with a nic ring?

### ISSUE THREAD

**Issue by ChenYahui2019** [libbpf/libbpf#163]
Currently, libbpf do not support concurrently receive pkts using AF_XDP. 

For example: I create 4 af_xdp sockets on nic's ring 0. Four sockets receiving packets concurrently can't work correctly because the API of cq `xsk_ring_prod__reserve` and `xsk_ring_prod__submit` don't support concurrence.

So, my question is why libbpf was designed non-concurrent mode, is the limit of kernel or other reason? I want to change the code to support concurrent receive pkts, therefore I want to find out whether this is theoretically supported.

Thx.

**Comment by anakryiko** [comment]
This is more appropriate question for https://github.com/xdp-project/xdp-project and bpf@vger.kernel.org mailing list, where all the BPF kernel developers are. You'll get more attention and better responses there. Please send your question to bpf@vger.kernel.org, thanks.
