### ISSUE TITLE
Question about using BPF_MAP_TYPE_LPM_TRIE

### ISSUE THREAD

**Issue by yonhenli** [libbpf/libbpf#166]
I am trying to use BPF_MAP_TYPE_LPM_TRIE to implement subnet filtering. But I encounter some problems when I use the data structure.

I have my map defined in the bpf program as follow:
``` 71 // subnet & port filtering
 72 struct bpf_map_def SEC("maps") block_subnet_map = {
 73   .type        = BPF_MAP_TYPE_LPM_TRIE,
 74   .key_size    = 8,
 75   .value_size  = sizeof(uint64_t), 
 76   .max_entries = 5120,
 77   .map_flags   = BPF_F_NO_PREALLOC,
 78 };
```

I was also trying to create a key for lookup:
```
345   struct bpf_lpm_trie_key lookup = {
346     .prefixlen = 32,
347     .data = {192, 168, 0, 0}
348   };
```

When I try to compile the code, the compiler says:
```
xdp_prog_kern.c:347:12: error: excess elements in array initializer [-Werror]
                .data = {192, 168, 0, 0}
                         ^~~
```
Does anyone how to solve this problem? Or what is the correct way to use BPF_MAP_TYPE_LPM_TRIE because I cannot find too much information about how to use it? I appreciate your help!

**Comment by anakryiko** [comment]
I don't have first hand experience with this particular type of map, but I think that you are supposed to use your own struct for key, the important part is that first 4 bytes of your struct would define prefixlen, everything else will be treated as data, that will be compared. Try that.

But also, keep in mind, that this is a mirror of libbpf. We keep issues and PRs open for this repo, but they should be strictly about issues with this particular mirror. All things BPF-related should be asked in bpf@vger.kernel.org mailing list. Thanks!
