### ISSUE TITLE
possible dereference of NULL pointer

### ISSUE THREAD

**Issue by brycekahle** [libbpf/libbpf#196]
I'm not a full-time C programmer, so apologies in advance if this is incorrect.

I've been examining the CO-RE code in libbpf, and I believe I have a found a `NULL` pointer dereference.
In the `skip_mods_and_typedefs` function:
https://github.com/libbpf/libbpf/blob/66780a46cb9f7f593a0f19d86b2073d03c836f05/src/libbpf.c#L1828-L1843
it calls `btf__type_by_id` which may return NULL if the `type_id` argument is invalid.
https://github.com/libbpf/libbpf/blob/66780a46cb9f7f593a0f19d86b2073d03c836f05/src/btf.c#L214-L220
`skip_mods_and_typedefs` proceeds to call `is_mod`
https://github.com/libbpf/libbpf/blob/66780a46cb9f7f593a0f19d86b2073d03c836f05/src/btf.h#L206-L213
and deeper `btf_kind`
https://github.com/libbpf/libbpf/blob/66780a46cb9f7f593a0f19d86b2073d03c836f05/src/btf.h#L124-L127
which accesses `t->info`. 

Since `t` at this point will be `NULL`, wouldn't this be a `NULL` pointer dereference?

**Comment by anakryiko** [comment]
Right, but `skip_mods_and_typedefs()` is not supposed to be called with invalid type ID.

**Comment by brycekahle** [comment]
@anakryiko OK. Can you explain these checks that often accompany the calls to `skip_mods_and_typedefs()` then?
Example:
https://github.com/libbpf/libbpf/blob/66780a46cb9f7f593a0f19d86b2073d03c836f05/src/libbpf.c#L4868-L4870

**Comment by brycekahle** [comment]
To clarify, I don't understand why these checks are necessary if `skip_mods_and_typedefs` assumes `t` is always non-NULL.

**Comment by anakryiko** [comment]
they probably aren't necessary, could be defensive checks or maybe `skip_mods_and_typedefs()` evolved to have non-NULL assumption since original implementation
