### ISSUE TITLE
Sync up with Linux

### ISSUE THREAD

**Issue by jirislaby** [libbpf/libbpf#197]
Could you sync up, so that we have a fix for crashes on x86_32 included?

In particular https://github.com/torvalds/linux/commit/b2f9f1535bb93ee5fa2ea30ac1c26fa0d676154c.

**Comment by anakryiko** [comment]
It's been synced long time ago: https://github.com/libbpf/libbpf/commit/cd016d93f7bf280fe6f2dfc723257786dd3ffd00
