### ISSUE TITLE
Why don't you support Array of maps in bpf_object__init_user_maps?

### ISSUE THREAD

**Issue by takehaya** [libbpf/libbpf#205]
hi. everyone.

Thanks for a great tool!

I'm trying to generate a map in map from elf, but from what I've seen, it doesn't seem to be supported.
https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L1851

I also read the comments and saw that you wrote this Could you please tell me why the decision to not respond was made?

> Array of maps is not supported: only the first element is considered.

thanks:)

**Comment by anakryiko** [comment]
That comments doesn't mean what you think it means. And it is about a legacy code path. So just disregard it. Map-in-map is actually supported since a not so long ago and is using a more modern BTF-defined syntax. Please check out https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/progs/test_btf_map_in_map.c for examples.

**Comment by takehaya** [comment]
Thank you so much for replying!
Okay, so the comments were not particularly meaningful. Thank you.

If it's okay with you, can you tell me the code for the part of libbpf's implementation that supports map in map from BTF?

**Comment by anakryiko** [comment]
https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L2101-L2163
https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L4096-L4110

If you want to create map-in-map programmatically, look at https://github.com/libbpf/libbpf/blob/master/src/bpf.c#L157-L190

**Comment by takehaya** [comment]
Thank you, I'll use that as a reference for reading `map in map` in golang from elf! 🙏 

Excuse me, but could I ask one more question. I understand that something like btfmap can be referenced in the `.map` of elf.

But the binary built with clang doesn't have the `.map` ....
I'm confused.  How does the  `.map`  get included in my binary?

**Comment by anakryiko** [comment]
It's ".maps" section. It's emitted by compiler. When you define a map, it's actually defining a variable (from compiler standpoint), and then you instruct compiler to put that variable into .maps ELF section with SEC(".maps"), which is expanded into `__attribute__((section(".maps")))`.

**Comment by takehaya** [comment]
I See!

So the definition as it was before is insufficient to move it...

An example of the previous definition

> struct bpf_map_def SEC("maps") xdpcap_hook = XDPCAP_HOOK();

Now.

> struct xdpcap_hook {~~}xdpcap_hook SEC(".maps");

Why did you decide to separate `map` and `.map`? Is it for compatibility?

**Comment by anakryiko** [comment]
.maps uses an entirely different syntax and underlying mechanism for parsing map definitions, which is more extensible and more powerful. So we split legacy "maps" section from new ".maps" section.
