### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by bluca** [libbpf/libbpf#228]
Hi,

Some users of libbpf are making use of new symbols from the yet unreleased libbpf 0.3.0 in their released, stable versions - which is unfortunate.
Now that kernel 5.10 is out and there's a fair few new APIs, would it be possible to do a new release? The deadline for Debian 11 is fast approaching, so it would be really great if that was possible.

Thanks!

CC @anakryiko @borkmann

**Comment by anakryiko** [comment]
https://github.com/libbpf/libbpf/releases/tag/v0.3

**Comment by bluca** [comment]
Thank you!
