### ISSUE TITLE
libbpf: elf: skipping unrecognized data section(16) .eh_frame

### ISSUE THREAD

**Issue by niclashedam** [libbpf/libbpf#238]
I'm trying to resolve https://github.com/niclashedam/ebpf-kill-example/issues/2. When I compile my simple eBPF and load it with libbpf, I receive two warnings from libelf.

```
libbpf: elf: skipping unrecognized data section(16) .eh_frame
libbpf: elf: skipping relo section(17) .rel.eh_frame for section(16) .eh_frame
```

I compiled the program using `clang` and `llc`.

```
clang -S \
    -D __BPF_TRACING__ \
    -I/home/nhed/Development/ebpf-kill-example/src/../libbpf/src//root/usr/include/ \
    -Wall \
    -Werror \
    -O2 -emit-llvm -c -g kern.c
llc -march=bpf -filetype=obj -o kern.o kern.ll
```

The code results in the following assembly.

```
nhed@nhed-1:~/Development/ebpf-kill-example$ llvm-objdump -S src/kern.o

src/kern.o:	file format ELF64-BPF


Disassembly of section tracepoint/syscalls/sys_enter_kill:

0000000000000000 ebpf_kill_example:
;   if (ctx->sig != SIGKILL)
       0:	79 12 18 00 00 00 00 00	r2 = *(u64 *)(r1 + 24)
       1:	55 02 10 00 09 00 00 00	if r2 != 9 goto +16 <LBB0_2>
;   long key = labs(ctx->pid);
       2:	79 11 10 00 00 00 00 00	r1 = *(u64 *)(r1 + 16)
       3:	bf 12 00 00 00 00 00 00	r2 = r1
       4:	c7 02 00 00 3f 00 00 00	r2 s>>= 63
       5:	0f 21 00 00 00 00 00 00	r1 += r2
       6:	af 21 00 00 00 00 00 00	r1 ^= r2
       7:	7b 1a f8 ff 00 00 00 00	*(u64 *)(r10 - 8) = r1
       8:	b7 01 00 00 01 00 00 00	r1 = 1
;   int val = 1;
       9:	63 1a f4 ff 00 00 00 00	*(u32 *)(r10 - 12) = r1
      10:	bf a2 00 00 00 00 00 00	r2 = r10
;   long key = labs(ctx->pid);
      11:	07 02 00 00 f8 ff ff ff	r2 += -8
      12:	bf a3 00 00 00 00 00 00	r3 = r10
      13:	07 03 00 00 f4 ff ff ff	r3 += -12
;   bpf_map_update_elem(&kill_map, &key, &val, BPF_NOEXIST);
      14:	18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r1 = 0 ll
      16:	b7 04 00 00 01 00 00 00	r4 = 1
      17:	85 00 00 00 02 00 00 00	call 2

0000000000000090 LBB0_2:
; }
      18:	b7 00 00 00 00 00 00 00	r0 = 0
      19:	95 00 00 00 00 00 00 00	exit
```

I load the program using `bpf_prog_load` and `bpf_object__find_program_by_name`.

Can you help me understand why these warnings occour and how I can fix them?

**Comment by anakryiko** [comment]
These warnings are benign, though I'm not sure why .eh_frame sections is generated. Can you share your C code that causes this? cc @yonghong-song, do you know when/why .eh_frame would be generated for BPF code?

**Comment by niclashedam** [comment]
Hi, sure. Thanks!

```
#include <linux/bpf.h>
#include <stdlib.h>

#include <bpf/bpf_helpers.h>

#define SIGKILL 9

struct {
  __uint(type, BPF_MAP_TYPE_HASH);
  __type(key, long);
  __type(value, char);
  __uint(max_entries, 64);
} kill_map SEC(".maps");

struct syscalls_enter_kill_args {
  long long pad;

  long syscall_nr;
  long pid;
  long sig;
};

SEC("tracepoint/syscalls/sys_enter_kill")
int ebpf_kill_example(struct syscalls_enter_kill_args *ctx) {
  if (ctx->sig != SIGKILL)
    return 0;

  long key = labs(ctx->pid);
  int val = 1;

  bpf_map_update_elem(&kill_map, &key, &val, BPF_NOEXIST);

  return 0;
}

char _license[] SEC("license") = "GPL";

```

**Comment by yonghong-song** [comment]
The .eh_frame is generated because the C code is compiled first with native architecture like
```
  clang -O2 -g -S -emit-llvm file.c  <==== native x86_64 arch
  llc -march=bpf file.ll
```

Compile with x64 arch will produce .eh_frame which tries to facilitate stack unwinding.
If you compile all the way with bpf `clang --target bpf ...`, you should not see .eh_frame.

**Comment by anakryiko** [comment]
#include <stdlib.h> is also suspicious, I don't think you are supposed to use that from BPF code. It definitely won't work if you call any of stdlib.h's functions. If you need type definitions, usually stdbool.h and stddef.h and stdint.h are the headers to use, I think.

**Comment by niclashedam** [comment]
@anakryiko The eBPF code in question is actually an example I wrote to show a bare minimum example. I have included stdlib to show that you can actually call glibc functions in eBPF (see `long key = labs(ctx->pid);`).

**Comment by niclashedam** [comment]
I can inform you that removing the stdlib include and stdlib call changed nothing.

```
nhed@nhed-1:~/Development/ebpf-kill-example$ llvm-objdump -S src/kern.o

src/kern.o:	file format ELF64-BPF


Disassembly of section tracepoint/syscalls/sys_enter_kill:

0000000000000000 ebpf_kill_example:
;   if (ctx->sig != SIGKILL)
       0:	79 12 18 00 00 00 00 00	r2 = *(u64 *)(r1 + 24)
       1:	55 02 0c 00 09 00 00 00	if r2 != 9 goto +12 <LBB0_2>
;   long key = ctx->pid;
       2:	79 11 10 00 00 00 00 00	r1 = *(u64 *)(r1 + 16)
       3:	7b 1a f8 ff 00 00 00 00	*(u64 *)(r10 - 8) = r1
       4:	b7 01 00 00 01 00 00 00	r1 = 1
;   int val = 1;
       5:	63 1a f4 ff 00 00 00 00	*(u32 *)(r10 - 12) = r1
       6:	bf a2 00 00 00 00 00 00	r2 = r10
;   long key = ctx->pid;
       7:	07 02 00 00 f8 ff ff ff	r2 += -8
       8:	bf a3 00 00 00 00 00 00	r3 = r10
       9:	07 03 00 00 f4 ff ff ff	r3 += -12
;   bpf_map_update_elem(&kill_map, &key, &val, BPF_NOEXIST);
      10:	18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r1 = 0 ll
      12:	b7 04 00 00 01 00 00 00	r4 = 1
      13:	85 00 00 00 02 00 00 00	call 2

0000000000000070 LBB0_2:
; }
      14:	b7 00 00 00 00 00 00 00	r0 = 0
      15:	95 00 00 00 00 00 00 00	exit
```

```
nhed@nhed-1:~/Development/ebpf-kill-example$ make test
./test/test.sh
-- Loading eBPF program.
libbpf: elf: skipping unrecognized data section(16) .eh_frame
libbpf: elf: skipping relo section(17) .rel.eh_frame for section(16) .eh_frame
```

**Comment by niclashedam** [comment]
@yonghong-song Thank you. This resolved the issue.

**Comment by anakryiko** [comment]
> @anakryiko The eBPF code in question is actually an example I wrote to show a bare minimum example. I have included stdlib to show that you can actually call glibc functions in eBPF (see `long key = labs(ctx->pid);`).

You can't, generally speaking. In this case you are lucky that labs is either completely defined in the header (as static inline) or compiler just has an optimized fully-inlined implementation. Try using qsort() and see if that works.

**Comment by niclashedam** [comment]
@anakryiko I think we are saying the same thing. Qsort will of course not work, but that is because of the complexity and not the fact that it is a glibc function. If I understand it correctly you can include any gblic function that lives up to the requirements of the verifier.

**Comment by anakryiko** [comment]
I don't think we are. It's not just about verifier requirements, but also about where the code lives. qsort() is defined in glibc .so, and there is no such thing in BPF world. Which is why I'm saying using anything but *types* from standard headers is prone to never work or break under some circumstances.
