### ISSUE TITLE
Facing issue while building libbpf

### ISSUE THREAD

**Issue by bsalunke** [libbpf/libbpf#248]
I'm trying to build libbpf on centos 7 with kernel verison:
[root@localhost portablebpf]# uname -r
3.10.0-514.el7.x86_64

 I'm getting following compilation error, I can understand the some of these feature might not be supported by underline kernel. 
e.g.PERF_EVENT_IOC_SET_BPF added in linux 4.1(https://elixir.bootlin.com/linux/v4.1.52/A/ident/PERF_EVENT_IOC_SET_BPF) so it will not work on my linux kernel 

However the cause of second compilation error is that PERF_COUNT_SW_BPF_OUTPUT is not available in 3.10 and got added in kernel version 4.4 (https://elixir.bootlin.com/linux/v4.4.260/A/ident/PERF_COUNT_SW_BPF_OUTPUT)

My questions is what  would be minimum kernel version on which libbpf would work w/o any issue? considering the fact it depends on the various kernel features. 

> root@localhost src]# make
>   MKDIR    staticobjs
>   CC       bpf.o
>   CC       btf.o
>   CC       libbpf.o
> libbpf.c: In function ‘bpf_program__attach_perf_event’:
> libbpf.c:9543:17: error: ‘PERF_EVENT_IOC_SET_BPF’ undeclared (first use in this function); did you mean ‘PERF_EVENT_IOC_ENABLE’?
>   if (ioctl(pfd, PERF_EVENT_IOC_SET_BPF, prog_fd) < 0) {
>                  ^~~~~~~~~~~~~~~~~~~~~~
>                  PERF_EVENT_IOC_ENABLE
> libbpf.c:9543:17: note: each undeclared identifier is reported only once for each function it appears in
> libbpf.c: In function ‘perf_buffer__new’:
> libbpf.c:10313:16: error: ‘PERF_COUNT_SW_BPF_OUTPUT’ undeclared (first use in this function); did you mean ‘PERF_COUNT_SW_CPU_CLOCK’?
>   attr.config = PERF_COUNT_SW_BPF_OUTPUT;
>                 ^~~~~~~~~~~~~~~~~~~~~~~~
>                 PERF_COUNT_SW_CPU_CLOCK
> make: *** [staticobjs/libbpf.o] Error 1

**Comment by anakryiko** [comment]
As you mentioned, it will all depend on the kernel features you are going to use, so there shouldn't be any libbpf-enforced minimum kernel versions.

As for the compilation errors. When building libbpf you should make sure that you are using Linux UAPI headers distributed with libbpf itself under include/uapi/linux directory in this repository.

For the future, please ask any generic BPF/libbpf questions on BPF mailing list. See https://github.com/libbpf/libbpf#bpflibbpf-usage-and-questions
