### ISSUE TITLE
Typo in xsk_socket__create_shared() causing logic failure when called multiple times

### ISSUE THREAD

**Issue by ajmmm** [libbpf/libbpf#259]
https://github.com/libbpf/libbpf/blob/a7502f2707421cb350b6b6ff8a39460ae5c5b477/src/xsk.c#L1096

There's a typo in xsk.c xsk_socket__create_shared() at line 1096.

The containing block of code is setting up the TX queue, but sets umem->rx_ring_setup_done = true, which should be tx_ring_setup_done.

Results in odd behaviour if calling the function multiple times, but it succeeds if I make the change in my local code.

**Comment by ajmmm** [comment]
Just an update - I think line 1093 should be changed too.

Current block (starting line 1087)
```
	if (tx && !tx_setup_done) {
		err = setsockopt(xsk->fd, SOL_XDP, XDP_TX_RING,
				 &xsk->config.tx_size,
				 sizeof(xsk->config.tx_size));
		if (err) {
			err = -errno;
			goto out_put_ctx;
		}
		if (xsk->fd == umem->fd)
			umem->rx_ring_setup_done = true;
	}
```

I think within the error condition, the goto should actually be to **out_mmap_rx**.
Otherwise, rx memory won't be unmapped in scenarios where tx ring setup fails.

Suggested change:
```
	if (tx && !tx_setup_done) {
		err = setsockopt(xsk->fd, SOL_XDP, XDP_TX_RING,
				 &xsk->config.tx_size,
				 sizeof(xsk->config.tx_size));
		if (err) {
			err = -errno;
			goto out_mmap_rx;
		}
		if (xsk->fd == umem->fd)
			umem->rx_ring_setup_done = true;
	}
```

**Comment by anakryiko** [comment]
libbpf patches are not accepted through this repo, sorry. See https://github.com/libbpf/libbpf#bpflibbpf-usage-and-questions, you need to send a patch or at least write an email to bpf@vger.kernel.org. Thank you!

**Comment by ajmmm** [comment]
OK will do!
