### ISSUE TITLE
drop some packets before redirecting to userspace

### ISSUE THREAD

**Issue by iwaniwaniwan012** [libbpf/libbpf#26]
For new version of libbpf in kernel was removed xdpsock_kern.c . So i saw bpf alu like code for loading on NIC. Can i write some xdp code for kernel and turn it into struct bpf_insn or something like this? Or same way i can not get performance?

**Comment by anakryiko** [comment]
I'n not exactly clear on what you are trying to achieve. Can you please provide some examples?
