### ISSUE TITLE
Mismatch in versioning?

### ISSUE THREAD

**Issue by kloczek** [libbpf/libbpf#265]
Latest git tag it is `v0.3` however in src/libbpf.map is used used three digit versioning like `LIBBPF_0.3.0`

**Comment by anakryiko** [comment]
Is this breaking anything? I just felt like doing v0.3.0 is unnecessary, but if it is causing any problems, let me know.

**Comment by kloczek** [comment]
I see that some vendors are not using version used in git tag but version which is used in ABI definition.

**Comment by anakryiko** [comment]
I see, thanks. With next version I'll stick to v0.4.0 form then.

**Comment by kloczek** [comment]
Perfect!! 
Thank you very much😀
