### ISSUE TITLE
clang seems to be failing to compile libbpf

### ISSUE THREAD

**Issue by evverx** [libbpf/libbpf#27]
It was originally discovered by the systemd CI in https://github.com/systemd/systemd/pull/12151:
```sh
FAILED: src/libbpf/9e6d599@@bpf@sta/bpf_next_src_libbpf_src_libbpf.c.o
clang -Isrc/libbpf/9e6d599@@bpf@sta -Isrc/libbpf -I../src/libbpf -I../src/libbpf/bpf_next/src/libbpf/include -I../src/libbpf/bpf_next/src/libbpf/include/uapi -Xclang -fcolor-diagnostics -fsanitize=address,undefined -fno-omit-frame-pointer -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=gnu99 -g -Wextra -Werror=undef -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Wdate-time -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result '-Wno-error=#warnings' -Wno-string-plus-int -Wno-error=nonnull -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -Wno-typedef-redefinition -Wno-gnu-variable-sized-type-not-at-end -Werror=shadow -include config.h -fPIC -g -O2 -Werror -Wall -Wno-pointer-arith -Wno-sign-compare  -MD -MQ 'src/libbpf/9e6d599@@bpf@sta/bpf_next_src_libbpf_src_libbpf.c.o' -MF 'src/libbpf/9e6d599@@bpf@sta/bpf_next_src_libbpf_src_libbpf.c.o.d' -o 'src/libbpf/9e6d599@@bpf@sta/bpf_next_src_libbpf_src_libbpf.c.o' -c ../src/libbpf/bpf_next/src/libbpf/src/libbpf.c
../src/libbpf/bpf_next/src/libbpf/src/libbpf.c:63:26: error: format string is not a string literal [-Werror,-Wformat-nonliteral]
        return vfprintf(stderr, format, args);
                                ^~~~~~
1 error generated.
```

**Comment by yonghong-song** [comment]
The code is from kernel tools/lib/bpf/libbpf.c. The code is written that way as the format string can be set by user, e.g., in libbpf.h
```
typedef int (*libbpf_print_fn_t)(enum libbpf_print_level level,
                                 const char *, va_list ap);

LIBBPF_API void libbpf_set_print(libbpf_print_fn_t fn);
```

The above compilation with flags specified by systemd. Maybe systemd can disable format-nonliteral warning to suppress the error.

**Comment by evverx** [comment]
@yonghong-song thank you for taking a look! I'm not familiar with the codebase so I'm afraid at this point I'm not sure whether it's OK to suppress those warnings. In `systemd` we usually add something like
```
        _Pragma("GCC diagnostic push"); 
        _Pragma("GCC diagnostic ignored \"-Wformat-nonliteral\"");
       ...
       _Pragma("GCC diagnostic pop");
```
if it's safe to ignore the warnings so that it doesn't matter what options people use to compile `systemd`. Anyway, I believe @wat-ze-hex knows how to build `libbpf` much better than I do and it would most likely be best to let @wat-ze-hex decide what to do.

@wat-ze-hex could you also take a look at https://github.com/libbpf/libbpf/issues/28? That PR is related to https://github.com/systemd/systemd/pull/12151 too.

**Comment by yonghong-song** [comment]
I guess, you could add some `#pragma clang diagnostic ignored ...` in the code base. But in this case, looks like gcc does not produce warning? So this makes add a clang specific suppress pragma odd.

**Comment by evverx** [comment]
Interestingly, I thought that `gcc` wasn't happy either but according to https://travis-ci.org/systemd/systemd/builds/516729445, gcc was fine while clang complained about the string literal. I'm not sure what is going on.

**Comment by rdna** [comment]
This is the second time I see this problem. In another project I added pragma to ignore this warning. IMO it makes sense to add it to libbpf so that it's fixed in one place instead of fixing it in every project.
I sent the fix to netdev: https://marc.info/?l=linux-netdev&m=155461563726406&w=2

**Comment by yonghong-song** [comment]
If this is the case for gcc, we should add clang pragma as well. Maybe pragma should be guarded by respective compiler macro? I did not test whether this is needed or not, @evverx, since you have access to clang build environment, could you help test?

**Comment by yonghong-song** [comment]
@evverx the @rdna's patch has been merged into bpf-next. Next bpf-next sync to libbpf should have this issue fixed.

**Comment by evverx** [comment]
@yonghong-song I've just applied the patch and run the script used on Travis CI (which is currently trying to build https://github.com/systemd/systemd/pull/12151 with gcc and clang). I'll close the issue when it finishes (the script builds weirds containers so it might take a while :-))

**Comment by evverx** [comment]
> Next bpf-next sync to libbpf should have this issue fixed.

OK. The two stages (where sanitizers aren't used) out of 5 should become green once the submodule in https://github.com/systemd/systemd/pull/12151 is updated and the code is force-pushed.

I'm wondering if there's a cron job or something like that that sync the code regularly. O does it happen when a considerable number of changes accumulates?

**Comment by yonghong-song** [comment]
@evverx Not yet for a cron job to sync the code regularly. But this is certainly the goal. We need to add some test before doing automatic pulling.
