### ISSUE TITLE
libbpf 1.0: support multiple .rodata*, .data*, .bss* sections

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#274]
Support multiple .rodata/.data/.bss sections. Create separate backing BPF_MAP_TYPE_ARRAY for each. This will finally get rid of annoying 

```
libbpf: elf: skipping unrecognized data section(8) .rodata.str1.1
```

warning. It will also support passing string literals to bpf_trace_printg():

```
bpf_printk("%s, %s!", "Hello", "world");
```

Having the ability to use multiple .data sections and putting dedicated global variables into separate .data.custom section also opens up some new and interesting possibilities (like dynamically sizing global arrays, without using BPF_MAP_TYPE_ARRAY map).

**Comment by anakryiko** [comment]
Closed via https://github.com/libbpf/libbpf/commit/5bf62459b1857946365d79900941b2487654e618

**Comment by chengshuyi** [comment]
Hi, This will cause the kernel that does not support global data to be unable to use __bpf_printk.

commit url: https://github.com/libbpf/libbpf/commit/5bf62459b1857946365d79900941b2487654e618#
trouble code is :

    } else if (strcmp(name, RODATA_SEC) == 0 ||
				       str_has_pfx(name, RODATA_SEC ".")) {

**Comment by anakryiko** [comment]
How is that piece of code changes anything about __bpf_printk?

If anything, https://github.com/libbpf/libbpf/commit/989d7189cdcf43480c7d1f15a13ad13333e0877d might cause regression. If that's the case for you, please use `#define BPF_NO_GLOBAL_DATA` before including bpf_helpers.h

**Comment by chengshuyi** [comment]
> How is that piece of code changes anything about __bpf_printk?
> 
> If anything, [989d718](https://github.com/libbpf/libbpf/commit/989d7189cdcf43480c7d1f15a13ad13333e0877d) might cause regression. If that's the case for you, please use `#define BPF_NO_GLOBAL_DATA` before including bpf_helpers.h

Regardless of whether there is static const or not, the clang compiler will put the string in the .rodata.str.1 section. Therefore, this part of the code parses the rodata.str.1 section, regards it as a global variable, and creates a map.

**Comment by leodido** [comment]
> Regardless of whether there is static const or not, the clang compiler will put the string in the .rodata.str.1 section. 

I've seen this happening too, but...

> Therefore, this part of the code parses the rodata.str.1 section, regards it as a global variable, and creates a map.

Whether the `____fmt` variable ends up into the skeleton maps (I guess you mean something like `skel->rodata->____fmt`) depends on the visibility that your Clang gives to the `____fmt` variable.

**Comment by anakryiko** [comment]
Either way this problem should have been fixed by https://github.com/libbpf/libbpf/commit/5c31bcf220f66e70f39fd141f5b0c55c6ab65e8e, forgot to mention it here. Please let me know if it still persists, though.
