### ISSUE TITLE
libbpf 1.0: deprecate few obscure BTF-related APIs

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#277]
Details: https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0#btfh-apis

List of APIs to deprecate:
  - btf__get_map_kv_tids();
  - btf_ext__reloc_func_info();
  - btf_ext__reloc_line_info();
  - btf_ext__func_info_rec_size();
  - btf_ext__line_info_rec_size().

We need to make sure BCC doesn't use these deprecated APIs internally.

**Comment by chenhengqi** [comment]
`btf_ext__func_info_rec_size()` and `btf_ext__line_info_rec_size()` are  trivial,
but both `struct btf_ext` and `struct btf_ext_info` are internal to `libbpf` itself.
Did not figure out a way to implement that without exposing these structs. :(

**Comment by anakryiko** [comment]
Yes, but .BTF.ext format is well-defined (in the sense that it's sort of like an ABI itself, even though it's not really described very clearly in the kernel). So BCC would need to implement its own parsing of .BTF.ext.

We could have left btf_ext__func_info_rec_size() and btf_ext__line_info_rec_size(), but whoever needs them will need to parse and understand .BTF.ext at a deeper level anyways, so at that point extracting the record size is the simplest of problems.

**Comment by chenhengqi** [comment]
Thanks for the insight. Might have a try later.
