### ISSUE TITLE
libbpf 1.0: unify and clean up bpf_map_create APIs

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#282]
Details: https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0#bpfh-low-level-apis

**Comment by chenhengqi** [comment]
@anakryiko  I would like to work on this issue, please assign it to me.

**Comment by chenhengqi** [comment]
> hey @chenhengqi, I'll happily assign this task to you, but I think we need to hold of just a little bit right now, as I'm still figuring out the overall strategy with low-level APIs (there is a similar issue for BPF_PROG_LOAD command). So instead of causing you to go over few unnecessary iterations, please give me a bit of time to think through the overall strategy first and try to lay it out as part of BPF_PROG_LOAD APIs. How does that sound?
> 

OK. I will watch the mailing list to see how BPF_PROG_LOAD landed and get to this later.

> Meanwhile, if you are looking for something a bit bigger to help with, I'd suggest looking at #354, it seems pretty interesting to me and a nice feature to have for completeness.

Yeah, let me invest some efforts on #354 first.

**Comment by chenhengqi** [comment]
Sorry, I've just unassigned myself on this issue. I will keep working on #354 .
