### ISSUE TITLE
libbpf 1.0: deprecate bpf_object__find_program_by_title API

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#292]
Details: https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0#libbpfh-high-level-apis

**Comment by thefallentree** [comment]
This api is pretty widely used in the tests, and I propose instead of removing this api we can just rename it to  `bpf_object__find_first_program_by_section_name()`

**Comment by anakryiko** [comment]
Ideally we should just migrate all selftests to use find_by_name(), which is the right thing to do and it sets a correct example. Using section name as a program unique identifier has a long and historic reasons, but we shouldn't encourage using it. This issue is exactly about migrating selftests to find_by_title(), which I couldn't do back then because it required a lot of changes and there were more important dependent features at that time.

**Comment by thefallentree** [comment]
SG, I can do that.
