### ISSUE TITLE
libbpf 1.0: deprecate bpf_program__title() API

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#297]
Details: https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0#libbpfh-high-level-apis

**Comment by thefallentree** [comment]
This has already been fixed: https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/tools/lib/bpf/libbpf.h?id=52109584202783e90a83c95103307a9a03ba7d9e
