### ISSUE TITLE
libbpf 1.0: deprecate per-bpf_program instance APIs (bpf_program__nth_fd, bpf_program__{pin,unpin}_instance)

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#300]
Details: https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0#libbpfh-high-level-apis

**Comment by chengshuyi** [comment]
Hi, The perf tool also uses this feature, see tools/perf/util/bpf-loader.c

**Comment by anakryiko** [comment]
It does now with https://patchwork.kernel.org/project/netdevbpf/patch/20211025224531.1088894-3-andrii@kernel.org/ ! See https://github.com/anakryiko/retsnoop/pull/1 for how retsnoop is using that.
