### ISSUE TITLE
libbpf 1.0: remove bpf_object__find_map_by_offset API

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#302]
Details: https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0#libbpfh-high-level-apis

APIs are going to be removed right before 1.0 release, so this shouldn't be done as a patch just yet.

**Comment by tallossos** [comment]
Hello!
I've submitted a patch for this - [Lore](https://lore.kernel.org/bpf/20210722162526.32444-1-tallossos@gmail.com/T/#u).
