### ISSUE TITLE
Add btf__get_from_id() API that support split BTF

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#314]
Add _split variant of btf__get_from_id() API. The name should take into account https://github.com/libbpf/libbpf/issues/278, though.

**Comment by qmonnet** [comment]
I submitted a patch for this as part of a series:
- [Patchwork](https://patchwork.kernel.org/project/netdevbpf/list/?series=515513)
- [Lore](https://lore.kernel.org/bpf/20210714141532.28526-1-quentin@isovalent.com/t/#u)

**Comment by qmonnet** [comment]
v3 of the patchset was [merged into bpf-next](https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=f309b4ba989d96c192edd0d730d85bc1dd92a64a), and this issue can be closed.

**Comment by anakryiko** [comment]
see https://lore.kernel.org/bpf/CAEf4BzbtPFEbme_KZQA+n-gCgC+xp-v+270BBCi+89smi6pzkA@mail.gmail.com/, we should start doing that, so that we don't have to remember to close issues.

**Comment by qmonnet** [comment]
Ok, happy to use it next time.
