### ISSUE TITLE
kernel/libbpf: add multi-argument bpf_trace_printk() helper similar to bpf_snprintf()

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#315]
bpf_snprintf() kernel-side implementation: https://lore.kernel.org/bpf/20210419155243.1632274-4-revest@chromium.org/
BPF_SNPRINTF() macro wrapping multi-arg passing on libbpf side: https://lore.kernel.org/bpf/20210419155243.1632274-6-revest@chromium.org/

**Comment by davemarchevsky** [comment]
I've submitted a [patchset](https://lore.kernel.org/bpf/20210821025837.1614098-1-davemarchevsky@fb.com/T/#m5c62f5a91af7bb13335bc11d4d044325f13fe518) implementing this
