### ISSUE TITLE
libbpf: add ability to override/augment vmlinux BTF from bpf_object_open_opts

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#318]
Add ability to specify a custom vmlinux BTF through bpf_object_open_opts. See last attempt and surrounding discussion at https://lore.kernel.org/bpf/CAEf4Bza3ETtToi8CMk13FyySVu=Qa0u35mH8RPeyfyw8aZFqgw@mail.gmail.com/

**Comment by chengshuyi** [comment]
I have sent a patch to promote the implementation of this feature. https://lore.kernel.org/bpf/e8a17455-e3e7-d259-b7ae-154cfa6f1a0a@linux.alibaba.com/T/#m4d9f7c6761fbd2b436b5dfe491cd864b70225804

**Comment by anakryiko** [comment]
https://patchwork.kernel.org/project/netdevbpf/list/?series=514753&state=* landed upstream. Will come through https://github.com/libbpf/libbpf/pull/335

**Comment by rafaeldtinoco** [comment]
If someone is interested, we are providing a distributions BTF files HUB (with an API) at: https://github.com/aquasecurity/btfhub soon.

**Comment by anakryiko** [comment]
@rafaeldtinoco once you have that up and running, it's probably better to announce that on bpf@vger mailing list as well, assuming more people are watching the mailing list than Github PRs.
