### ISSUE TITLE
kernel bpf test_progs - wrong libc version

### ISSUE THREAD

**Issue by geyslan** [libbpf/libbpf#321]
Trying to run [vmtest.sh](https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/tree/tools/testing/selftests/bpf/vmtest.sh) from the **bpf-next linux** `tools/testing/selftests/bpf` on Arch Linux raises this error:

```
./test_progs
./test_progs: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by ./test_progs)
```
VM:
https://libbpf-vmtest.s3-us-west-1.amazonaws.com/x86_64/libbpf-vmtest-rootfs-2020.09.27.tar.zst

```
[root@(none) /]# strings /usr/lib/libc.so.6 | grep '^GLIBC_2.' | tail
GLIBC_2.30
GLIBC_2.5
GLIBC_2.9
GLIBC_2.7
GLIBC_2.6
GLIBC_2.18
GLIBC_2.11
GLIBC_2.16
GLIBC_2.13
GLIBC_2.2.6
```
It would be nice to update [travis-ci/vmtest/configs/INDEX]( https://github.com/libbpf/libbpf/blob/899c45baa2fba6c24dd446776aa3efa8c9446c16/travis-ci/vmtest/configs/INDEX) to refer to a new image with GLIBC_2.33.

---

**Host settings:**

```
❯ strings /usr/lib/libc.so.6 | grep GLIBC_2.33
GLIBC_2.33
GLIBC_2.33

❯ uname -a
Linux hb 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux

❯ gcc --version
gcc (GCC) 11.1.0

❯ clang --version
clang version 13.0.0 (/home/uzu/.cache/yay/llvm-git/llvm-project ad381e39a52604ba07e1e027e7bdec1c287d9089)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by geyslan** [comment]
@sinkap JFYI. Thanks.

**Comment by anakryiko** [comment]
Please see README, questions like this should be sent to bpf@vger.kernel.org, where lots more people will see them and be able to help. In this particular case KP Singh is your best chance. So please send this to bpf@vger.kernel.org, thanks!

**Comment by geyslan** [comment]
I see, @anakryiko. I've already marked KP Singh in this thread, but I'll bring this to bpf@vger.kernel.org. Thanks for the instructions.

**Comment by geyslan** [comment]
Done. :+1: 

https://lore.kernel.org/bpf/CAGG-pUTpppu-voYuT81LiTMAUA5oAWwnAwYQVAhyPwj3CwnZPA@mail.gmail.com
