### ISSUE TITLE
why not support centos or  redhat

### ISSUE THREAD

**Issue by jony-one** [libbpf/libbpf#328]
why not support centos or  redhat os? the doc is not found. why?

**Comment by anakryiko** [comment]
centos and redhat are definitely supported. Can you please elaborate what exactly is the issue?

**Comment by jony-one** [comment]
i run centos kernel version 4.11.1-1.el7.elrepo.x86_64. but run tip old kernel version.
but nothing more, now run ubuntu
so, i want contributed to the BPF,converted from BCC to BPF CO-RE about c xdp program ,but i not fount xdp converted  doc .
can you provide some clues? thanks

**Comment by jony-one** [comment]
i can use `bpftrace -l `  find xdp entry point.
but how to use libbpf attach ip 、xdp or socket  rewrite packet!

**Comment by jony-one** [comment]
hi boy! libbpf I don’t seem to be able to find out if I have my own tc loader or I don’t know how to use it. The key is whether to use the command line to achieve？
Thanks

**Comment by jony-one** [comment]
i found bpf_tc_hook_create  , thank
