### ISSUE TITLE
Field understanding.

### ISSUE THREAD

**Issue by jony-one** [libbpf/libbpf#330]
Excuse me, I don’t understand the ifindex of bpf_prog_load_attr very well. I thought it was the serial number of the network number, but it didn’t seem to be. 
So this means...

thanks

**Comment by anakryiko** [comment]
Please see https://github.com/libbpf/libbpf#bpflibbpf-usage-and-questions, all general questions about BPF and libbpf should be sent to bpf@vger.kernel.org. Thanks.
