### ISSUE TITLE
LIBSUBDIR not determined correctly on most 64bit architectures

### ISSUE THREAD

**Issue by hramrach** [libbpf/libbpf#337]
The makefile has this code:
```
ifeq ($(shell uname -m),x86_64)
        LIBSUBDIR := lib64
else
        LIBSUBDIR := lib
endif

```
In shell I would do
```
if [ -z "$LIBSUBDIR" ] ; then case $(uname -m) in
        *64|*64be|*64eb|*64el|*64le|s390x) LIBSUBDIR=lib64 ;;
        *) LIBSUBDIR=lib ;;
esac ; fi
```
but not sure how to translate that into makefile

**Comment by anakryiko** [comment]
We can use regexp, see https://stackoverflow.com/questions/49871570/regex-in-makefile.

**Comment by hramrach** [comment]
On Sun, Jul 18, 2021 at 12:08:18PM -0700, Andrii Nakryiko wrote:
> We can use regexp, see https://stackoverflow.com/questions/49871570/regex-in-makefile.

That article actually says you cannot use regexp but you can embed shell
script.

**Comment by anakryiko** [comment]
> On Sun, Jul 18, 2021 at 12:08:18PM -0700, Andrii Nakryiko wrote: We can use regexp, see https://stackoverflow.com/questions/49871570/regex-in-makefile.
> That article actually says you cannot use regexp but you can embed shell script.

I meant $(shell) + bash's [[ =~ regexp]] test. But filter-out is simpler, of course. Let me try to fix the CI in next few days before I land the change.

**Comment by hramrach** [comment]
As also noted in the article there is no guarantee that the shell executed by make is bash so bash regexps are not an option, and embedding the case statement would be a bit unwieldy. Of course, you could also pipe the uname output through grep.
