### ISSUE TITLE
Directly modifying a register in uprobe handler

### ISSUE THREAD

**Issue by hyunsooda** [libbpf/libbpf#346]
Hi all,

I checked out [example](https://github.com/libbpf/libbpf-bootstrap/blob/master/examples/c/uprobe.c) and played by modifying something. Specifically, an error occurred when I directly modified a register value like the following.

``` c
int handle_uprobe(struct pt_regs* ctx) {
    ctx->rax = 123; // error occurs
}
```

However, I could modify with the function ```bpf_probe_write_user()```, and it seems to have a similar restriction when I make kernel module (```LKM```). The programming of LKM also has a similar function like ```bpf_probe_write_user()``` to read from userspace memory and occur error when we directly access that memory address. So, I wonder that there is a method to modify some registers (I'm guessing it may be an illegal operation from a security perspective).

Thank you

**Comment by chenhengqi** [comment]
In kernel, we have:

https://github.com/torvalds/linux/blob/62fb9874f5da54fdb243003b386128037319b219/kernel/trace/bpf_trace.c#L1083-L1102

I think it is not possible to update register values from BPF programs.

BPF has a helper bpf_override_return, but it works in a different way.

**Comment by hyunsooda** [comment]
Hi @chenhengqi,

Thanks for providing a good reference. [It seems to check whether the access is writing or reading](https://github.com/torvalds/linux/blob/62fb9874f5da54fdb243003b386128037319b219/kernel/trace/bpf_trace.c#L1090). ```bpf_override_return``` seems not proper method to modify registers in generally as it explained [here](https://github.com/torvalds/linux/blob/dbe69e43372212527abf48609aba7fc39a6daa27/tools/include/uapi/linux/bpf.h#L2718)

Let me close if you don't have any other comments. Thanks again.
