### ISSUE TITLE
libbpf doesn't have attach_tracepoint

### ISSUE THREAD

**Issue by joelagnel** [libbpf/libbpf#35]
Someone (possibly me) needs to add bpf_attach_tracepoint support to libbpf. This is one of the things missing here compared to BCC's libbpf.

Is anyone else working on this? Thanks

**Comment by yonghong-song** [comment]
@joelagnel No people are working on this yet. You are welcome to contribute it!

**Comment by joelagnel** [comment]
Thanks @yonghong-song , will do. Adding it to my list.

**Comment by anakryiko** [comment]
This was added in https://github.com/libbpf/libbpf/commit/01272d30403f406edddfef4562efed54bfbdae56.
