### ISSUE TITLE
Support static initialization of BPF_MAP_TYPE_PROG_ARRAY

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#354]
Support static initialization of BPF_MAP_TYPE_PROG_ARRAY maps (used for BPF tail calls) with a syntax similar to map-in-map initialization:

```
SEC("socket")
int tail_1(void *ctx) {
	return 42;
}

struct {
	__uint(type, BPF_MAP_TYPE_PROG_ARRAY);
	__uint(max_entries, 2);
	__type(key, int);
	__array(values, int ());
} prog_array_init SEC(".maps") = {
	.values = {
		[1] = (void *)&tail_1,
	},
};
```

See https://github.com/cilium/ebpf/issues/214 for previous discussion.

**Comment by anakryiko** [comment]
@chenhengqi are you planning to work on this? If not, it's totally fine, I'll just give it as a good ramp up task to people new to my team. Just didn't want to step on your toes. Please let me know.

**Comment by chenhengqi** [comment]
Sorry for the delay, but I am working on this issue now. :)
