### ISSUE TITLE
Support uniform BTF-defined key/value specification across all BPF maps

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#355]
Currently a bunch of (usually pretty specialized) BPF maps do not support specifying BTF types for they key and value. For such maps, specifying their definition like this:

```
struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __type(key, int);
    __type(value, int);
} my_perf_buf SEC(".maps");
```

Would actually produce warnings about retrying BPF map creation without BTF. Users are forced to know such nuances and use `__uint(key_size, 4)` instead. This is non-uniform, annoying, and inconvenient.

Instead, teach libbpf to recognize BPF maps that do not support specifying types for key and value, and queitly removing BTF type IDs when creating BPF map. But still use type information to calculate key and value sizes. That way the above definition will work with no warnings and no retries to create map, and key_size and value_size are going to be calculated properly.

**Comment by chenhengqi** [comment]
Interesting! Did not notice this subtle difference.

@anakryiko  You can assign this to me. I would like to work on this improvement. Thanks.
