### ISSUE TITLE
How to build for 32bit ARM by cross-compiling?

### ISSUE THREAD

**Issue by HA-sala** [libbpf/libbpf#360]
Hi, all:
   I want to build for 32bit ARM by cross-compiling.
   What should I do first? What parameters should be changed in Makefile？

**Comment by anakryiko** [comment]
I think this is something that you'll have to try to figure out yourself. You can see libbpf's Makefile, see what's missing there preventing your from cross-compiling it. If it's some shortcoming of how we set up libbpf's Makefile, we'll be able to fix and extend it.

**Comment by HA-sala** [comment]
Thank you very much!!! I'm already trying to do it. :)
