### ISSUE TITLE
fatal error: 'gnu/stubs-32.h' file not found while program 

### ISSUE THREAD

**Issue by advancevillage** [libbpf/libbpf#363]
Linux debian 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

/usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
```c
clang -Wall -g -O2 -target bpf -c sg.bpf.c -o sg.bpf.o
In file included from sg.bpf.c:9:
In file included from /usr/include/bpf/libbpf.h:14:
In file included from /usr/include/stdio.h:27:
In file included from /usr/include/bits/libc-header-start.h:33:
In file included from /usr/include/features.h:485:
/usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
# include <gnu/stubs-32.h>
          ^~~~~~~~~~~~~~~~
1 error generated.
```

The content of /usr/include/gnu/stubs.h is usually:
```c
#if !defined __x86_64__
# include <gnu/stubs-32.h>
#endif
#if defined __x86_64__ && defined __LP64__
# include <gnu/stubs-64.h>
#endif
#if defined __x86_64__ && defined __ILP32__
# include <gnu/stubs-x32.h>
#endif
```

If I'm compiling program on 64-bit architecture, I should have __x86_64__ and __LP64__ macros defined, but for some reason I don't have them . Why ? There is (most probably) no reason to use 32-bit headers of glibc and install multilib glibc.

**Comment by chenhengqi** [comment]
You are compiling a BPF program, but why do you need libbpf.h ?

**Comment by yonghong-song** [comment]
Ya, pls try to tweak your include files, some of them may not be really needed for bpf programs as bpf program cannot really call any libc functions. If your issue cannot be resolved, maybe you can post the whole reproducible test case so bcc community can help you.
