### ISSUE TITLE
On tools needing to compile and link against both libpcap and libbpf

### ISSUE THREAD

**Issue by paololucente** [libbpf/libbpf#376]
Dear libbpf Gurus,

Thanks so much for your work on this library. I am myself the developer of a tool that, as title says, needs to link against both libpcap and libbpf, each to achieve something different (if the use-case is of interest, i can share any further detail that may be needed).

To compile against libpcap, i have to include `pcap/pcap.h`; in turns that header calls for a `pcap/bpf.h` which has tons of definitions related to BPF. It is also possible to not include it by defining a PCAP_DONT_INCLUDE_PCAP_BPF_H. But this is not possible for me because i do rely on things like `struct bpf_program` defined in there (programs to express filters in libpcap).

At the same time, your `bpf/libbpf.h` header does include `linux/bpf.h` and i fully see why this is required, ie. you rely on stuff that is defined there like `struct bpf_map`. 

Getting closer to the issue, the problem is that `pcap/bpf.h` and `linux/bpf.h` don't totally overlap but they also don't totally diverge and seem to not be greatly coordinated. The specific issue i did bump into is that they both define `struct bpf_insn`: exact same thing but defined that just slight different to bother the compiler to consider it as a re-definition. 

Not sure if you have got ideas on how to handle this - if it is at all of interest to you, you may very well say that this is out of your hands being more an "ecosystem" issue. I thought to report it anyway, at very least it may be useful to others. The best i could do myself was to work it around by making sure that source files needing libpcap are separate by those needing libbpf (so far this setup holds, i hope it will also in future).

Paolo

**Comment by anakryiko** [comment]
Is pcap/bpf.h some custom header that libpcap defines on its own? libbpf just uses system-wide UAPI header, which is what libpcap should be probably using as well. So as you've guessed, I have no idea how to help with this, sorry.
