### ISSUE TITLE
libbpf: Netlink-based XDP prog detected, please unload it in order to lunch AF_XDP prog

### ISSUE THREAD

**Issue by jackmygreat** [libbpf/libbpf#381]
If you use custom xdp program, libbpf will have error. It reports :Netlink-based XDP prog detected, please unload it in order to lunch AF_XDP prog

**Comment by anakryiko** [comment]
Please see https://github.com/libbpf/libbpf#bpflibbpf-usage-and-questions and post a more expanded question to the mailing list. Thanks.
