### ISSUE TITLE
libbpf: switch libbpf_num_possible_cpus() implementation to simpler sysconf(_SC_NPROCESSORS_CONF) call

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#383]
There is no need to parse files. We need to double-check, but there is probably also no way that sysconf() can fail, which makes the API use simpler.

**Comment by mfrw** [comment]
@anakryiko Can I take a stab at it ?

**Comment by anakryiko** [comment]
Sure! Just keep in mind that libbpf changes have to go through kernel tree (bpf-next in this case), so please submit the patch to bpf@vger.kernel.org. See https://kernelnewbies.org/FirstKernelPatch and https://www.kernel.org/doc/html/latest/bpf/bpf_devel_QA.html if it will be your first kernel patch submission.

**Comment by mfrw** [comment]
One point, since `sysconf` sets the `errno` we probably can avoid using `libbpf_err`.
Is my understanding correct ?

**Comment by anakryiko** [comment]
Let's not split discussion into two parts. Replied on mailing list.

**Comment by mfrw** [comment]
@anakryiko Should we probably close this issue ?

**Comment by anakryiko** [comment]
We are not going to do that.  https://lore.kernel.org/bpf/ef0f23d0-456a-70b0-1ef9-2615a5528278@iogearbox.net/ for explanation of why not.
