### ISSUE TITLE
consider adding debuginfod-client support to fetch kernel debuginfo if needed & missing

### ISSUE THREAD

**Issue by fche** [libbpf/libbpf#399]
While BTF data is getting easier and easier to find, users might encounter older or oddball kernels where you need to go to ELF/DWARF content, and where it may not be already installed.  If this situation is worth worrying about, consider extending `btf__load_vmlinux_btf()` with calls to the elfutils debuginfod client CLI or API, after it fails to find something under all the `locations[]`.  It can attempt fetching debuginfo for the kernel (or a module .ko), based on the hexadecimal build-id.

https://sourceware.org/elfutils/Debuginfod.html

**Comment by anakryiko** [comment]
I think BTFGen approach discussed at https://lore.kernel.org/bpf/CAEf4BzbDBGEnztzEcXmCFMNyzTjJ3pY41ahzieu9yJ+EDHU0dg@mail.gmail.com/ is a better approach, please check the discussion thread.
