### ISSUE TITLE
Tagging versions

### ISSUE THREAD

**Issue by bluca** [libbpf/libbpf#42]
Not really an issue, more of a question: is there a plan to set a version independent of the kernel (separate from the ABI revision) and tag it on Github when a release happen?

Thanks!

**Comment by yonghong-song** [comment]
@bluca this has not been discussed yet. I think once libbpf is built officially by distro (fedora, ubuntu, etc.). The release version will be tagged.

**Comment by bluca** [comment]
@yonghong-song I see, thanks! I think it's a bit of a chicken-and-egg problem, if you would like distros to ship libbpf from this repository rather than the kernel source, I would suggest the libbpf maintainers should discuss versioning and tagging first. I think it's unlikely that distros will pick it up otherwise.
Debian for example is shipping from the kernel tree at the moment, and I asked the debian-kernel maintainers team if they'd like to switch over (I'd be happy to maintain it as a standalone source package), and they said "If they are going to do releases independently of the kernel, yes, that seems sensible. Otherwise, no"

**Comment by anakryiko** [comment]
@bluca, I've just tagged v0.0.3 release. Please see discussion in https://github.com/libbpf/libbpf/issues/47, we've agreed that we'll be tagging each release just before new merge window opens in bpf-next kernel tree. So each open window will mark a new release and all the new APIs will be added into a new version after that point in kernel and subsequently here on github.

**Comment by bluca** [comment]
Great, thank you!
