### ISSUE TITLE
BPF CO:RE on Kernel 4.19 (and others) (by manually adding vmlinux)

### ISSUE THREAD

**Issue by Dennis-Bbg** [libbpf/libbpf#423]
In the readme.md, "kernel built with CONFIG_DEBUG_INFO_BTF=y option" is mentioned as a prerequisite, which limits the usage of BPF CO:RE to kernel 5.2 or above (see BCC issue https://github.com/iovisor/bcc/issues/2905).

However shouldn't it be possible to still use BTF and BPF CO:RE with only "DEBUG_FS=y" kernel option and a manual extraction with pahole from dwarves package?

From btf.c:
```
struct {
	const char *path_fmt;
	bool raw_btf;
} locations[] = {
	/* try canonical vmlinux BTF through sysfs first */
	{ "/sys/kernel/btf/vmlinux", true /* raw BTF */ },
	/* fall back to trying to find vmlinux ELF on disk otherwise */
	{ "/boot/vmlinux-%1$s" },
	{ "/lib/modules/%1$s/vmlinux-%1$s" },
	{ "/lib/modules/%1$s/build/vmlinux" },
	{ "/usr/lib/modules/%1$s/kernel/vmlinux" },
	{ "/usr/lib/debug/boot/vmlinux-%1$s" },
	{ "/usr/lib/debug/boot/vmlinux-%1$s.debug" },
	{ "/usr/lib/debug/lib/modules/%1$s/vmlinux" },
};
```

What are the other locations and what is the difference between raw_btf = true/false?
How to generate the vmlinux-file with pahole?

I need to use BPF CO:RE on Kernel 4.19 and would really appreciate your help on how to get to a vmlinux file in the format needed.

**Comment by Dennis-Bbg** [comment]
@chenhengqi Thanks for your quick response and the link!

Unfortunately, btfgen seems to only generate part of the vmlinux file tailored to a specific application. So its usage seems to be to reduce the size of vmlinux file:
```
$ OBJ1=/tmp/btfgendemo/bcc/libbpf-tools/.output/execsnoop.bpf.o
$ OBJ2=/tmp/btfgendemo/bcc/libbpf-tools/.output/opensnoop.bpf.o
$ OBJ3=/tmp/btfgendemo/bcc/libbpf-tools/.output/bindsnoop.bpf.o

$ mkdir /tmp/btfgendemo/btfs
$ ./btfgen --inputdir=/tmp/btfgendemo/btfhub/ubuntu/focal/x86_64/ \
            --outputdir=/tmp/btfgendemo/btfs \
            --obj=$OBJ1 --obj=$OBJ2 --obj=$OBJ3
```

They also rely on btfhub to get vmlinux-files, but my kernel version is not supported there (https://github.com/aquasecurity/btfhub/blob/main/docs/supported-distros.md) :(

I guess my problem right now is how to use pahole to get the btf data in the right format (raw or not raw?) for libbpf.
Unfortunately, `pahole -j /boot/vmlinuz-4.18.0-25-generic` gives an error:
```
pahole: Multithreading requires elfutils >= 0.178. Continuing with a single thread...
libbpf: failed to get EHDR from /boot/vmlinuz-4.18.0-25-generic
pahole: file '/boot/vmlinuz-4.18.0-25-generic' has no supported type information.
```

**Comment by anakryiko** [comment]
As you rightly understood, you'll need to generate your own BTF. `pahole -j <path-to-vmlinux>` is the right command. You are passing vmlinuZ, which is an archive that contains more than just vmlinux. So just pass vmlinux image.

But if you are doing this for one specific kernel, you don't really need CO-RE, so keep that in mind. If you compile your BPF program against kernel headers, all the offsets and types will be correct without CO-RE, as long as you run BPF program only on that specific kernel.

But if not, once you have your custom BTF, use https://github.com/libbpf/libbpf/blob/master/src/libbpf.h#L110 to pass it to libbpf for CO-RE relocations.

**Comment by rafaeldtinoco** [comment]
> They also rely on btfhub to get vmlinux-files, but my kernel version is not supported there (https://github.com/aquasecurity/btfhub/blob/main/docs/supported-distros.md) :(

Why ? What is the kernel you are using ?

**Comment by Dennis-Bbg** [comment]
Thanks for your replys!


@rafaeldtinoco Thank you! Sorry that was an unclear statement from me; I guess BTF-GEN will accept any vmlinux. However, they only refer to btfhub.
I am using Kernel 4.18 now and 4.19 later, as well as 5.4 on the dev machine.


@anakryiko Thanks, got it now :D I compiled the kernel 4.18 for Ubuntu 16.10 following https://wiki.ubuntu.com/Kernel/BuildYourOwnKernel and found the vmlinux file there, which could be patched with 'pahole -J.

That's a good point, but I would prefer the CO:RE way, as the eBPF programs should be deployed to arbitrary linux versions.

Would you prefer using 'const char *btf_custom_path;' over placing it e.g. at _/usr/lib/debug/boot/vmlinux-4.18.0-25-generic_ (or one of the other search paths from https://github.com/libbpf/libbpf/blob/96268bf0c2b73b3ba91172a74179c2272870b8f8/src/btf.c#L4624-L4640)?
Using btf_custom_path gives the possibility to deploy a bunch of vmlinux-files for all targets together with the application, which might come handy, but is there another technical difference?



Unfortunately, now I get another error: `libbpf: load bpf program failed: Invalid argument`
```
libbpf: loading kernel BTF '/usr/lib/debug/boot/vmlinux-4.18.0-25-generic': 0
libbpf: map:stackdata_map container_name:____btf_map_stackdata_map cannot be found in BTF. Missing BPF_ANNOTATE_KV_PAIR?
libbpf: map 'stackdata_map': created successfully, fd=4
libbpf: sec 'uprobe': found 2 CO-RE relocations
libbpf: CO-RE relocating [0] struct pt_regs: found target candidate [201] struct pt_regs in [vmlinux]
libbpf: prog 'trace_func_entry': relo #0: kind <byte_off> (0), spec is [2] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'trace_func_entry': relo #0: matching candidate #0 [201] struct pt_regs.di (0:14 @ offset 112)
libbpf: prog 'trace_func_entry': relo #0: patched insn #2 (ALU/ALU64) imm 112 -> 112
libbpf: prog 'trace_func_entry': relo #1: kind <byte_off> (0), spec is [2] struct pt_regs.si (0:13 @ offset 104)
libbpf: prog 'trace_func_entry': relo #1: matching candidate #0 [201] struct pt_regs.si (0:13 @ offset 104)
libbpf: prog 'trace_func_entry': relo #1: patched insn #9 (ALU/ALU64) imm 104 -> 104
libbpf: sec 'uretprobe': found 1 CO-RE relocations
libbpf: prog 'trace_func_exit': relo #0: kind <byte_off> (0), spec is [2] struct pt_regs.ax (0:10 @ offset 80)
libbpf: prog 'trace_func_exit': relo #0: matching candidate #0 [201] struct pt_regs.ax (0:10 @ offset 80)
libbpf: prog 'trace_func_exit': relo #0: patched insn #2 (ALU/ALU64) imm 80 -> 80
libbpf: load bpf program failed: Invalid argument
libbpf: failed to load program 'trace_func_entry'
libbpf: failed to load object 'main.bpf.o'
 eBPF program not loaded 
```

by using this eBPF-Program (as a uProbe at function entry for a simple test App)
```
SEC("uprobe")
int trace_func_entry(struct pt_regs *ctx)
{
    u64 pid_tgid = bpf_get_current_pid_tgid();
    u32 pid = pid_tgid;

    int arg1;
    int arg2;

    arg1 = BPF_CORE_READ(ctx, di);  // Arguments of the uProbed function "int cal(int, int)"
    arg2 = PT_REGS_PARM2_CORE(ctx);

    __u32 key = 0;
    struct stack_trace_t* data;
    data = bpf_map_lookup_elem(&stackdata_map, &key);
	if (!data)
		return 0;

    size_t max_len = MAX_STACK_RAWTP * sizeof(__u64);
    data->user_stack_size = bpf_get_stack(ctx, data->user_stack, max_len, BPF_F_USER_STACK);

    return 0;
}
```

I guess there might be something wrong with 'struct pt_regs *ctx', or what does "Invalid argument" refer to?
Isn't struct pt_regs* just the cpu registers which should be the same, as both (development machine which compiled the bpf code on 5.4 and test machine with kernel 4.18) are amd64 on the same CPU?

Thanks in advance again for your help :)

**Comment by anakryiko** [comment]
> Would you prefer using 'const char *btf_custom_path;' over placing it e.g. at _/usr/lib/debug/boot/vmlinux-4.18.0-25-generic_ (or one of the other search paths from

yes, btf_custom_path was added specifically for situation like yours.

> Using btf_custom_path gives the possibility to deploy a bunch of vmlinux-files for all targets together with the application, which might come handy, but is there another technical difference?

Not really, but btf_custom_path is much cleaner approach rather than reverse-engineering where vmlinux image should lie in the system.

> 
> Unfortunately, now I get another error: `libbpf: load bpf program failed: Invalid argument`
> 

"Invalid argument" just means you got -EINVAL from bpf() syscall. There could be lots of reasons for this. Please post in bpf@vger mailing list with more details, if you'd like people to help you.

**Comment by Dennis-Bbg** [comment]
Sorry  for the late reply. I hope you had nice holidays :)
I'll try the mailing list. Thanks!
Is there a way to get more details than just "-EINVAL"?

**Comment by Dennis-Bbg** [comment]
Sorry for the late reply. I hope you had nice holidays :)
I'll try the mailing list. Thanks!
Is there a way to get more details than just "-EINVAL"?

Another question about ```btf_custom_path``` @anakryiko : I use the following code in the loader:
```C
struct bpf_object_open_opts* openOpts = (struct bpf_object_open_opts*) calloc(1, sizeof(bpf_object_open_opts));
openOpts->sz = sizeof(openOpts);
openOpts->btf_custom_path = "./vmlinux";           // Custom BTF path
struct bpf_object* main_bpf_obj = bpf_object__open_file("main.bpf.o", openOpts);
```

but it seems to not load it. What else do I need to do?

**Comment by anakryiko** [comment]
> Sorry for the late reply. I hope you had nice holidays :) I'll try the mailing list. Thanks! Is there a way to get more details than just "-EINVAL"?

You can try using https://github.com/anakryiko/retsnoop to get stack traces pointing inside the kernel source code. Especially if you have a very recent kernel, you can use `--lbr` option can get it down to the specific if check in the kernel. Give it a try, if you are curious.

> 
> Another question about `btf_custom_path` @anakryiko : I use the following code in the loader:
> 
> ```c
> struct bpf_object_open_opts* openOpts = (struct bpf_object_open_opts*) calloc(1, sizeof(bpf_object_open_opts));
> openOpts->sz = sizeof(openOpts);
> openOpts->btf_custom_path = "./vmlinux";           // Custom BTF path
> struct bpf_object* main_bpf_obj = bpf_object__open_file("main.bpf.o", openOpts);
> ```
> 
> but it seems to not load it. What else do I need to do?

You'll need to provide libbpf debug log output (see libbpf_set_print() API to set your custom callback). BTW, you don't have to calloc, you can use on the stack variable. Also use LIBBPF_OPTS macro:
```
LIBBPF_OPTS(bpf_object_open_opts, opts,
    .btf_custom_path = "./vmlinux",
);
bpf_object__open_file(...)
```

But again, please use mailing list so that others can help and/or learn as well.
