### ISSUE TITLE
libbpf: failed to find BTF info for global/extern symbol 'ENCAPSULATION_IP'

### ISSUE THREAD

**Issue by howardcai** [libbpf/libbpf#430]
start to exercise these bpf and while compiling self test, i encounter above errors. I did manual switch clang from 10 to clang-12 to avoid another error of llvm. 

I don't see where the above symbol defined except above bpf test file. is there something missing?

Have not dig in details of the specific test cases etc.

See below.

==
howardcai@system76-pc:~/Downloads/linux-5.15.11/tools/testing/selftests/bpf$ make
  GEN-SKEL [test_progs] test_cls_redirect_subprogs.skel.h
libbpf: failed to find BTF info for global/extern symbol 'ENCAPSULATION_IP'
Error: failed to link '/home/howardcai/Downloads/linux-5.15.11/tools/testing/selftests/bpf/test_cls_redirect_subprogs.o': Unknown error -2 (-2)
make: *** [Makefile:473: /home/howardcai/Downloads/linux-5.15.11/tools/testing/selftests/bpf/test_cls_redirect_subprogs.skel.h] Error 254

howardcai@system76-pc:~/Downloads/linux-5.15.11/tools/testing/selftests/bpf$ uname -a
Linux system76-pc 5.15.11 #1 SMP Mon Dec 27 19:59:34 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

howardcai@system76-pc:~/Downloads/linux-5.15.11/tools/testing/selftests/bpf$ clang --version
Ubuntu clang version 12.0.0-3ubuntu1~20.04.4
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /lib/llvm-12/bin

**Comment by howardcai** [comment]
maybe because I changed the clang from clang10 into clang-12 and did not make clean.

so I did a make clean, it seems passing the original test case compiling. and encounter the following errors again. 

 GEN-SKEL [test_progs] test_xdp_context_test_run.skel.h
  GEN-SKEL [test_progs] test_global_func13.skel.h
  GEN-SKEL [test_progs] kfunc_call_test_subprog.skel.h
libbpf: failed to find BTF for extern 'bpf_kfunc_call_test1' [27] section: -2
Error: failed to open BPF object file: No such file or directory
make: *** [Makefile:477: /home/howardcai/Downloads/linux-5.15.11/tools/testing/selftests/bpf/kfunc_call_test_subprog.skel.h] Error 255
make: *** Deleting file '/home/howardcai/Downloads/linux-5.15.11/tools/testing/selftests/bpf/kfunc_call_test_subprog.skel.h'

**Comment by anakryiko** [comment]
please see https://github.com/libbpf/libbpf#bpflibbpf-usage-and-questions and submit questions to the mailing list
