### ISSUE TITLE
Make BPF skeleton generation more robust

### ISSUE THREAD

**Issue by chenhengqi** [libbpf/libbpf#433]
In https://github.com/iovisor/bcc/pull/3777, a corner case is reported.

In the following code:
```c
const volatile dev_t value = 0;

SEC("raw_tp/sched_process_exit")
int handle_tp(void *ctx)
{
        bpf_printk("blabla");
        return 0;
}
```
If `value` (`sizeof(dev_t) == 4`) get updated from userspace (`sizeof(dev_t) == 8`)
it will accidentally overwrite the content of "blabla" in `bpf_printk` statement, causing it
to print nothing.

Before update, we have the following in rodata section:
```
"\0\0\0\0blabla\0"
```
After update `value` to 100, we have:
```
"0x64\0\0\0\0\0\0\0la\0"
```

It's not easy to fix this in userspace, because we can't simply `undef` this `dev_t` typedef.

Maybe we can fix this by:
* Treat them as bitfield in skeleton, `dev_t value:32`
* Provide setters for rodata fields in skeleton and use `memcpy` to update those fields

**Comment by anakryiko** [comment]
It's annoying issue for sure that sizeof(dev_t) differs between kernel and user-space, but I'm not sure there is a great fix from libbpf/skeleton side. We can't detect this during the skeleton generation time to warn users.

My recommendation would be to stick to using __u32/__u64 types as much as possible to avoid such surprises.

We could make skeleton generation code always use underlying primitive type (e.g., int) to avoid this for primitive types. There could still be issues with other standard types defined in libc differently than in the kernel. But at least for dev_t, pid_t and others it would solve the problem and shouldn't be problematic to use from user-space.

**Comment by chenhengqi** [comment]
> It's annoying issue for sure that sizeof(dev_t) differs between kernel and user-space, but I'm not sure there is a great fix from libbpf/skeleton side. We can't detect this during the skeleton generation time to warn users.
> 
> My recommendation would be to stick to using __u32/__u64 types as much as possible to avoid such surprises.
> 

Glad to know that you prefer this approach, will keep this in mind.
I am going to accept changes in iovisor/bcc#3777 .

> We could make skeleton generation code always use underlying primitive type (e.g., int) to avoid this for primitive types. There could still be issues with other standard types defined in libc differently than in the kernel. But at least for dev_t, pid_t and others it would solve the problem and shouldn't be problematic to use from user-space.

This is much simpler and clearer than what I propose above. Will try to make an RFC to the BPF mailing list.

**Comment by anakryiko** [comment]
Implemented in https://github.com/libbpf/bpftool/commit/219a89d7f5e9697e9f0ad71c2ba214d742761918
