### ISSUE TITLE
Consume perf buffer content when the event number in buffer is lower than wakeup_events

### ISSUE THREAD

**Issue by rainkin1993** [libbpf/libbpf#438]
I have a perf ring where wakeup_events is higher than 1, (i.e., 1000).
My goal is to consume the remaining events after a timeout (i.e., 1s) while the event number in the buffer is lower than wakeup_events.

I use the following two codes to do that. But I am not sure which one is **correct** and which one has better **performance**;

Code A:
```
while (perf_buffer__poll(pb, 1000) >= 0)
{
    ...
    // if the above perf_buffer__poll successed, skip the following perf_buffer_consume; otherwise, do that
    perf_buffer__consume(pb);
}
```

Code B: do not wait for notifications and just iterate all buffers and consume events. 
In my understanding, the perf buffer number usually is the same as the CPU core number which is relatively small, thus iterating all buffers seem fine for performance.
```
while (perf_buffer__consume(pb) >= 0)
{
    sleep(1); // 1 s
}
```

**Comment by anakryiko** [comment]
Both correct in the sense that you'll get your events. poll with timeout + consume (case A) will give you events immediately if there are a lot of them, while case B would drop messages if a lot of them get scheduled fast. It depends on your needs, but both uses are supported.
