### ISSUE TITLE
libbpf 0.7 release plans?

### ISSUE THREAD

**Issue by martinetd** [libbpf/libbpf#440]
Hi,

bcc released 0.24 which depends on unreleased changes in libbpf, which in turns caused problems when trying to upgrade it in nixos for bpftrace which comes with its own version of libbpf,  causing bcc to calls wrong versions of the symbols.
(see https://github.com/NixOS/nixpkgs/pull/155080 for details if interested)

The solution of packaging current libbpf master and using it for both seems to work, so I think that's the best way forward -- what are the current plans for a 0.7 release?

Thanks!

**Comment by vcunat** [comment]
On a quick glance, I think a couple of CVEs also got fixed since 0.6.1: https://github.com/NixOS/nixpkgs/issues/155331  (I couldn't immediately see by which particular commit)

**Comment by evverx** [comment]
It seems a bash script automatically assigning pointless CVEs based on OSS-Fuzz bug reports has been resurrected somehow even though it was seemingly turned off when I complained about it. What's weird is that OSS-Fuzz has nothing to do with it and nobody actually knows where those CVEs come from.

**Comment by martinetd** [comment]
Yes, I've commented on the nixos issue that these are probably not worth CVEs (no trust boundary crossed that I can see); interesting to read they come out of nowhere though...

We'd nevertheless like to update as there are other bug fixes and because it's required for the new bcc version, but it's not great to just package an arbitrary tip of the master branch so if a new release is planned soonish I'd appreciate it and will wait for it :)

**Comment by evverx** [comment]
> interesting to read they come out of nowhere though...

I've just opened https://github.com/google/oss-fuzz/issues/7146 to hopefully track that down.

> We'd nevertheless like to update as there are other bug fixes and because it's required for the new bcc version

I think it would be great if libbpf could be updated. But I just kind of maintain the fuzzer so I can't comment on new releases :-)

**Comment by anakryiko** [comment]
The plan with v0.7 was to try to complete the rest of planned 1.0-related tasks (https://github.com/libbpf/libbpf/issues?q=is%3Aissue+is%3Aopen+label%3Alibbpf-1.0), which probably will take next few weeks. Cutting v0.7 right now seems a bit premature.

As for BCC and bpftrace, those projects are capable (and indeed sort of expect it, given that they are using new libbpf APIs before they are released in "official" version, which IMO is completely understandable) of building and statically linking against libbpf compiled from submodule. Can you build BCC and bpftrace using the version of libbpf that's coming from the submodule?

**Comment by martinetd** [comment]
Thanks for the answer.
If you're actively working on the rest of the 1.0-related API changes then it's probably just as well to wait as you say. If API stays compatible it's probably not that bad either way but it'll definitely be less work to just wait it out.


For bcc/bpftrace, speaking for nixos: while it's easy to build bcc with its submodule, it's not really practical to use the submodule for the bpfbuild after it -- we'd need to have bcc install the libbpf it embeds somewhere for bpftrace to use it in its turn, it's much simpler to just define a new package with the appropriate libbpf version and use it for both. (We cannot just use the bcc build tree in the bpftrace build)
I can understand using the submodule for development cycle but cutting a release with dependencies that have no release is going to be annoying for all fast-paced distros (alpine and fedora also come to mind -- which both also use the packaged libbpf for both tools -- and archlinux which builds bcc with libbpf as submodule but as a package for bpftrace will also run into the incompatibility we ran into trying submodule on nixos)... Not much use bringing that up to you though :)


Anyway, the question would be whether we want to just upgrade the "normal" libbpf package or to add a new one and make just bcc/bpftrace use it -- we'll probably need to do it for 1.0 anyway if you remove the deprecated function wrappers so it might be just as easy to start now.
(We're starting to see more users now (systemd, dpdk, knot..) so upgrading the package for everyone willy-nilly is not going to work much longer)

Will discuss it a bit more on the nixos side, thanks again for taking the time to reply.

**Comment by anakryiko** [comment]
I didn't realize bpftrace doesn't support using libbpf from submodule. Too bad for bpftrace... ;)

But yeah, give me few more weeks for 0.7 release. Will give more time to mark last batch of deprecations and let users test it a bit better (here's to hoping). With that 0.8 hopefully won't introduce any new deprecations (or maybe just the very minor ones). Then we'll have to make decision whether to do 0.9 or just go for 1.0.

**Comment by anakryiko** [comment]
https://github.com/libbpf/libbpf/releases/tag/v0.7.0
