### ISSUE TITLE
why tc(struct bpf_sec_def) cookie in not have SEC_SLOPPY_PFX attribute?

### ISSUE THREAD

**Issue by aguaiyoung** [libbpf/libbpf#441]
Hi,
  Though read https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0#stricter-and-more-uniform-bpf-program-section-name-sec-handling ,i agree with sec have must strict name like tp.
'tc' and 'classifer' adn 'action' is same as SCHED_CLS progm type,but tc has not  SEC_SLOPPY_PFX  attribute,Why? if you ebpf progamr named tc_ingress or tc_egress,it's not illagl. I don't agree with it.
  I really appreciate it/that if you tell me why.

**Comment by anakryiko** [comment]
> if you ebpf progamr named tc_ingress or tc_egress,it's not illagl

It is with SEC("tc") definition.

SEC("tc") was added after the move to strict semantics, so there was never a good reason to allow sloppy behavior. libbpf 1.0 will disable sloppy prefix behavior altogether.

But there is no need to have SEC("tc_ingress") and SEC("tn_egress"), use SEC("tc") for both programs. libbpf supports multiple BPF programs with the same SEC() name.

**Comment by aguaiyoung** [comment]
> But there is no need to have SEC("tc_ingress") and SEC("tn_egress"), use SEC("tc") for both programs. libbpf supports multiple BPF programs with the same SEC() name.

thank anakryiko's replay.
how to get the different fd  bpf programs with the same SEC() name?
To get the different fd, i try to add list and lookup by name. like that:
 bpf_object__for_each_program(prog, obj) {
        fd = bpf_program__fd(prog);
        pg_name = bpf_program__section_name(prog);
        **bpf_prog_add_list(pg_name, fd);**
        bpf_program__attach(prog);
    }

    bpf_map__for_each(map, obj) {
        fd = bpf_map__fd(map);
        pg_name = bpf_map__name(map);
        **bpf_map_add_list(pg_name, fd);**
    }

  '''''
  int bpf_prog_get_fd_by_name(char *name)
{
    int nhash;
    struct bpf_progs_data *prog;

    if (!name || strlen(name) == 0)
       return -1;

    nhash = bpf_name_hashkey(name, strlen(name));
    list_for_each_entry(prog, &prog_list[nhash], nlist) {
       if (!strcmp(prog->name, name) ){
           return prog->fd;
       }
    }

    return -1;
}
  ''''
can you tell me some good method?
thank you!

**Comment by anakryiko** [comment]
bpf_object__find_program_by_name(), or use BPF skeleton (see https://nakryiko.com/posts/libbpf-bootstrap/#the-user-space-side), or you can iterate programs if you want and use bpf_program__name() instead of bpf_program__section_name().

**Comment by aguaiyoung** [comment]
> 

thanks a lot.
verify it with bpf_program__name,it's ok.
bpf_program__name api get function name, 
bpf_program__section_name api get sec name.
