### ISSUE TITLE
adding bpf_map_lookup_and_delete_elem to bpf_helper_defs.h

### ISSUE THREAD

**Issue by guyarb** [libbpf/libbpf#446]
Hey all,

I wanted to use bpf_map_lookup_and_delete_elem method, but it does not appear in bpf_helper_defs.h
how can I add it?

(I have a libbpf+CORE module, and if I'm importing `bpf.h` and `vmllinux.h` it creates redefinition errors between them, so I tried to look for another way to use that method, and I noticed I'm using bpf_map_lookup and bpf_map_delete from `bpf_helpers.h`)
Thanks!

**Comment by anakryiko** [comment]
There is no bpf_map_lookup_and_delete_elem() BPF helper that can be used from BPF program. You'll have to use `bpf_map_lookup_elem()` followed by `bpf_map_delete_elem()`.
