### ISSUE TITLE
test:How to test in my vm?

### ISSUE THREAD

**Issue by swimlessbird** [libbpf/libbpf#453]
In this project, test code run in travis ci.How to test locally？

**Comment by anakryiko** [comment]
All the tests run in CI are coming from kernel's BPF selftests (https://github.com/torvalds/linux/tree/master/tools/testing/selftests/bpf). You can find vmtest.sh script which uses the same image and kernel config to do the same locally. It's not identical to CI environment, but is pretty close.

**Comment by swimlessbird** [comment]
> All the tests run in CI are coming from kernel's BPF selftests (https://github.com/torvalds/linux/tree/master/tools/testing/selftests/bpf). You can find vmtest.sh script which uses the same image and kernel config to do the same locally. It's not identical to CI environment, but is pretty close.

I will try  it,thx.
