### ISSUE TITLE
documentation: Needs documentation

### ISSUE THREAD

**Issue by aviallon** [libbpf/libbpf#460]
Documentation building lacks documentation on how to do it.  
A simple `README` would suffice.

Also, there are no up-to-date documentation archives available.
The most recent one is for 0.4.0, and it looks like it is a stub.

**Comment by anakryiko** [comment]
What do you mean? https://libbpf.readthedocs.io/en/v0.5.0/api.html

**Comment by aviallon** [comment]
> What do you mean? https://libbpf.readthedocs.io/en/v0.5.0/api.html

See here:
https://readthedocs.org/projects/libbpf/downloads/

**Comment by aviallon** [comment]
Moreover, there is no link to `api.html` on the sidebar, making the most useful documentation inaccessible if you do not know the URL.

**Comment by huang195** [comment]
Is there a man page for all these functions? Maybe I'm expecting too much, but the api.html is just a list of function prototypes. For people who want to start using libbpf, how do we figure out how to use these functions?

**Comment by huang195** [comment]
@anakryiko Thanks for the suggestions. I know some of these are already mentioned in README.md, but I wasn't sure if I missed a more comprehensive documentation / tutorial or not. Good that you clarified it.

**Comment by grantseltzer** [comment]
Hi there, i'm very sorry I missed this conversation when you originally tagged me @anakryiko. 

> Moreover, there is no link to `api.html` on the sidebar, making the most useful documentation inaccessible if you do not know the URL.

The complication with the API link not being in the sidebar is that kernel.org hosts all linux documentation. In order for the API docs to be versioned we need to host it via this github repo connected to readthedocs.org. So we link directly to libbpf.readthedocs.org from the kernel documentation.

See what I mean here: https://kernel.org/doc/html/latest/bpf/libbpf/index.html
and here: https://libbpf.readthedocs.io/en/latest/

Perhaps there's a way to put this link in the sidebar manually, I will look into this!

> Also, there are no up-to-date documentation archives available. The most recent one is for 0.4.0, and it looks like it is a stub.

I am looking into why the documentation PDFs and other downloads aren't being built for each version as well.

@huang195 As Andrii says, for now it's mostly just function prototypes, it's mostly just been me adding documentation for the API when I have the opportunity.

**Comment by anakryiko** [comment]
@grantseltzer Worst case we can probably make API link a bit more prominent? It's not easy to understand from "For API documentation see the [versioned API documentation site](https://libbpf.readthedocs.io/en/latest/api.html)." that this is *the most important* piece of documentation :)

**Comment by grantseltzer** [comment]
Handled in https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=e8c5e1a0f78f
