### ISSUE TITLE
BSD-2 license is missing some information

### ISSUE THREAD

**Issue by lmb** [libbpf/libbpf#461]
LICENSE.BSD-2-Clause is missing authors and the years:

https://github.com/libbpf/libbpf/blob/93c570ca4b251415b72ef24e17d7a93ca61a9d42/LICENSE.BSD-2-Clause#L10

A common way to resolve is something like `(c) years The Libbpf Authors`, but it this still requires some digging through git history to figure out what is an appropriate timespan.

**Comment by anakryiko** [comment]
Seems like the first libbpf commit dates back to 2015, we can just do "(c) 2015 The Libbpf Authors"
