### ISSUE TITLE
Issue occured when doing af_xdp on virtio net interface

### ISSUE THREAD

**Issue by beirvin** [libbpf/libbpf#466]
Hi Dear Fellows:
When I do AF_XDP test on virtio net interface, I got an issue as below. So pls give me a hand to figure out this issue.

Exception information:
libbpf: can't get next link: Invalid argument
libbpf: Kernel error message: virtio_net: Too few free TX rings available

Regarding linux sorce code can be found at virtio_net.c@ virtnet_xdp_set() function:
static int virtnet_xdp_set(struct net_device *dev, struct bpf_prog *prog,
struct netlink_ext_ack *extack)
{
... ...
/ XDP requires extra queues for XDP_TX /
if (curr_qp + xdp_qp > vi->max_queue_pairs) {
NL_SET_ERR_MSG_MOD(extack, "Too few free TX rings available");
netdev_warn(dev, "request %i queues but max is %i\n",
curr_qp + xdp_qp, vi->max_queue_pairs);
return -ENOMEM;
}
... ...
}

**Comment by anakryiko** [comment]
https://github.com/libbpf/libbpf#bpflibbpf-usage-and-questions

**Comment by beirvin** [comment]
> https://github.com/libbpf/libbpf#bpflibbpf-usage-and-questions

Okay, I get the reply from your link
