### ISSUE TITLE
proper tag for packaging

### ISSUE THREAD

**Issue by yonghong-song** [libbpf/libbpf#47]
people (@acj) started to build libbpf packages. In the below particular case,
   https://pkgs.alpinelinux.org/packages?name=libbpf&branch=edge
the libbpf package is built for bcc distro purpose on alpine linux.
The related bcc issue is:
   https://github.com/iovisor/bcc/issues/2338

This issue is filed so we can discuss how to tag libbpf for distro:
   - when to tag and what is the tag name

**Comment by anakryiko** [comment]
It seems like we bump kernel's libbpf version roughly with every kernel release cycle, so we can tag commit with the last bpf tree fix before new merge window opens. E.g., merge window just opened and we'll probably going to be bumping the version to 0.0.4, so this might be a good time to sync latest libbpf changes and tag 0.0.3 "release"? 

@yonghong-song, @4ast, @borkmann?

**Comment by yonghong-song** [comment]
bcc will also release roughly along with kernel release cycle. The bcc (and possibly other projects) using libbpf will have their own release numbers. They can maintain an internal map for
their release to the corresponding libbpf release.
So probably is a good idea to tag 0.0.3 release.

**Comment by anakryiko** [comment]
https://github.com/libbpf/libbpf/pull/49 is the last set of fixes that went into 0.0.3, once that is merged, we can tag new "release". Which format for tag naming we should adopt? 

- libbpf-0.0.3
- libbpf-v0.0.3
- v0.0.3

Any preferences?

**Comment by yonghong-song** [comment]
bcc/pahole uses v0.0.3 style. we already know it is libbpf, maybe vx.x.x just fine?

**Comment by anakryiko** [comment]
sounds good to me! And we have a first release, yay! https://github.com/libbpf/libbpf/releases/tag/v0.0.3

**Comment by borkmann** [comment]
Yeah sounds good to me, every time merge window just closed and all the changes including fixes have landed, we can then tag here after backport.

**Comment by acj** [comment]
Thanks, all. I'll change the Alpine package's version to 0.0.3.
