### ISSUE TITLE
Unable to load bpf program that uses BPF_MAP_TYPE_LPM_TRIE

### ISSUE THREAD

**Issue by nsaeris** [libbpf/libbpf#470]
I am using libbpf  v0.7.0

I have a bpf program with following map definition:

struct {
  __uint(type, BPF_MAP_TYPE_LPM_TRIE);
  __type(key, struct bpf_lpm_trie_key);
  __type(value, uint);
  __uint(max_entries, 100);
} route_rule_map SEC(".maps");

Loading the program results in following error:
libbpf: Error in bpf_create_map_xattr(route_rule_map):Invalid argument(-22). Retrying without BTF.
libbpf: map 'route_rule_map': failed to create: Invalid argument(-22)
libbpf: failed to load object 'xdp_root_bpf'
libbpf: failed to load BPF skeleton 'xdp_root_bpf': -22
Failed to load and verify BPF skeleton

Changing the map type to say "BPF_MAP_TYPE_HASH" works. Any idea what could be the cause?

The current code that uses bcc and BPF_MAP_TYPE_LPM_TRIE works. Now I am porting the code to use libbpf + CO-RE, and running into above issue.

**Comment by nsaeris** [comment]
Switching 
from:
struct {
  __uint(type, BPF_MAP_TYPE_LPM_TRIE);
  __uint(key_size, sizeof(struct v4_lpm_key));
  __uint(value_size, sizeof(struct v4_lpm_value));
  __uint(max_entries, 100);
} route_rule_map SEC(".maps");

to:
struct bpf_map_def SEC("maps") route_rule_map = {
  .type = BPF_MAP_TYPE_LPM_TRIE,
  .key_size = sizeof(struct v4_lpm_key),
  .value_size = sizeof(struct v4_lpm_value),
  .max_entries = 100,
};

works with following warning:
libbpf: map 'route_rule_map' (legacy): legacy map definitions are deprecated, use BTF-defined maps instead
libbpf: Use of BPF_ANNOTATE_KV_PAIR is deprecated, use BTF-defined maps in .maps section instead

I have been referring below:
https://facebookmicrosites.github.io/bpf/blog/2020/02/20/bcc-to-libbpf-howto-guide.html
http://patchwork.ozlabs.org/project/netdev/patch/20190611044747.44839-7-andriin@fb.com/

**Comment by nsaeris** [comment]
A followup question:
How to declare map as pinned?

struct bpf_map_def does not have attribute "pinning"

whereas following is supported but does not work for BPF_MAP_TYPE_LPM_TRIE.
struct {
  __uint(type, BPF_MAP_TYPE_HASH);
  __type(key, uint);
  __type(value, uint);
  __uint(max_entries, 10);
  __uint(pinning, LIBBPF_PIN_BY_NAME);
} config_map SEC(".maps");

**Comment by anakryiko** [comment]
Do you have either <linux/bpf.h> or <vmlinux.h> included? I wonder if `struct bpf_lpm_trie_key` isn't fully defined.

Try replacing __type(key, struct bpf_lpm_trie_key) with __uint(key_size, sizeof(struct bpf_lpm_trie_key), and __type(value, ...) with __uint(value_size, sizeof(...)) to see if this makes any difference.

But __type() should work for key and value, so not sure what's going on. Maybe share a little bit more of your BPF code.

**Comment by nsaeris** [comment]
Thank you for your prompt reply. I switched to use my type for key and value. 

Following snippet will answer your questions:

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
#include <bpf/bpf_core_read.h>
#include "xdp_root.bpf.h"



struct v4_lpm_key {
    __u32 prefixlen;
    __be32 addr;
};
struct v4_lpm_value {
    uint instance_pool_id;
};

struct {
  __uint(type, BPF_MAP_TYPE_LPM_TRIE);
  __uint(key_size, sizeof(struct v4_lpm_key));
  __uint(value_size, sizeof(struct v4_lpm_value));
  __uint(max_entries, 100);
  __uint(map_flags, BPF_F_NO_PREALLOC);
} route_rule_map SEC(".maps");

What I realized that if I do not set the map_flags in above definition then I get following error and program fails to load:
libbpf: map 'route_rule_map': failed to create: Invalid argument(-22)
libbpf: failed to load object 'xdp_root_bpf'
libbpf: failed to load BPF skeleton 'xdp_root_bpf': -22
Failed to load and verify BPF skeleton

With the flag, even following definitions works:
struct {
  __uint(type, BPF_MAP_TYPE_LPM_TRIE);
  __type(key, struct v4_lpm_key);
  __type(value, struct v4_lpm_value);
  __uint(max_entries, 100);
  __uint(map_flags, BPF_F_NO_PREALLOC);
} route_rule_map SEC(".maps");

I tried setting the value of map_flags to 0 and it did not work. It seems BPF_F_NO_PREALLOC is mandatory for maps of type BPF_MAP_TYPE_LPM_TRIE.

So my map definitions finally looks like following and it is working.
struct {
  __uint(type, BPF_MAP_TYPE_LPM_TRIE);
  __type(key, struct v4_lpm_key);
  __type(value, struct v4_lpm_value);
  __uint(max_entries, 100);
  __uint(map_flags, BPF_F_NO_PREALLOC);
  __uint(pinning, LIBBPF_PIN_BY_NAME);
} route_rule_map SEC(".maps");

**Comment by anakryiko** [comment]
ok, cool, glad you figured it out
