### ISSUE TITLE
gcc11 /usr/include/bpf/libbpf.h:1222:33: error: field ‘info’ has incomplete type

### ISSUE THREAD

**Issue by muziling** [libbpf/libbpf#472]
env: centos 7 & update gcc version to gcc11
       libbpf version 0.7
       kernel updated to 5.17

write a test.c
```
#include <bpf/libbpf.h>
int main(int argc, char **argv) {
    bpf_program__set_autoload(NULL, false);
    bpf_map__ifindex(NULL);
    bpf_map__set_pin_path(NULL, NULL);
    bpf_object__open_file(NULL, NULL);
    return 0;
}
```
compile with :  gcc test.c -lbpf， and error output:  /usr/include/bpf/libbpf.h:1222:33: error: field ‘info’ has incomplete type

**Comment by chenhengqi** [comment]
I think CentOS 7 is too old for libbpf.

**Comment by anakryiko** [comment]
Your system-wide Linux UAPI headers are way too old. Libbpf comes with its own set of latest UAPI headers in https://github.com/libbpf/libbpf/tree/master/include/uapi/linux. You can use those instead of the ones that come with your system.

**Comment by chenhengqi** [comment]
I managed to build libbpf on CentOS 7 (with kernel 3.10), it works. :)

You can build your program with `gcc -I/path/to/libbpf/include/uapi test.c -lbpf`.
