### ISSUE TITLE
Bug Issue: libbpf cannot successfullly detects whether kernel support FEAT_PROBE_READ_KERN APIs in old kernel versions

### ISSUE THREAD

**Issue by rainkin1993** [libbpf/libbpf#473]
**Background:** Libbpf automatically replaces calls to BPF `bpf_probe_read_{kernel,user}[_str]()` helpers with `bpf_probe_read[_str]()`, if libbpf detects that kernel doesn't support new variants. Specifically, libbpf will invoke `probe_kern_probe_read_kernel` function to load a small eBPF program into the kernel in which `bpf_probe_read_kernel` API is invoked and let the kernel checks whether the new API is valid. If the loading failes, libbpf considers the new API invalid and replace it with the old API.

```
static int probe_kern_probe_read_kernel(void)
{
	struct bpf_insn insns[] = {
		BPF_MOV64_REG(BPF_REG_1, BPF_REG_10),	/* r1 = r10 (fp) */
		BPF_ALU64_IMM(BPF_ADD, BPF_REG_1, -8),	/* r1 += -8 */
		BPF_MOV64_IMM(BPF_REG_2, 8),		/* r2 = 8 */
		BPF_MOV64_IMM(BPF_REG_3, 0),		/* r3 = 0 */
		BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_probe_read_kernel),
		BPF_EXIT_INSN(),
	};
	int fd, insn_cnt = ARRAY_SIZE(insns);

	fd = bpf_prog_load(BPF_PROG_TYPE_KPROBE, NULL, "GPL", insns, insn_cnt, NULL);
	return probe_fd(fd);
}
```

**Bugs**: On older kernel versions, the kernel checks whether the version number provided in the bpf syscall, matches the LINUX_VERSION_CODE. If not matched, the bpf syscall fails. eBPF  However, the `probe_kern_probe_read_kernel` code does not set the kernel version number provided to the `bpf` syscall, which causes the loading process alwasys fails for old versions. **It means that libbpf will replace the new API with the old one even the kernel supports the new one.**

**Solution:** The naive solution is just setting the kernel version field by invoking `get_kernel_version()` and it works well in my environment. Could you check the bug and the solution is right or not. If needed, I can send a PR to fix it.

**Comment by chenhengqi** [comment]
What's your kernel version ?

**Comment by rainkin1993** [comment]
> What's your kernel version ?

4.18 and 4.19. I port the bpf_probe_read_{kernel,user}[_str]() kernel patch back to the old kernel 4.18 and 4.19.

**Comment by rainkin1993** [comment]
> Alternatively we can use BPF_PROG_TYPE_SOCKET_FILTER or BPF_PROG_TYPE_TRACEPOINT program type instead of kprobe. @rainkin1993 can you please check if BPF_PROG_TYPE_TRACEPOINT works for your kernels? I don't remember if tracepoints enforced version check or not. If would be more reliable than using SOCKET_FILTER (some Red Hat backports disable SOCKET_FILTER prog type, but TRACEPOINT still works).

- BPF_PROG_TYPE_TRACEPOINT works for my kernels.
- I checked the source code of bpf syscall and only found `BPF_PROG_TYPE_KPROBE` mathcing the kernel version.
https://elixir.bootlin.com/linux/v4.19/source/kernel/bpf/syscall.c#L1360
    ```
    if (type == BPF_PROG_TYPE_KPROBE &&
            attr->kern_version != LINUX_VERSION_CODE)
	    return -EINVAL;
    ```

Thus BPF_PROG_TYPE_TRACEPOINT is the proper way to go.

> In any case, please submit a proper patch upstream to [bpf@vger.kernel.org](mailto:bpf@vger.kernel.org).

Sure. I will do that.

**Comment by anakryiko** [comment]
great, thanks for checking and confirming!
