### ISSUE TITLE
ring buffer and epoll

### ISSUE THREAD

**Issue by alexburt** [libbpf/libbpf#497]
Hello,
I need to process many ring buffers and other descriptors (sockets) in one thread.
For now I can do it only when I add ring buffer descriptors to epoll outside libbpf and then call ring_buffer__consume for all ring buffers.
This is not efficient because I can not tell  ring_buffer__consume which ring buffers to process. I want to process only ring buffers which is alerted by epoll.

Is it possible to return pointer to ring structure by ring_buffer__new/add and export ringbuf_process_ring which can process only one ring buffer?
in this case I will be able to add ring buffer pointer to my epoll with ring buffer file descriptor and process it.

**Comment by anakryiko** [comment]
I assume you use one struct ring_buffer and add multiple ringbuf map fds to it? Can you just create one struct ring_buffer for each BPF ringbuf map and consume only those you care about? Seems like libbpf provides all the necessary APIs to achieve what you want, unless I'm miunderstanding the problem.

**Comment by alexburt** [comment]
You right.
Thank you very much!
