### ISSUE TITLE
What is the minimum kernel version supported by libbpf

### ISSUE THREAD

**Issue by yhsmer** [libbpf/libbpf#499]
Hiya! I want to know what is the minimum kernel version supported by libbpf, it's not mentioned in the documentation.

**Comment by anakryiko** [comment]
libbpf doesn't have minimum kernel version requirement. Kernel version dependency will be determined by kernel features your BPF code is expecting. Libbpf itself tries to accommodate as many kernel versions as possible.

**Comment by yhsmer** [comment]
> libbpf doesn't have minimum kernel version requirement. Kernel version dependency will be determined by kernel features your BPF code is expecting. Libbpf itself tries to accommodate as many kernel versions as possible.

Thank you very much!
