### ISSUE TITLE
Missing events when tracing 2 tracepoints - NVMe Driver (nvme_setup_cmd and nvme_complete_rq)

### ISSUE THREAD

**Issue by jmazzie** [libbpf/libbpf#500]
I'm in the process of building a tool to trace the latency of transactions on the nvme driver. We started with bpftrace and built a tool that would trace the nvme_setup_cmd tracepoint and nvme_complete_rq tracepoint, but found that we were missing some of the events. This was based on Brendan Gregg's tool, nvmelatency, in his BPF Performance Tools book, though by using tracepoints instead of kprobes. We also saw the issue while using kprobes.

We moved to libbpf in case it was something in bpftrace and rewrote the tool with the same results. In the process of debugging the issue I simplified the tool to just count the number of times we traced nvme_setup_cmd and nvme_complete_rq without doing any other processing on the data. By using a PERCPU_HASH to track nvme_setup_cmd and another to track nvme_complete_rq. We will always miss some of the completion events when tracing both points. If I count just one or the other we get the correct number of events, but need both to do latency calculations.  

The calls are being made around 1 million times a second, which I realize is a lot, but my expectation is that performance would suffer with the tracing enabled but not miss the events.

**Comment by anakryiko** [comment]
https://github.com/libbpf/libbpf#bpflibbpf-usage-and-questions
