### ISSUE TITLE
`class_id` field is missing from `bpf_tc_opts`

### ISSUE THREAD

**Issue by meox** [libbpf/libbpf#506]
Seems that `class_id` field is missing from `bpf_tc_opts` in libbpf v0.8.0.
Is there a way to set it?

**Comment by anakryiko** [comment]
https://github.com/libbpf/libbpf#bpflibbpf-usage-and-questions

**Comment by meox** [comment]
is there a way to set TCA_BPF_CLASSID?
I didn't find it in the doc.
Thanks
