### ISSUE TITLE
Question: Fix bad relo in BPF_KPROBE_SYSCALL?

### ISSUE THREAD

**Issue by jsoo1** [libbpf/libbpf#507]
On kernel 5.4, x86_64:
```
; int BPF_KPROBE_SYSCALL(kprobe__flock, int fd, int cmd) {
0: (bf) r6 = r1
1: (85) call unknown#195896080
invalid func unknown#195896080
```

This is a pretty confusing error, which I know is being improved. What is actually unsupported in the use of the macro? 

If I manually do the same thing as BPF_KPROBE_SYSCALL: 
```
int kprobe__flock(struct pt_regs *ctx) {
  struct pt_regs *regs = PT_REGS_SYSCALL_REGS(ctx);
  int fd = (int)PT_REGS_PARM1(regs);
  int cmd = (int)PT_REGS_PARM2(regs);
```
results in:
```
; int kprobe__flock(struct pt_regs *ctx) {
0: (bf) r6 = r1
1: (b7) r8 = 3
; struct pt_regs *regs = PT_REGS_SYSCALL_REGS(ctx);
2: (79) r1 = *(u64 *)(r6 +112)
; int fd = (int)PT_REGS_PARM1(regs);
3: (79) r7 = *(u64 *)(r1 +112)
R1 invalid mem access 'inv'
```
... wait I see. I  am not exactly replicating `___bpf_syscall_args`.

**Comment by anakryiko** [comment]
"invalid func unknown#195896080" is failed CO-RE relocation (libbpf v0.8 has much better error message, please upgrade)

As to why relocation failed, that's another thing.

**Comment by jsoo1** [comment]
I see. I'll try with 0.8. I read your blog post and understood the error message well enough (thank you for your posts, they are invaluable by the way).

**Comment by jsoo1** [comment]
With 0.8 I still have the same error message. If I wanted to test my functionality without CO-RE, could I access the pt_regs parameter directly?

**Comment by jsoo1** [comment]
Looking at the expanded macro I see this:

```
return ____kprobe__flock(ctx, (void *)({ typeof(((regs))->rdi) __r; ({ bpf_probe_read_kernel((void *)(&__r), sizeof(*(&__r)), (const void *)__builtin_preserve_access_index(&((typeof((((regs)))))((((regs)))))->rdi)); }); __r; }), (void *)({ typeof(((regs))->rsi) __r; ({ bpf_probe_read_kernel((void *)(&__r), sizeof(*(&__r)), (const void *)__builtin_preserve_access_index(&((typeof((((regs)))))((((regs)))))->rsi)); }); __r; }));
```

Is `bpf_probe_read_kernel` available in kernel 5.4? I think that is the cause of the error.

**Comment by jsoo1** [comment]
Maybe this is because the 5.4 variant I have is slightly before BTF support?

**Comment by jsoo1** [comment]
Yes this looks like the kernel I have is slightly before BTF and `bpf_probe_read_kernel`. I worked around this by using this instead of `BPF_KPROBE_SYSCALL`:
```c
int kprobe__flock(struct pt_regs *ctx) {
  struct pt_regs *regs = PT_REGS_SYSCALL_REGS(ctx);
  int fd, cmd;
  __u64 fd_, cmd_;
  bpf_probe_read_kernel(&fd_, sizeof(fd_), &PT_REGS_PARM1(regs));
  bpf_probe_read_kernel(&cmd_, sizeof(cmd_), &PT_REGS_PARM2(regs));
```
I'm not sure but I think this is somewhat portable, too.  Thank you for your help! Closing this.

**Comment by anakryiko** [comment]
it's not because of bpf_probe_read_kernel(), libbpf is smart enough to substitute bpf_probe_read() if bpf_probe_read_kernel() isn't available.

But what you do for kprobe with using PT_REGS_PARM1 explicitly looks correct, feel free to do that.

Do check though whether you need PT_REGS_SYSCALL_REGS, older kernels didn't have that ARCH_HAS_SYSCALL_WRAPPER set, so if your kernel doesn't have that, you shouldn't use  PT_REGS_SYSCALL_REGS(), just read ctx directly (you won't need bpf_probe_read/bpf_probe_read_kernel at all then)

**Comment by jsoo1** [comment]
I see. Thank you very much!
