### ISSUE TITLE
Libbpf-CI is failing.

### ISSUE THREAD

**Issue by Alt-Shivam** [libbpf/libbpf#517]
Libbpf-CI is failing. 
![image](https://user-images.githubusercontent.com/81817735/175210320-87c6f1d8-b528-4bda-ba90-4c818a0fca93.png)

If this issue is valid, I want to work on this.
Thanks.

**Comment by anakryiko** [comment]
The issue is with upstream (in kernel repo) selftests, which was fixed already. We just need to sync libbpf to latest upstream commit. I'll start on it right now. Thanks for offering your help, but this time there isn't much to be done besides the sync.
