### ISSUE TITLE
failed to add legacy kprobe event for vfs_open: No such file or directory

### ISSUE THREAD

**Issue by Ephemeraler** [libbpf/libbpf#524]
QUESTION1: Failed to open BPF Object.
I write a demo about vfs_open using libbpf,  I can run in X86_64 successfully. 
Then I want to run this demo in aarch64, I firstly use bpftool to generate vmlinux.h in aarch64. then I compile it successfully.
But when I run, "Failed to open Object", I find "bpf_object__open_skeleton" have some problem, it return err = -3, strerror it "No such process".
Why dose this problem occur?

**Comment by Ephemeraler** [comment]
I have solved this problem, I change libbpf version from 0.4.0 to 0.8.0. but, I have encountered new problems when I use BPF_KPROBE, ---"incompleted definition of type "struct user_pt_regs" " TAT.

**Comment by Ephemeraler** [comment]
>

**Comment by Ephemeraler** [comment]
QUESTION2："incompleted definition of type "struct user_pt_regs" ", When I write demo, I use vmlinux/aarch/vmlinux.h in libbpf/libbpf(github), but I find it doesn't have struct user_pt_regs, so I use bpftool to generate a vmlinux.h in aarch machine. This problem is solved.

**Comment by Ephemeraler** [comment]
QUESTION3: failed to add legacy kprobe event for 'vfs_open+0x0': No such file or directory
                      prog 'vfs_open': failed to create kprobe 'vfs_open+0x0' perf event: No such file or directory
                      prog 'vfs_open': failed to auto-attach: -2

**Comment by anakryiko** [comment]
please see https://github.com/libbpf/libbpf#bpflibbpf-usage-and-questions
