### ISSUE TITLE
bpf_object_open seems to crash if file path doesn't exists

### ISSUE THREAD

**Issue by meox** [libbpf/libbpf#527]
If we pass a not existent path to the `bpf_object_open`
we got a crash because `bpf_object__elf_init`

**Comment by anakryiko** [comment]
Do you have more details? I couldn't repro it.

**Comment by anakryiko** [comment]
@meox ping?

**Comment by meox** [comment]
I'll try to reproduce it tomorrow with a shareable snippet of code

**Comment by meox** [comment]
```C
#include <stdio.h>

#include <bpf/bpf.h>
#include <bpf/libbpf.h> /* libbpf_num_possible_cpus */


int main() {
  struct bpf_object* obj = bpf_object__open("/tmp/not/exists");
   if(obj == NULL) {
    printf("cannot load!\n");
    return 1;
  }

  printf("loaded!");
}
```

This program doesn't print "cannot load!"

**Comment by chenhengqi** [comment]
For old versions of libbpf, you should use either `libbpf_set_strict_mode(LIBBPF_STRICT_ALL);` or `libbpf_get_error(obj)`.

**Comment by meox** [comment]
> For old versions of libbpf, you should use either `libbpf_set_strict_mode(LIBBPF_STRICT_ALL);` or `libbpf_get_error(obj)`.

I'm using libbpf 0.8.0

**Comment by chenhengqi** [comment]
Add `libbpf_set_strict_mode(LIBBPF_STRICT_ALL);` before `bpf_object__open()`.

**Comment by meox** [comment]
it works!
