### ISSUE TITLE
What happens to a uprobe when the .so file it linked to gets deleted?

### ISSUE THREAD

**Issue by thesw4rm** [libbpf/libbpf#528]
Hi,

Crossposting from libbpf-rs.

I created a uprobe and attached it to libssl within an actively running container (accessed the container's filesystem using the root process' directory in procfs). The uprobe is intercepting function calls as expected and reporting results. When I kill and delete the container, the uprobe will obviously not report any events any more, but I was wondering what happens to it? 

Is there a clean-up process somewhere in the kernel that removes the uprobe's hooks, or does it just become a dangling pointer? If uprobe is a dangling pointer, are we able to clean it up from the userspace loader?

**Comment by anakryiko** [comment]
Asked on the mailing list (https://lore.kernel.org/bpf/OBzRUbPFxraCqyqKJG4wxt16KtWfSZuzR1_huzK30nTPOyc2_oKjBYylXc9fr0CL_oOi0SbH8P67jujAXcI8rMT_wZQwfcAblzuteWLv5fg=@pm.me/), closing issue here, as it's more appropriate to discuss upstream.
