### ISSUE TITLE
Backport bugfix from xdp-project/xdp-tools#205

### ISSUE THREAD

**Issue by alexforster** [libbpf/libbpf#529]
Would y'all accept a PR to backport the bugfix in xdp-project/xdp-tools#205 to a new libbpf branch? I see XDP support was removed in master recently, but for various reasons it's going to be a while before we move to libxdp, so I'd appreciate it if we could cut a `v0.8.1` release with this fix.

**Comment by anakryiko** [comment]
Can you send PR against https://github.com/libbpf/libbpf/tree/v0.8.0 ? I can cut 0.8.1 with that.

**Comment by anakryiko** [comment]
@alexforster created https://github.com/libbpf/libbpf/tree/libbpf-0.8.1

**Comment by anakryiko** [comment]
https://github.com/libbpf/libbpf/releases/tag/v0.8.1

**Comment by alexforster** [comment]
Thanks!
