### ISSUE TITLE
library code won't link?

### ISSUE THREAD

**Issue by yarochewsky** [libbpf/libbpf#53]
#include <stdio.h>
#include <assert.h>
#include <linux/bpf.h>
#include "libbpf.h"
#include <unistd.h>
#include <arpa/inet.h>

int main(int ac, char **argv)
{
    struct bpf_object *obj;
    int map_fd, prog_fd;

    if (bpf_prog_load("test.o", BPF_PROG_TYPE_SOCKET_FILTER,
              &obj, &prog_fd))
        return 1;
}

gcc -Wall -std=c11 -L. -llibbpf test-user.c -o test-user

In file included from test-user.c:5:0:
libbpf.h:125:10: warning: ‘enum bpf_attach_type’ declared inside parameter list
     enum bpf_attach_type *expected_attach_type);
          ^
libbpf.h:125:10: warning: its scope is only this definition or declaration, which is probably not what you want
libbpf.h:127:13: warning: ‘enum bpf_attach_type’ declared inside parameter list
        enum bpf_attach_type *attach_type);
             ^
libbpf.h:247:16: warning: ‘enum bpf_attach_type’ declared inside parameter list
           enum bpf_attach_type type);
                ^
libbpf.h:326:23: error: field ‘expected_attach_type’ has incomplete type
  enum bpf_attach_type expected_attach_type;
                       ^
libbpf.h:444:23: error: field ‘info’ has incomplete type
  struct bpf_prog_info info;

**Comment by anakryiko** [comment]
`enum bpf_attach_type` is defined in <linux/bpf.h>, so please check that that file is up to date and contains that definition.

But also, the proper argument to gcc to link against libbpf would be `-lbpf`, not `-llibbpf`. Please try that, I wasn't able to link successfully without fixing that.

**Comment by yarochewsky** [comment]
That was very helpful. Thanks for the timely response!

**Comment by rchatsiri** [comment]
I'm found an issues after build Suricata source code with eBPF flag. After check ``` enum bpf_attach_type ``` at path ``` /usr/include/linux/bpf.h ```.  Enum type didn't included on ``` linux/bpf.h ```. How to work about on this step.
```
make[2]: Entering directory '/mnt/disks/sdb1/workspacecpp/suricata/src'
  CC       source-af-packet.o
In file included from source-af-packet.c:74:0:
/usr/include/bpf/libbpf.h:419:23: error: field ‘expected_attach_type’ has incomplete type
  enum bpf_attach_type expected_attach_type;
                       ^~~~~~~~~~~~~~~~~~~~
/usr/include/bpf/libbpf.h:585:23: error: field ‘info’ has incomplete type
  struct bpf_prog_info info;
                       ^~~~
In file included from source-af-packet.c:75:0:
/usr/include/bpf/bpf.h:76:23: error: field ‘expected_attach_type’ has incomplete type
  enum bpf_attach_type expected_attach_type;
                       ^~~~~~~~~~~~~~~~~~~~
Makefile:1726: recipe for target 'source-af-packet.o' failed
make[2]: *** [source-af-packet.o] Error 1
make[2]: Leaving directory '/mnt/disks/sdb1/workspacecpp/suricata/src'
Makefile:500: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/mnt/disks/sdb1/workspacecpp/suricata'
Makefile:426: recipe for target 'all' failed
make: *** [all] Error 2
```

Reference back to upstream linux. It has define an enum type name ```expected_attach_type``` at ```linux/bpf.h```

https://github.com/torvalds/linux/blob/ccaaaf6fe5a5e1fffca5cca0f3fc4ec84d7ae752/tools/lib/bpf/bpf.h#L76

How we can create new ```bpf.h``` file at upstream linux at  ``` /usr/include/linux/ ``` support libbpf in Suricata?

**Comment by anakryiko** [comment]
Seems like you system headers are way too old. You either need to upgrade your kernel headers package, or when compiling point it to local copies of up-to-date linux headers in https://github.com/libbpf/libbpf/tree/master/include/uapi/linux
