### ISSUE TITLE
libbpf reuse of pinned RINGBUF map broken

### ISSUE THREAD

**Issue by telbizov** [libbpf/libbpf#531]
Libbpf (tested on version 0.8.0 as well as HEAD built from source) has a bug were reusing an already existing pinned RINGBUF map results in a "parameter mismatch" due to incorrectly comparing the max_entries values of the existing (pinned) map and the one under consideration.

The issue seems to come from the fact that the pinned map already has its max_entries rounded up while the map under consideration doesn't. Details and a simple patch follow.

Map definition:

```
struct {
 __uint(type, BPF_MAP_TYPE_RINGBUF);
 __uint(max_entries, 5000);
 __uint(pinning, LIBBPF_PIN_BY_NAME);
} evring0 SEC(".maps");
```

First load (no map loaded):

```
578: ringbuf name evring0 flags 0x0
 key 0B value 0B max_entries 8192 memlock 24576B
```

Second load with my added debug output:

```
libbpf: Rumen Telbizov Debug: map_info.type (27) == map->def.type (27)
libbpf: Rumen Telbizov Debug: map_info.max_entries (8192) == map->def.max_entries (5000)
libbpf: couldn't reuse pinned map at '/sys/fs/bpf/evring0': parameter mismatch
libbpf: map 'evring0': error reusing pinned map
libbpf: map 'evring0': failed to create: Invalid argument(-22)
```

The issue lies in map_is_reuse_compat() which does the comparison. The following fixes the issue:

```
- map_info.max_entries == map->def.max_entries &&
+ map_info.max_entries == (map_info.type == BPF_MAP_TYPE_RINGBUF ? adjust_ringbuf_sz(map->def.max_entries) : map->def.max_entries) &&
```

Created https://github.com/libbpf/libbpf/pull/530 with a proposed patch. Patch worked for me but feel free to rewrite as you deem appropriate.

**Comment by anakryiko** [comment]
Addressed by https://github.com/libbpf/libbpf/pull/539/commits/7ac1a39bdcccadebb4728ef4a4e7e6b9b3b4f81e

**Comment by telbizov** [comment]
Thank you for fixing and merging this to the upstream kernel @anakryiko
