### ISSUE TITLE
DSO missing from command line Error

### ISSUE THREAD

**Issue by mharbali** [libbpf/libbpf#532]
Respectable authorized:

i am working on xdp. https://github.com/ns1/xdp-workshop

when i run "Make" command on Ubuntu 22.04 ( xdp-workshop/02-stats/solution-2 <== FOLDER NAME )

I am having
`
"/usr/bin/ld: /root/xdp-workshop/common//libbpf/libbpf.a(libbpf.o): undefined reference to symbol 'gzopen64@@ZLIB_1.2.3.3' /usr/bin/ld: /lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line collect2: error: ld returned 1 exit status make: *** [../../common/makerules:39: stats_user] Error 1"
`
error.

I saw error source related with "libbpf"

It is killing me. I am trying to solve this issue for 2 week. I can't sleep, i can't eat, i can't stop thinking reason of this problem. For god sake please for world peace for GOD for everything please help me for solving this issue.

I even rent dedicated server because i tought maybe this error similar like "Its worked on my machine"

Its doesn't work in any device i tryed. (Lenovo Y520-15IKBM / raspberry pi 3 / huawei matebook D16 / dedicated server <== devices i tryed )

**This problem / issue is important for the future of the world.**

I have no idea how can i explain more about how urgent and important this issue. I home someone will be take seriously this issue and solve it.

Best Regards

**Comment by anakryiko** [comment]
make sure you are linking against zlib (pass -lz during compilation) and make sure you have zlib in LD_LIBRARY_PATH?

**Comment by mharbali** [comment]
> make sure you are linking against zlib (pass -lz during compilation) and make sure you have zlib in LD_LIBRARY_PATH?

Hello anakryiko, 

Maybe i am missing some point, if you can write advice solution with details step by step i am sure its will be better for someone else either.

I am pretty sure, someone else will be have similar issue and will search google. So for helping community if you can share with details its will be better for everyone

Best Regards

**Comment by mharbali** [comment]
> make sure you are linking against zlib (pass -lz during compilation) and make sure you have zlib in LD_LIBRARY_PATH?

There is might be problem on make file? Please i really need to solve this issue.

Best Regards
