### ISSUE TITLE
[error] libbpf: failed to find BTF for extern 'bpf_xxxx': -2

### ISSUE THREAD

**Issue by Teanix** [libbpf/libbpf#541]
When I added a bpf helpers func by myself, I want to test the correctness of this function.
But this error is prompted:

```
libbpf: failed to find BTF for extern 'bpf_xxxx': -2
ERROR: opening BPF object file failed
```

So i want to ask, if I want to add bpf helpers func by myself, 
what additional steps do I need to do, currently I The code change path is as follows:
 
1. include/uapi/linux/bpf.h
2. kernel/trace/bpf_trace.c
3. tools/include/uapi/linux/bpf,h 

Or does anyone know of documentation or links to teach developers how to add a bpf helpers func ? thanks so much.

**Comment by anakryiko** [comment]
Check what bpf_helper_defs.h header is doing for existing BPF helpers. You can do the same explicitly for your experimental BPF helper. Or, build libbpf from kernel repo (that's where libbpf sources live, this repo is Github mirror/projection derived from kernel sources). Kernel repo's libbpf generates bpf_helper_defs.h automatically using latest include/uapi/linux/bpf.h.

**Comment by Teanix** [comment]
I temporarily solved this problem by explicitly declaring new func in bpf_helper_defs.h, but what I want to ask is, I have added my new func in `include/uapi/linux/bpf.h`  -  `FN( my_new_func)` like this, but after I compile the kernel, why the relevant declarations are not automatically generated. Are there any other modifications required? thanks a lot for your answer.

**Comment by anakryiko** [comment]
@Teanix are you building libbpf from https://kernel.googlesource.com/pub/scm/linux/kernel/git/bpf/bpf-next/+/refs/heads/master/tools/lib/bpf/ or from this repo? This repo is a projection from authoritative libbpf sources in kernel repo (see https://github.com/libbpf/libbpf#readme).

**Comment by Teanix** [comment]
Thank you very much for your reply, in fact I am building libbpf from this repo, so far I have solved the problem, just need to add the relevant function declaration in  bpf_helper_defs.h
