### ISSUE TITLE
bpf/usdt.bpf.h causes BTF finalization error VAR __bpf_usdt_specs

### ISSUE THREAD

**Issue by fleitz** [libbpf/libbpf#551]
When I include #include <bpf/usdt.bpf.h> libbpf stops being able to open the BPF object.

libbpf: No offset found in symbol table for VAR __bpf_usdt_specs
libbpf: Error finalizing .BTF: -2.
Error: failed to open BPF object file: No such file or directory

**Comment by anakryiko** [comment]
Are you building your BPF application with BTF (e.g., do you pass '-g' to clang when compiling .bpf.o)? If yes, your Clang is probably too old. If not, please add -g.

**Comment by fleitz** [comment]
It’s only when including the usdt.bpf.h header, there’s lots of other code in the object that loads fine.

I know it’s definitely using -g I’ll check the clang version, it’s from Ubuntu 22.04 so it should be new enough.

**Comment by fleitz** [comment]
I compiled bpftool from a newer kernel, now it works and generates a skeleton properly.
