### ISSUE TITLE
xdpoffload to Intel XL710 NIC fails

### ISSUE THREAD

**Issue by wzyyoyo** [libbpf/libbpf#554]
Hello.
My Linux distribution = CentOS 7.
Kernel version = 5.4.210.
NIC Model = Intel XL710 (40G).
clang and llvm version = 9.0.1 (obtained by manually compiling the official source).

I execute the command "sudo ip link set dev enp5s0f1 xdpoffload obj program.o sec mysection".
I want to offload an XDP sample program to the Intel XL710 network card for execution, but I get the following error:
"libbpf: prog 'myprogram': BPF program load failed: Invalid argument" "libbpf: prog 'myprogram': failed to load: -22"
"libbpf: failed to load object 'program.o'"

The sample code comes from the book "Linux Observability with BPF", the hosting website of the sample code, the URL link is: "https://github.com/bpftools/linux-observability-with-bpf".
I have tried to select xdpgeneric mode and xdpdrv mode, both can be executed correctly, only the xdpoffload mode fails, I am a newbie to eBPF, hope to get help, thank you very much.

**Comment by chenhengqi** [comment]
Questions like this should be sent to the BPF mailing list.

(Don't think Intel XL710 NIC supports XDP offload)
