### ISSUE TITLE
system call __NR_perf_event_open fails

### ISSUE THREAD

**Issue by caneatcansleep** [libbpf/libbpf#556]
I download linux-5.19.1 and compile the [samples/bpf](https://github.com/torvalds/linux/tree/master/samples/bpf).  When running tracex1_user.c, I found [`bpf_program__attach`](https://github.com/torvalds/linux/blob/1c23f9e627a7b412978b4e852793c5e3c3efc555/samples/bpf/tracex1_user.c#L34) failed with information "libbpf: kprobe perf_event_open() failed: No such file or directory", I also found ( I build a Clion project to run xx_user.c in samples/bpf so I cound debug the code) `bpf_program_attach` will finally call `perf_event_open_probe` in libbpf.c and `perf_event_open_probe` will do a syscall "__NR_perf_event_open". If the system call fails, it will print failure information "libbpf: kprobe perf_event_open() failed: No such file or directory".
```
static int perf_event_open_probe(bool uprobe, bool retprobe, const char *name,
				 uint64_t offset, int pid, size_t ref_ctr_off)
{
	struct perf_event_attr attr = {};
	char errmsg[STRERR_BUFSIZE];
	int type, pfd, err;

	if (ref_ctr_off >= (1ULL << PERF_UPROBE_REF_CTR_OFFSET_BITS))
		return -EINVAL;

	type = uprobe ? determine_uprobe_perf_type()
		      : determine_kprobe_perf_type();
	if (type < 0) {
		pr_warn("failed to determine %s perf type: %s\n",
			uprobe ? "uprobe" : "kprobe",
			libbpf_strerror_r(type, errmsg, sizeof(errmsg)));
		return type;
	}
	if (retprobe) {
		int bit = uprobe ? determine_uprobe_retprobe_bit()
				 : determine_kprobe_retprobe_bit();

		if (bit < 0) {
			pr_warn("failed to determine %s retprobe bit: %s\n",
				uprobe ? "uprobe" : "kprobe",
				libbpf_strerror_r(bit, errmsg, sizeof(errmsg)));
			return bit;
		}
		attr.config |= 1 << bit;
	}
	attr.size = sizeof(attr);
	attr.type = type;
	attr.config |= (__u64)ref_ctr_off << PERF_UPROBE_REF_CTR_OFFSET_SHIFT;
	attr.config1 = ptr_to_u64(name); /* kprobe_func or uprobe_path */
	attr.config2 = offset;		 /* kprobe_addr or probe_offset */

	/* pid filter is meaningful only for uprobes */
	pfd = syscall(__NR_perf_event_open, &attr,
		      pid < 0 ? -1 : pid /* pid */,
		      pid == -1 ? 0 : -1 /* cpu */,
		      -1 /* group_fd */, PERF_FLAG_FD_CLOEXEC);
	if (pfd < 0) {
		err = -errno;
		pr_warn("%s perf_event_open() failed: %s\n",
			uprobe ? "uprobe" : "kprobe",
			libbpf_strerror_r(err, errmsg, sizeof(errmsg)));
		return err;
	}
	return pfd;
}
```
I have successfully executed two samples in samples/bpf, such as sockex1 and sockex2, they does not use `bpf_program__attach`.

**Comment by caneatcansleep** [comment]
One thing to mention: If I directly run tracex1(see below), it also fails with the same information.
![image](https://user-images.githubusercontent.com/50044253/185900872-2c5d6b3d-ff28-48c5-99df-cc4fe3bcf541.png)

**Comment by chenhengqi** [comment]
What's the result of `cat /proc/kallsyms | grep __netif_receive_skb_core` ?

**Comment by caneatcansleep** [comment]
here is the result:
![image](https://user-images.githubusercontent.com/50044253/185932851-09d673e1-253f-4e85-a440-db18e1a0d78a.png)
does it mean the actual function to attach is `__netif_receive_skb_core.constprop.0` rather than `__netif_receive_skb_core`?

**Comment by chenhengqi** [comment]
Right.

**Comment by caneatcansleep** [comment]
thanks, da lao. I will try it tomorrow. 
I google the keyword "constprop" and find it seems that the change of function's name is due to gcc's optimization. So is this optimization common for kernel functions?  It will be a trouble if for most functions I want to attache gcc will change the function's name. If so, I have to check whether the function's name have been changed. 
And why libbpf does not check if the function's name is consistent with the name in `/proc/kallsyms`  or not? Or it does but I miss it?
