### ISSUE TITLE
How to get corresponding relationships between kprobe and kretprobe.

### ISSUE THREAD

**Issue by Ephemeraler** [libbpf/libbpf#558]
For example, I'm tracing vfs_read in kprobe and kretprobe, but if vfs_read is called multiple times,  the return value of the vfs_read detected by kretprobe corresponds to which kprobe detected.

kprobe vfs_read 1                           kretprobe vfs_read 1
kprobe vfs_read 2                           kretprobe vfs_read 2
kprobe vfs_read 3             ?            kretprobe vfs_read 3
kprobe vfs_read 4                           kretprobe vfs_read 4
kprobe vfs_read 5                           kretprobe vfs_read 5

**Comment by chenhengqi** [comment]
Typically, we use tid (thread id in userspace) as key to store data in BPF maps on kprobe, and retrieve data back on kretprobe.

**Comment by Ephemeraler** [comment]
>
