### ISSUE TITLE
usdt: unrecognized arg #0

### ISSUE THREAD

**Issue by fleitz** [libbpf/libbpf#559]
Trying to get a USDT program to attach, but when it's attached it fails with the error.

```
libbpf: usdt: unrecognized arg #0 spec '8@(%rsp) 8@8(%rsp) 8@16(%rsp) -4@24(%rsp)'
libbpf: prog 'ruby_method_usdt_helper': failed to auto-attach: -22
```
I've tried removing all the arguments, as well as not using the helper and only using pt_regs, but it all fails with the same error.

Trying to attach to this USDT: https://github.com/ruby/ruby/blob/d92f09a5eea009fa28cd046e9d0eb698e3d94c5c/probes.d#L15

```
SEC("usdt//lib/x86_64-linux-gnu/libruby-3.0.so.3.0:ruby:method__entry")
int BPF_USDT(ruby_method_usdt_helper, int clazz, int method, int filename, int fileno){
    return 0;
}

SEC("usdt//lib/x86_64-linux-gnu/libruby-3.0.so.3.0:ruby:method__entry")
int ruby_method_pt_regs(struct pt_regs *ctx) {
    return 0;
}
```

Running on Ubuntu 22.04, libbpf v1.0.0, and Kernel 5.18.10-76051810-generic

**Comment by fleitz** [comment]
If it helps, attaching USDTs to python works fine...
```
SEC("usdt//usr/bin/python3.10:python:function__entry")
int BPF_USDT(python_method, char* filename, char* method, int lineno){
    return 0;
}
```

**Comment by anakryiko** [comment]
It's probably "8@(%rsp)" is not parsed  because libbpf expects "8@0(%rsp)". Will you be able to submit the fix or we should find someone else to work on a fix?

**Comment by fleitz** [comment]
I can work on a fix, especially now that I know what the issue is. If I can fix it I'll submit a patch / PR. 

Question, does the PR go here or should it go into the Linux Kernel? My understanding is libbpf is extracted out of the kernel, correct?

**Comment by fleitz** [comment]
Read the docs, know where to submit the patches :)

**Comment by anakryiko** [comment]
It's probably best to combine this with the first usecase (where offset is explicit), and just make sure that offset is zero if it's this new form. And yes, please send patch to bpf@vger.kernel.org

**Comment by 0xB10C** [comment]
Running into the same problem with `8@(%rsp)`. @fleitz let me know if your still working on this and need help testing. Otherwise I might pick this up.

**Comment by fleitz** [comment]
Our code is here: https://github.com/containiq/libbpf These fixes fixed the parsing issue but it would also sometimes crash the ruby VM so it probably has bugs.
