### ISSUE TITLE
BPF_F_CURRENT_CPU in vmlinux.h [ARM]

### ISSUE THREAD

**Issue by Ephemeraler** [libbpf/libbpf#564]
I use bpftool to generate vmlinux in arm. but it don't exist BPF_F_CURRENT_CPU in vmlinux.h. thank u.

**Comment by Ephemeraler** [comment]
And I found that when I use 0 to replace BPF_F_CURRENT_CPU in bpf_perf_event_output, the function may send fail.

**Comment by anakryiko** [comment]
BPF_F_CURRENT_CPU used to be #define macro on older kernels, so if you generate vmlinux.h from such old kernel you won't get it in vmlinux.h. You need to use either newer kernel, or just #define it yourself:

```
#define BPF_F_CURRENT_CPU 0xffffffffULL
```

This constant is not going to check.
