### ISSUE TITLE
Can't work on CentOS7 with kernel 5.6

### ISSUE THREAD

**Issue by garyhuang123** [libbpf/libbpf#568]
hello, i try this blindssl https://github.com/citronneur/blindssl which employs libbpf, on the 5.6 kernel with BTF enabled, but it comes out to this error, any ideas? @anakryiko @yonghong-song 

[root@localhost bin]# ./blindssl -p /lib64/libssl.so
libbpf: Error in bpf_object__probe_loading():Invalid argument(22). Couldn't load trivial BPF program. Make sure your kernel supports BPF (CONFIG_BPF_SYSCALL=y) and/or that RLIMIT_MEMLOCK is set to big enough value.
libbpf: failed to load object 'blindssl_bpf'
libbpf: failed to load BPF skeleton 'blindssl_bpf': -22
blindssl: Failed to load BPF program: Invalid argument

[root@localhost ~]# prlimit -l
RESOURCE DESCRIPTION SOFT HARD UNITS
MEMLOCK max locked-in-memory address space unlimited unlimited bytes

[root@localhost ~]# grep CONFIG_BPF_SYSCALL /boot/config-5.6.14-100.el7.x86_64
CONFIG_BPF_SYSCALL=y

[root@localhost ~]# uname -a
Linux 5.6.14-100.el7.x86_64 https://github.com/citronneur/blindssl/issues/1 SMP Fri Aug 26 12:59:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by chenhengqi** [comment]
https://github.com/libbpf/libbpf#libbpf-and-general-bpf-usage-questions
