### ISSUE TITLE
why not provide __PT_PARM6_REG

### ISSUE THREAD

**Issue by liyan-ah** [libbpf/libbpf#575]
maybe this is a simple question, but it confused me.
I need to print first 8 arguments for a 11 arguments function. with `bpftrace`,  I can use [arg0 .. arg5] to print first 5, and [sarg0 .. sarg2] to print next 3. but in libbpf, only [__PT_PARM1_REG .. __PT_PARM5_REG] are provided, no  __PT_PARM6_REG.
as I know, first six arguments can be accesed with register in [x86_64](https://wiki.cdot.senecacollege.ca/wiki/X86_64_Register_and_Instruction_Quick_Start). would it be better if we can provide __PT_PARM6_REG to use? or did I missed anything?

here is the solution I used now:
https://github.com/libbpf/libbpf/pull/574

**Comment by vincentmli** [comment]
@liyan-ah  just my  guess, maybe because BPF only have 5 registers r1-r5 for function argument passing? I wonder  how to access 6th argument too

**Comment by liyan-ah** [comment]
@vincentmli not really. on `centos8`, x86_64 platform, I defined a macro to access arg6 in `libbpf`, which can be found in https://github.com/libbpf/libbpf/pull/574.  `BPF` registers would not limit the access, it's os' register that pass function arguments. the register using  method on x86_64 is:
```
Usage during [syscall](https://wiki.cdot.senecacollege.ca/wiki/Syscalls)/function call:

First six arguments are in rdi, rsi, rdx, rcx, r8d, r9d; remaining arguments are on the stack.
For syscalls, the syscall number is in rax. For procedure calls, rax should be set to 0.
Return value is in rax.
The called routine is expected to preserve rsp,rbp, rbx, r12, r13, r14, and r15 but may trample any other registers.
```
refered from [X86_64_Register_and_Instruction_Quick_Start](https://wiki.cdot.senecacollege.ca/wiki/X86_64_Register_and_Instruction_Quick_Start).

**Comment by liyan-ah** [comment]
as we can see, in https://github.com/libbpf/libbpf/blob/master/src/bpf_tracing.h, `libbpf` access arguments with registers. 
```
...
#define __PT_PARM3_REG rdx
#define __PT_PARM4_REG rcx
#define __PT_PARM5_REG r8
...
#define PT_REGS_PARM3(x) (__PT_REGS_CAST(x)->__PT_PARM3_REG)
#define PT_REGS_PARM4(x) (__PT_REGS_CAST(x)->__PT_PARM4_REG)
#define PT_REGS_PARM5(x) (__PT_REGS_CAST(x)->__PT_PARM5_REG)
```
users can access arguments through these macros. 
what confused me is: os provide 6 registers but `libbpf` only use first 5. Is the platform difference limit 6th ?

**Comment by vincentmli** [comment]
ok, I understand the x86 arch support 6 registers for function argument.  there is no 

```
#define __PT_PARM6_REG r9
#define PT_REGS_PARM6(x) (__PT_REGS_CAST(x)->__PT_PARM6_REG)
```
the reason there is no above macro for 6th argument is by my guess maybe BPF only support 5 registers, and it requires 1:1 mapping between x86 function argument register and BPF function register? @chenhengqi , could you please clarify if you know the answer ? :)

**Comment by chenhengqi** [comment]
This is not related to BPF register restriction.

Actually, we retrieve these arguments from `struct pt_regs *ctx` and it is architecture-specific. Not sure whether all architectures supported by LInux has 6 registers for arguments passing.

@liyan-ah  Please send your patch to BPF mailing list.

**Comment by liyan-ah** [comment]
@chenhengqi okay. I would send my patch.

@vincentmli thanks for your attention. I think I got the answer.

issue closed :)

**Comment by vincentmli** [comment]
@liyan-ah @chenhengqi I did more reading, could be totally  irrelevant here as I am still learning and trying to figure out if there is any association  :) https://lore.kernel.org/bpf/20191108064039.2041889-4-ast@kernel.org/ is interesting
```
+ * x86-64 register R9 is not used by BPF programs, but can be used by BPF
+ * trampoline. x86-64 register R10 is used for blinding (if enabled).
  */
```

**Comment by anakryiko** [comment]
there is no technical reason, just no one added 6th arg macro. See https://github.com/libbpf/libbpf-bootstrap/issues/111#issuecomment-1251917107 and yes, please do send a patch.
