### ISSUE TITLE
 kprobe for mmap

### ISSUE THREAD

**Issue by kochia3** [libbpf/libbpf#584]
I'm trying to have krobe for mmap:
```
SEC("kprobe/do_mmap")
int BPF_KPROBE(kprobe_mmap, void *addr, unsigned long len, unsigned long prot, unsigned long flags, unsigned long fd, unsigned long offset)
{
	return 0;
}
```

but it fails to compile, it works if I remove the last parameter and make parameter count to five

my guess it that it's due to calling conversion

how can I get the sixth parameter?

**Comment by anakryiko** [comment]
See https://github.com/libbpf/libbpf-bootstrap/issues/111#issuecomment-1251917107
