### ISSUE TITLE
Replacement for bpf_set_link_xdp_fd

### ISSUE THREAD

**Issue by tjcw** [libbpf/libbpf#587]
I am trying to get xdp-tutorial to work with the 'new' libbpf (at the moment it is coded to the 'old' libbpf), because I am trying to write another test case in the style of the 'new' libbpf.

One of the first build breaks I run into is
```
common_user_bpf_xdp.c: In function ‘xdp_link_attach’:
common_user_bpf_xdp.c:26:8: warning: implicit declaration of function ‘bpf_set_link_xdp_fd’; did you mean ‘bpf_link__fd’? [-Wimplicit-function-declaration]
  err = bpf_set_link_xdp_fd(ifindex, prog_fd, xdp_flags);
        ^~~~~~~~~~~~~~~~~~~
        bpf_link__fd
```
Reading the commentary on commits, I notice that bpf_set_link_xdp_fd was deprecated as being low-level; now it appears to have been completely removed.

What should I replace it with ?

**Comment by tjcw** [comment]
It looks like I'm supposed to remove xdp_link_attach from common_user_bpf_xdp.c and revise its callers so that they use bpf_xdp_attach in libbpf instead. What do I need to set the bpf_xdp_attach_opts to ?

**Comment by tjcw** [comment]
I have a similar problem with load_bpf_object_file in xdp-tutorial, which refers to bpf_prog_load_attr and bpf_prog_load_xattr . These were marked deprecated and have now disappeared, but I cannot see what to replace them with.

**Comment by anakryiko** [comment]
You need `bpf_xdp_attach()`. You can leave opts as `NULL`, if you don't need to specify any opts. As for `bpf_prog_load_xattr()` -- you need to use a proper bpf_object-based API, see `bpf_object__open_file()` and `bpf_object__load()`.

**Comment by tjcw** [comment]
Is there an example of this ? I am getting stuck where I think the xdp or bpf library is expecting me to load a dispatcher program; something is looking for an xdp_metadata section which is not there. Does Ubunto 20.04 (5.4.0-121-generic kernel) support BPF 1.0 ?

**Comment by anakryiko** [comment]
There are a bunch of "examples" (BPF selftests actually) in https://github.com/torvalds/linux/tree/master/tools/testing/selftests/bpf, there are some that show bpf_xdp_attach() and plenty that show bpf_object__open+bpf_object__load. As for Ubuntu -- no idea.

**Comment by tjcw** [comment]
Thanks ! I was missing a call to bpf_program__set_type(bpf_prog,BPF_PROG_TYPE_XDP) , and the required handlng of the fq when calling xsk_ring_prod__reserve, xsk_ring_prod__fill_addr, and xsk_ring_prod__submit is slightly different.
