### ISSUE TITLE
Replicating kfunc_call_test from the kernel tests on standalone bpf program (calling kernel function is not allowed)

### ISSUE THREAD

**Issue by hfingler** [libbpf/libbpf#591]
Hi all,

I'm trying to replicate a bpf test in the kernel that calls a function defined in the kernel itself. Source code is here: https://github.com/torvalds/linux/blob/v5.15/tools/testing/selftests/bpf/progs/kfunc_call_test.c

I think I have all dependencies:
 Running within a qemu VM (Ubuntu 18.04)
 Kernel v 5.15 compiled from scratch with configs from `tools/bpf/bpftool/feature.c`
 pahole v1.22 (1.24 has a reported bug that doesn't allow me to use it)
 libbpf v1.0
 Installed bpf tool from 5.15 kernel directory at `tools/bpf`
 clang and llvm 15

The goal is to call `bpf_kfunc_call_test1`, which is defined in `net/bpf/test_run.c`.
I have two BPF programs and neither work. The first one is as is from the kernel:

```
#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

extern __u64 bpf_kfunc_call_test1(struct sock *sk, __u32 a, __u64 b,
				  __u32 c, __u64 d) __ksym;

SEC("classifier")
int kfunc_call_test1(struct __sk_buff *skb)
{
	struct sock *sk = 0;
  	__u64 a;
  	a = bpf_kfunc_call_test1(sk, 1, 2, 3, 4);
  	bpf_printk("bpf_kfunc_call_test1:  %d.\n", a);
  	return a;
}
```

It is compiled with these commands:

```
bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -I. -idirafter /usr/lib/llvm-15/lib/clang/15.0.2/include -idirafter /usr/local/include -idirafter /usr/include/x86_64-linux-gnu -idirafter /usr/include -c hello.bpf.c -o hello.bpf.o
llvm-strip -g hello.bpf.o
bpftool gen skeleton hello.bpf.o > hello.skel.h
cc -g -Wall hello.skel.h hello.c /usr/lib64/libbpf.a   -lelf -lz -o hello
```

The output is quite large, here is a [gist](https://gist.github.com/hfingler/dc96af45d87004d0dc412e35be31709c).
Mainly:

```
libbpf: extern (func ksym) 'bpf_kfunc_call_test1': resolved to kernel [104983]
libbpf: prog 'kfunc_call_test1': BPF program load failed: Invalid argument
...
kernel function bpf_kfunc_call_test1 args#0 expected pointer to STRUCT sock but R1 is not a pointer to btf_id
processed 6 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
-- END PROG LOAD LOG --
libbpf: prog 'kfunc_call_test1': failed to load: -22
libbpf: failed to load object 'hello_bpf'
libbpf: failed to load BPF skeleton 'hello_bpf': -22
Failed to load and verify BPF skeleton
```

The other program is based off of minimal.c from [libbpf-bootstrap](https://github.com/libbpf/libbpf-bootstrap)

```
#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

extern __u64 bpf_kfunc_call_test1(struct sock *sk, __u32 a, __u64 b,
				  __u32 c, __u64 d) __ksym;

SEC("tp/raw_syscalls/sys_enter")
int handle_tp(void *ctx)
{
	__u64 a;
   	a = bpf_kfunc_call_test1(0, 1, 2, 3, 4);
   	bpf_printk("bpf_kfunc_call_test1:  %d.\n", a);
	return 0;
}
```

The output is a little different, [gist](https://gist.github.com/hfingler/ac69e286f9e527dfd678ef2d768e757c), mainly:

```
libbpf: extern (func ksym) 'bpf_kfunc_call_test1': resolved to kernel [104983]
...
calling kernel function bpf_kfunc_call_test1 is not allowed
libbpf: prog 'handle_tp': failed to load: -13
libbpf: failed to load object 'hello_bpf'
libbpf: failed to load BPF skeleton 'hello_bpf': -13
Failed to load and verify BPF skeleton
```

What is the problem here? I'm mostly interested in the second program, so that I can use it on my own tracepoints and other places.

I'm aware of filtering in `net/core/filter.c`, but I can't find any reference to `bpf_kfunc` functions. In fact, I added this to filter.c, where both functions just return true:
```
const struct bpf_verifier_ops my_verifier_ops = {
	.check_kfunc_call	= export_the_world,
	.is_valid_access	= accept_the_world,
};
```

I'm assuming something is not allowing this program to call it, maybe it's the section it's put in. The kernel test's SEC is `classifier`, which is defined at `tools/lib/bpf/libbpf.c` as  `BPF_PROG_SEC("classifier", BPF_PROG_TYPE_SCHED_CLS),`, while `tp/` is `BPF_PROG_TYPE_TRACEPOINT`.
Is there a filter somewhere that allows one but not the other? For example, in `kernel/bpf/syscall.c` I see:

```
static bool is_net_admin_prog_type(enum bpf_prog_type prog_type)
{
	switch (prog_type) {
	case BPF_PROG_TYPE_SCHED_CLS:
        .. others
```
but `BPF_PROG_TYPE_TRACEPOINT` is not here.

There are so many references to these things that I'm totally lost, that's why I am asking for help.
This example could be added to bootstrap for calling a kernel function, which would help future developers.

 Thanks!

**Comment by anakryiko** [comment]
Please, send email to bpf@vger.kernel.org (see https://github.com/libbpf/libbpf#libbpf-and-general-bpf-usage-questions), this will help others and won't rely on much smaller number of people watching Github issues.

**Comment by chichina** [comment]
> 大家好，
> 
> 我正在尝试在内核中复制一个 bpf 测试，该测试调用在内核本身中定义的函数。源代码在这里：https://github.com/torvalds/linux/blob/v5.15/tools/testing/selftests/bpf/progs/kfunc_call_test.c
> 
> 我想我有所有依赖项： 在 qemu VM (Ubuntu 18.04) 中运行 Kernel v 5.15 从头开始​​编译，配置来自`tools/bpf/bpftool/feature.c` pahole v1.22 (1.24 有一个报告的错误，不允许我使用它) 已安装 libbpf v1.0来自 clang 和 llvm 15的 5.15 内核目录的 bpf 工具`tools/bpf`
> 
> 目标是调用`bpf_kfunc_call_test1`，它在 中定义`net/bpf/test_run.c`。 我有两个 BPF 程序，但都不起作用。第一个来自内核：
> 
> ```
> #include "vmlinux.h"
> #include <bpf/bpf_helpers.h>
> 
> extern __u64 bpf_kfunc_call_test1(struct sock *sk, __u32 a, __u64 b,
> 				  __u32 c, __u64 d) __ksym;
> 
> SEC("classifier")
> int kfunc_call_test1(struct __sk_buff *skb)
> {
> 	struct sock *sk = 0;
>   	__u64 a;
>   	a = bpf_kfunc_call_test1(sk, 1, 2, 3, 4);
>   	bpf_printk("bpf_kfunc_call_test1:  %d.\n", a);
>   	return a;
> }
> ```
> 
> 它是用这些命令编译的：
> 
> ```
> bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
> clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -I. -idirafter /usr/lib/llvm-15/lib/clang/15.0.2/include -idirafter /usr/local/include -idirafter /usr/include/x86_64-linux-gnu -idirafter /usr/include -c hello.bpf.c -o hello.bpf.o
> llvm-strip -g hello.bpf.o
> bpftool gen skeleton hello.bpf.o > hello.skel.h
> cc -g -Wall hello.skel.h hello.c /usr/lib64/libbpf.a   -lelf -lz -o hello
> ```
> 
> 输出相当大，这是一个[要点](https://gist.github.com/hfingler/dc96af45d87004d0dc412e35be31709c)。 主要是：
> 
> ```
> libbpf: extern (func ksym) 'bpf_kfunc_call_test1': resolved to kernel [104983]
> libbpf: prog 'kfunc_call_test1': BPF program load failed: Invalid argument
> ...
> kernel function bpf_kfunc_call_test1 args#0 expected pointer to STRUCT sock but R1 is not a pointer to btf_id
> processed 6 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
> -- END PROG LOAD LOG --
> libbpf: prog 'kfunc_call_test1': failed to load: -22
> libbpf: failed to load object 'hello_bpf'
> libbpf: failed to load BPF skeleton 'hello_bpf': -22
> Failed to load and verify BPF skeleton
> ```
> 
> 另一个程序基于[libbpf-bootstrap的 minimal.c](https://github.com/libbpf/libbpf-bootstrap)
> 
> ```
> #include "vmlinux.h"
> #include <bpf/bpf_helpers.h>
> 
> extern __u64 bpf_kfunc_call_test1(struct sock *sk, __u32 a, __u64 b,
> 				  __u32 c, __u64 d) __ksym;
> 
> SEC("tp/raw_syscalls/sys_enter")
> int handle_tp(void *ctx)
> {
> 	__u64 a;
>    	a = bpf_kfunc_call_test1(0, 1, 2, 3, 4);
>    	bpf_printk("bpf_kfunc_call_test1:  %d.\n", a);
> 	return 0;
> }
> ```
> 
> 输出有点不同，[要点](https://gist.github.com/hfingler/ac69e286f9e527dfd678ef2d768e757c)，主要是：
> 
> ```
> libbpf: extern (func ksym) 'bpf_kfunc_call_test1': resolved to kernel [104983]
> ...
> calling kernel function bpf_kfunc_call_test1 is not allowed
> libbpf: prog 'handle_tp': failed to load: -13
> libbpf: failed to load object 'hello_bpf'
> libbpf: failed to load BPF skeleton 'hello_bpf': -13
> Failed to load and verify BPF skeleton
> ```
> 
> 这里有什么问题？我最感兴趣的是第二个程序，这样我就可以在我自己的跟踪点和其他地方使用它。
> 
> 我知道在 中进行过滤`net/core/filter.c`，但找不到对`bpf_kfunc`函数的任何引用。事实上，我将它添加到 filter.c，其中两个函数都返回 true：
> 
> ```
> const struct bpf_verifier_ops my_verifier_ops = {
> 	.check_kfunc_call	= export_the_world,
> 	.is_valid_access	= accept_the_world,
> };
> ```
> 
> 我假设某些东西不允许该程序调用它，也许是它放入的部分。内核测试的 SEC 是 ，`classifier`它定义为`tools/lib/bpf/libbpf.c`， `BPF_PROG_SEC("classifier", BPF_PROG_TYPE_SCHED_CLS),`而`tp/`is `BPF_PROG_TYPE_TRACEPOINT`。 某处是否有过滤器允许一个但不允许另一个？例如，在`kernel/bpf/syscall.c`我看到：
> 
> ```
> static bool is_net_admin_prog_type(enum bpf_prog_type prog_type)
> {
> 	switch (prog_type) {
> 	case BPF_PROG_TYPE_SCHED_CLS:
>         .. others
> ```
> 
> 但`BPF_PROG_TYPE_TRACEPOINT`不在这里。
> 
> 这些东西太多了，我完全迷路了，这就是我寻求帮助的原因。 此示例可以添加到引导程序以调用内核函数，这将有助于未来的开发人员。
> 
> 谢谢！
请问解决了吗
