### ISSUE TITLE
error when tracing with br_forward function 

### ISSUE THREAD

**Issue by billyxue** [libbpf/libbpf#592]
Hi, When I am tracing br_probe FUNCTION 

 SEC("fentry/br_forward")
 int BPF_PROG(fentry_br_forward,struct net_device *to, struct sk_buff *skb, bool local_rcv, bool local_orig)
 {
     return 0;
 }

when RUN will display errors :   failed to find kernel BTF, 

libbpf: failed to find kernel BTF type ID_ of 'br_forward': -3
libbpf: prog 'fentry_br_forward': failed to prepare load attributes: -3
libbpf: prog 'fentry_br_forward': failed to load: -3
libbpf: failed to load object 'helloworld_bpf'
libbpf: failed to load BPF skeleton 'helloworld_bpf': -3
Failed to load and verify BPF skeleton

my env:
libbpf 1.0

internal-mirror:~/billy/doing/libbpf-bootstrap/libbpf# ls -la /sys/kernel/btf/vmlinux
-r--r--r-- 1 root root 3539989 Sep 25 15:03 /sys/kernel/btf/vmlinux

internal-mirror:~/billy/doing/libbpf-bootstrap/libbpf# clang --version
Debian clang version 11.0.1-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
internal-mirror:~/billy/doing/libbpf-bootstrap/libbpf# uname -a
Linux internal-mirror 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

**Comment by chenhengqi** [comment]
For some reasons, `br_forward` is not presented in kernel BTF. Please try kprobe.

**Comment by billyxue** [comment]
I have tried kprobe but failed , and all the functions in  net/bridge/br_forward.c  will failed

SEC("kprobe/br_forward")
int BPF_KPROBE(entry_br_forward,
const struct net_bridge_port *to,
struct sk_buff *skb, bool local_rcv, bool local_orig)

{
    return 0;
}

will failed when run
libbpf: prog 'entry_br_forward': failed to create kprobe 'br_forward+0x0' perf event: No such file or directory
libbpf: prog 'entry_br_forward': failed to auto-attach: -2
Failed to attach BPF skeleton

Any future plans?

**Comment by anakryiko** [comment]
Do you have CONFIG_BRIDGE set?
```
$ zcat /proc/config.gz | grep -w CONFIG_BRIDGE
CONFIG_BRIDGE=m
```

In my case it was in a module, so unless that module is loaded, you won't be able to attach to br_forward.

**Comment by billyxue** [comment]
> Do you have CONFIG_BRIDGE set?
> 
> ```
> $ zcat /proc/config.gz | grep -w CONFIG_BRIDGE
> CONFIG_BRIDGE=m
> ```
> 
> In my case it was in a module, so unless that module is loaded, you won't be able to attach to br_forward.

OK, after loaded the BRIDGE module, It works
thank you
