### ISSUE TITLE
Do map and prog have access mode like normal files

### ISSUE THREAD

**Issue by caneatcansleep** [libbpf/libbpf#604]
Currently, I know that `bpf_obj_pin` will set the access mode of a map or prog, it has such a call chain:
```
bpf_obj_pin
      bpf_obj_pin_user
           bpf_obj_do_pin
                   vfs_mkobj
                         bpf_mkmap
                                bpf_mkobj_ops
                                       bpf_get_inode(this func will set the i_mode of struct i_node)
```
But I want to know if there is an access mode for a map or prog without pinning map? If so, can I set the access mode to prevent malicious processes or malicious users from deleting my map?

**Comment by anakryiko** [comment]
This question belongs to BPF mailing list, please see https://github.com/libbpf/libbpf#libbpf-and-general-bpf-usage-questions.
