### ISSUE TITLE
libbpf: implement BTF validator

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#617]
Validate BTF for basic sanity before using its contents. This will prevent most of reported fuzz errors and will increase overall robustness.

**Comment by retpolanne** [comment]
Hey @anakryiko, I'm getting back on track with this patch. 

So, what I've been trying to do is to add a function `btf_validate_data` on `bpf_object__init_btf`. I've also added the fix to #484 there. 

Now I need to figure out which BTF validations I should add to the libbpf side. I'm not very familiar with BTF, sorry (checking `kernel/bpf/btf.c` I can see an explanation on the BTF verification), and as you mentioned on my patch [1] I shouldn't be overzealous. 

Also, can I send you patches off list before I send them to the mailing list? Or is it better to send it on the bpf mailing list for feedbacks? 

[1] https://lore.kernel.org/bpf/20220929160558.5034-1-annemacedo@linux.microsoft.com/T/#md5c1ccff88ddfcb0cba844de49fdf750c1c22d79

**Comment by anakryiko** [comment]
hey @retpolanne, I think that maybe implementing validation as BTF API would make sense, as it will allow other use cases to reuse this logic. So maybe add btf__validate() API to libbpf/src/btf.c and then use that from libbpf.c?

Other than that, adding call to btf__validate() from bpf_object__init_btf() makes sense.

Please send patches straight to mailing list.

**Comment by retpolanne** [comment]
@anakryiko that sounds like a great idea! I’m also checking kernel/bpf/btf.c and saw some of the validations there such as iterating through types. That sounds like a plan. 

As I’m working I’ll send it to the mailing list then, thanks!
