### ISSUE TITLE
Mapping relationship between tag and kernel version?

### ISSUE THREAD

**Issue by ZwjAccount** [libbpf/libbpf#629]
would you tell me the aapping relationship between tag in branch master with kernel version?

**Comment by anakryiko** [comment]
If you are asking what kernel commit correspond to Github's version of libbpf, then it's recorded in https://github.com/libbpf/libbpf/blob/master/BPF-CHECKPOINT-COMMIT (for matching bpf tree commit) and https://github.com/libbpf/libbpf/blob/master/CHECKPOINT-COMMIT (for matching bpf-next tree commit). When we sync code from kernel to Github, we merge both bpf and bpf-next trees together.

Does that answer your question?
