### ISSUE TITLE
why libbpf restrict BTF-defined map-in-map BPF_MAP_TYPE_HASH_OF_MAPS key size to 4 bytes?

### ISSUE THREAD

**Issue by andywu106** [libbpf/libbpf#653]
I used BPF_MAP_TYPE_HASH_OF_MAPS type map-in-map, like this:

struct outer_map_key_v4 {
        __be32 daddr; /* Big-endian */
        __be16 dport; /* Big-endian */
};

struct reuseport_map {
        __uint(type, BPF_MAP_TYPE_REUSEPORT_SOCKARRAY);
        __uint(max_entries, 1024);
        __uint(key_size, sizeof(__u32));
        __uint(value_size, sizeof(__u32));
} reuseport_array_inner SEC(".maps");

struct {
        __uint(type, BPF_MAP_TYPE_HASH_OF_MAPS);
        __uint(max_entries, 1024);
        __type(key, struct outer_map_key_v4);
        __type(value, __u32);
        __array(values, struct reuseport_map);
} outer_map_v4 SEC(".maps") = {
        .values = {
                [0] = &reuseport_array_inner,
        },
};

got following error when make:

  GEN-SKEL output/tcp_reuseport.skel.h
libbpf: .maps relo #0: hash-of-maps 'outer_map_v4' should have key size 4.
Error: failed to open BPF object file: Invalid argument

why key size should be 4 bytes?

**Comment by andywu106** [comment]
I found this is restricted by bpf_object__collect_map_relos() in tools/lib/bpf/libbpf.c，
why？is a BUG？

bpf_object__collect_map_relos()
{
  if (is_map_in_map) {
          if (sym->st_shndx != obj->efile.btf_maps_shndx) {
                  pr_warn(".maps relo #%d: '%s' isn't a BTF-defined map\n",
                          i, name);
                  return -LIBBPF_ERRNO__RELOC;
          }

          if (map->def.type == BPF_MAP_TYPE_HASH_OF_MAPS &&
              map->def.key_size != sizeof(int)) {
                  pr_warn(".maps relo #%d: hash-of-maps '%s' should have key size %zu.\n",
                          i, map->name, sizeof(int));
                  return -EINVAL;
          }
          targ_map = bpf_object__find_map_by_name(obj, name);
          if (!targ_map) {
                  pr_warn(".maps relo #%d: '%s' isn't a valid map reference\n",
                          i, name);
                  return -ESRCH;
          }
  } 

}

**Comment by anakryiko** [comment]
this restriction applies only when you are setting inner maps declaratively:

```
struct outer_hash {
        __uint(type, BPF_MAP_TYPE_HASH_OF_MAPS);
        __uint(max_entries, 5);
        __type(key, int);
        __array(values, struct inner_map);
} outer_hash SEC(".maps") = {
        .values = {
                [0] = &inner_map2,
                [4] = &inner_map1,
        },
};
```

If you just do:

```
struct outer_hash {
        __uint(type, BPF_MAP_TYPE_HASH_OF_MAPS);
        __uint(max_entries, 5);
        __type(key, long);
        __array(values, struct inner_map);
} outer_hash SEC(".maps");
```

then it should work fine.

**Comment by andywu106** [comment]
> 
> If you just do:
> 
> ```
> struct outer_hash {
>         __uint(type, BPF_MAP_TYPE_HASH_OF_MAPS);
>         __uint(max_entries, 5);
>         __type(key, long);
>         __array(values, struct inner_map);
> } outer_hash SEC(".maps");
> ```
> 
> then it should work fine.

If not specify inner map, when libbpf auto create the outer map, kernel will return -22, as inner_map_fd is 0 in :
htab_of_map_alloc()->bpf_map_meta_alloc()

struct bpf_map *bpf_map_meta_alloc(int inner_map_ufd)
{
        struct bpf_map *inner_map, *inner_map_meta;
        u32 inner_map_meta_size;
        struct fd f;
        int ret;

        f = fdget(inner_map_ufd);
        inner_map = __bpf_map_get(f);
        if (IS_ERR(inner_map))
                return inner_map; // return -EINVAL (-22) here！！！

}

**Comment by anakryiko** [comment]
Did you try my suggestion above? `__array(values, struct inner_map)` specifies what inner map prototype should be used and libbpf sets inner_map_fd using that "prototype inner map".

**Comment by andywu106** [comment]
> 

This work fine, Thanks！
