### ISSUE TITLE
add uprobe failed cause of "writev" with multiple buffers

### ISSUE THREAD

**Issue by Hackerl** [libbpf/libbpf#656]
libbpf add uprobe on some kernels by writing a string to "/sys/kernel/debug/tracing/uprobe_events".

https://github.com/libbpf/libbpf/blob/c2e797c8def68044b046eaf03ab1fc01948f73bf/src/libbpf.c#L10489-L10496
https://github.com/libbpf/libbpf/blob/c2e797c8def68044b046eaf03ab1fc01948f73bf/src/libbpf.c#L9946-L9964

Write data to fd by calling "vdprintf", in most implementations of the standard library, the data is finally written by the writev syscall.
In case of success, the syscall I catch is as follows:
> writev(74, [{iov_base="p:uprobes/libbpf_2251891__proc_2245757_exe_0xc6cea /proc/2245757/exe:0xc6cea", iov_len=76}, {iov_base=NULL, iov_len=0}], 2) = 76

When I pass a long binary path, data is split into multi-segment:
> writev(67, [{iov_base="p:uprobes/", iov_len=10}, {iov_base="libbpf_2250674__proc_2245757_root_data00_home_xxxxxxxxxxxx_main_1_18_0xdc76a", iov_len=76}], 2) = -1 EINVAL (Invalid argument)

"/sys/kernel/debug/tracing/uprobe_events" does not allow segmented writes, so it fails.
The following code tests multi-segment write under normal conditions:
```cpp
#include <unistd.h>
#include <cstdio>
#include <cerrno>
#include <fcntl.h>
#include <cstdarg>

static int append_to_file(const char *file, const char *fmt, ...) {
    int fd, n, err = 0;
    va_list ap;

    fd = open(file, O_WRONLY | O_APPEND | O_CLOEXEC, 0);

    if (fd < 0)
        return -errno;

    va_start(ap, fmt);
    n = vdprintf(fd, fmt, ap);
    va_end(ap);

    if (n < 0)
        err = -errno;

    close(fd);
    return err;
}

int main() {
    append_to_file(
            "1.txt",
            "%c:%s/%s %s:0x%zx",
            'p',
            "uprobes",
            "libbpf_2338177__proc_2299670_root_data00_home_xxxxxxxxxxx_main_1_18_0xdc76a",
            "/proc/2299670/root/data00/home/xxxxxxxxxxx/main_1.18",
            0xc6cea
    );

    return 0;
}
```
```sh
strace -s 1000 ./demo
execve("./demo", ["./demo"], 0x7fffeed8c270 /* 22 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7fa4c9404118) = 0
set_tid_address(0x7fa4c9404308)         = 7638
open("1.txt", O_WRONLY|O_APPEND|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
writev(3, [{iov_base="p:uprobes/", iov_len=10}, {iov_base="libbpf_2338177__proc_2299670_root_data00_home_xxxxxxxxxxx_main_1_18_0xdc76a", iov_len=75}], 2) = 85
writev(3, [{iov_base=" /proc/2299670/root/data00/home/xxxxxxxxxxx/main_1.18:0xc6cea", iov_len=61}, {iov_base=NULL, iov_len=0}], 2) = 61
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```
> PS: I am using musl libc 1.2.2 - https://musl.cc/

I think it might be better to use write syscall after formatting into string:
```cpp
snprint(buffer, sizeof(buffer), ....);
write(fd, buffer, n);
```

**Comment by anakryiko** [comment]
oh, that's an interesting quirk. I think it should be fine to switch to explicit write() call. Would you be able to prepare and send kernel patch to bpf@vger.kernel.org?

**Comment by Hackerl** [comment]
> Would you be able to prepare and send kernel patch to [bpf@vger.kernel.org](mailto:bpf@vger.kernel.org)?

Ok, I'll try to submit a patch in a few days.

**Comment by Hackerl** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=01dc26c980b0
