### ISSUE TITLE
libbpf: BTF is required, but is missing or corrupted.

### ISSUE THREAD

**Issue by zhouushaooqiann** [libbpf/libbpf#667]
Hi, after updating libbpf from 0.5.0 to 1.1.0, I switched to BTF-defined maps for my XDP program as instructed.
However receiving this error while trying to load the XDP program.

```
libbpf: BTF is required, but is missing or corrupted.
ERROR: opening BPF object file failed
```

Any help is appreciated!

**Comment by anakryiko** [comment]
Make sure you compile your BPF code with recent enough Clang and specify `-g` option, to generate BTF
