### ISSUE TITLE
libbpf code warehouse access control

### ISSUE THREAD

**Issue by lec-bit** [libbpf/libbpf#670]
Is there an independent test case for the libbpf repository on GitHub besides the kernel selftest? How to ensure the quality of the incorporated code?
I mean, does libbpf have a separate access test case here, and how does it do it?

**Comment by anakryiko** [comment]
No, libbpf is developed and tested as part of kernel repository. BPF selftests (https://github.com/torvalds/linux/tree/master/tools/testing/selftests/bpf) are a big set of both unit tests and end-to-end integration tests, validating kernel, libbpf, and compiler behavior. See readme in BPF selftests directory to see how to build and run those selftests.
