### ISSUE TITLE
What does "libbpf: BTF is required, but is missing or corrupted." mean?

### ISSUE THREAD

**Issue by cookiengineer** [libbpf/libbpf#678]
Effectively for the error message `libbpf: BTF is required, but is missing or corrupted.` there's not a single useful result on Google. All mailing list entries are kind of useless without any source codes, so it's a riddle to me what I am doing wrong.

I'm working on an ebpf module, but I cannot load it. I have no idea what I am doing wrong, I'm not a kernel developer and honestly I did not find _any_ XDP program that's working and actually compiling and loading successfully. All examples are either older than 3 months (which imply they're out of date in terms of either libbpf or libxdp), or they are so old that they require a copy of the `bpf-helpers.h` file from years ago; and they aren't compatible with libbpf.

- I am using a new clang and llvm version (`15.0.7`)
- I am using Arch Linux on linux `6.2.10` (tried out several other systems, including Debian/Ubuntu which also is broken AF in terms of eBPF)
- My eBPF module code and generated-by-LLVM bytecodes are located at https://github.com/cookiengineer/ebpf-firewall

The state of how far I got:

I had a program compiled, and loaded, but now I'm getting these useless errors that I have no clue how to debug:

```bash
> sudo bpftool --debug prog load module.bpfel /sys/fs/bpf/whatever type xdp
libbpf: loading module.bpfel
libbpf: elf: section(2) .text, size 712, link 0, flags 6, type=1
libbpf: sec '.text': found program 'parse_dns_question' at insn offset 0 (0 bytes), code size 89 insns (712 bytes)
libbpf: elf: section(3) xdp_prog, size 1520, link 0, flags 6, type=1
libbpf: sec 'xdp_prog': found program 'xdp_prog_main' at insn offset 0 (0 bytes), code size 190 insns (1520 bytes)
libbpf: elf: section(4) .relxdp_prog, size 112, link 7, flags 40, type=9
libbpf: elf: section(5) .maps, size 96, link 0, flags 3, type=1
libbpf: elf: section(6) license, size 4, link 0, flags 3, type=1
libbpf: license of module.bpfel is GPL
libbpf: elf: section(7) .symtab, size 672, link 1, flags 0, type=2
libbpf: BTF is required, but is missing or corrupted.
Error: failed to open object file
```

When I am using another userspace program to load the module (e.g. `cilium/ebpf`'s loader), I am getting the following error which doesn't help me either because I don't know what it means (and neither does anybody on google or stackoverflow, because there are only generic answers to this that don't help at all):

```bash
> sudo go run test.go 
field XdpProgMain: program xdp_prog_main: load program: permission denied: invalid access to packet, off=56 size=2, R8(id=0,off=56,r=55): R8 offset is outside of the packet (45 line(s) omitted)
<nil>
```

I have now the following questions:

- How do I effectively debug an ebpf program that I'm trying to load?
- What is the CLI command to load and debug an xdp program?
- What does R7/R8 mean? How do I find that section? Do I need to disassemble the eBPF bytecode in order to find out what R7/R8 actually was? What about debug symbols?

Thanks for any help, I'm pretty stuck with this for weeks now, and I don't understand how anybody can use eBPF modules when things are _that_ undocumented, outdated and not in-sync everywhere.

**Comment by anakryiko** [comment]
check that your kernel support BPF CO-RE and has BTF (see https://github.com/libbpf/libbpf#bpf-co-re-compile-once--run-everywhere)

you can use https://github.com/libbpf/veristat to load your program and get verifier log

re: r7/r8, you probably need to brush up on basics of BPF itself. See if https://scanfcilium.readthedocs.io/en/latest/bpf.html helper. https://isovalent.com/learning-ebpf/ also does a pretty good job explaining details like this.

**Comment by ivan-tkatchev** [comment]
@cookiengineer To get rid of the frankly user-hostile "BTF is required, but is missing or corrupted" message you need to compile your eBPF source code with debug information.

Pass `-g` to your clang invocation command line.
