### ISSUE TITLE
How to get sample programs that use the latest version of libbpf

### ISSUE THREAD

**Issue by LittleEnough** [libbpf/libbpf#679]
I have a program based on libbpf v0.7, which works well. However, when I updated libbpf to v1.0, numerous errors occurred. 

I suspect that some APIs may have been deprecated or modified. Therefore, I am curious to know where I can find sample programs that are based on the latest version of libbpf. Thanks.

**Comment by mscastanho** [comment]
@LittleEnough Although not exactly a link to sample programs, [this blog post](https://nakryiko.com/posts/libbpf-v1/) has details about what changed in v1.0, which may give you some clue about how to fix the errors you're seeing.

**Comment by anakryiko** [comment]
@LittleEnough see also https://github.com/libbpf/libbpf/wiki/Libbpf-1.0-migration-guide

**Comment by LittleEnough** [comment]
Thanks, this is very helpful to me. I can't wait to recompile my program now!
