### ISSUE TITLE
SEGV in bpf_object__collect_prog_relos() at libbpf.c:4243

### ISSUE THREAD

**Issue by bladchan** [libbpf/libbpf#683]
**Describe the bug**
Bad files which can lead `bpf_object__collect_prog_relos()` to segv issue.

Pocs here:
[poc3.zip](https://github.com/libbpf/libbpf/files/11349519/poc3.zip)

**To Reproduce**
1. Build the whole library with **ASAN**;
2. Driver program (compile it with **ASAN** too):
```c++
// fuzz_driver.cpp
#include "libbpf.h"

static int libbpf_print_fn(enum libbpf_print_level level, const char *format, va_list args)
{
	return 0;
}

int main(int argc, char** argv) {

	struct bpf_object *obj = NULL;
	
	DECLARE_LIBBPF_OPTS(bpf_object_open_opts, opts);
	int err;

	libbpf_set_print(libbpf_print_fn);
	
	opts.object_name = "fuzz-object";
	obj = bpf_object__open_file(argv[1], &opts);
	printf("%s",argv[1]);
	err = libbpf_get_error(obj);
	if (err){
		printf("No");
		return 0;
	}

	bpf_object__close(obj);
	return 0;
}
```
3. Run pocs:
```bash
$ ./fuzz_driver ./poc3
```

**Expected behavior**
The code snippet where the issue happened should avoid segmentation fault because it can lead to DoS.

**Environment (please complete the following information):**
 - System and Version : Ubuntu 20.04.1 + Clang 11.0
 - commit version: fbd60dbff51c870f5e80a17c4f2fd639eb80af90

**Additional context**
ASAN says:
```text
$ ./fuzz_driver poc3
AddressSanitizer:DEADLYSIGNAL
=================================================================
==3672712==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7f6edcd3507c bp 0x7fffcd931850 sp 0x7fffcd930380 T0)
==3672712==The signal is caused by a READ memory access.
==3672712==Hint: address points to the zero page.
    #0 0x7f6edcd3507c in bpf_object__collect_prog_relos /home/ubuntu/test_program/libbpf/src/libbpf.c:4243:52
    #1 0x7f6edcd3507c in bpf_object__collect_relos /home/ubuntu/test_program/libbpf/src/libbpf.c:6672:10
    #2 0x7f6edcd3507c in bpf_object_open /home/ubuntu/test_program/libbpf/src/libbpf.c:7356:16
    #3 0x7f6edcd1620c in bpf_object__open_file /home/ubuntu/test_program/libbpf/src/libbpf.c:7376:20
    #4 0x4c6160 in main /home/ubuntu/test_program/libbpf/fuzz.c:18:8
    #5 0x7f6edc8e0082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #6 0x41c36d in _start (/home/ubuntu/test_program/libbpf/fuzz_driver+0x41c36d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/ubuntu/test_program/libbpf/src/libbpf.c:4243:52 in bpf_object__collect_prog_relos
==3672712==ABORTING
```

**Comment by evverx** [comment]
All these issues have already been found and reported by OSS-Fuzz: https://github.com/libbpf/libbpf/issues?q=is%3Aissue+is%3Aopen+label%3Afuzz-issue.

**Comment by evverx** [comment]
Looking at `fuzz_driver` it seems to be the same as https://github.com/libbpf/libbpf/blob/master/fuzz/bpf-object-fuzzer.c

**Comment by bladchan** [comment]
> All these issues have already been found and reported by OSS-Fuzz: https://github.com/libbpf/libbpf/issues?q=is%3Aissue+is%3Aopen+label%3Afuzz-issue.

@evverx Got it! But without fixing🤷‍♂️. Thank for your quick replay. I'll close this issue.

**Comment by evverx** [comment]
> But without fixing🤷‍♂️.

To be fair some issues were fixed: https://bugs.chromium.org/p/oss-fuzz/issues/list?q=label%3AProj-libbpf%20status%3DVerified&can=1.

https://github.com/libbpf/libbpf/issues/617 should hopefully help to address most of the open issues eventually.
