### ISSUE TITLE
Invalid BTF type name when loading BTF

### ISSUE THREAD

**Issue by tw4452852** [libbpf/libbpf#684]
This is actually a track issue for https://github.com/tw4452852/zbpf/issues/3.

TLDR: `int*` in C will be `*int` in Zig. So two proposals here:

- Fixup BTF type name in libbpf before loading BTF into kernel.
- Relax kernel BTF verifier.

What do you think about it?

**Comment by anakryiko** [comment]
So kernel enforces C rules for identifier. Can you instuct Zig compiler to produce C-compatible names?

**Comment by tw4452852** [comment]
Hi @anakryiko 

Right now I haven't figure out a proper way to fix this on Zig side, so I did a workaround on my vendored version (https://github.com/tw4452852/zbpf/commit/bad505e019b61854a334a11e95275ba50f9fb688). 
Let's close this issue right now.
