### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by ffashion** [libbpf/libbpf#691]
OS: Linux localhost.localdomain 5.4.242-1.el7.elrepo.x86_64 #1 SMP Tue Apr 25 09:46:07 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
clang: clang version 16.0.5 (https://github.com/llvm/llvm-project.git 2eb26b66c63979e583c8d07e09fb5e0061b06768)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/fashion/project/llvm-project/build/install/bin
Found candidate GCC installation: /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11
Selected GCC installation: /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

error: 
  MKDIR    staticobjs
  CC       staticobjs/bpf.o
  CC       staticobjs/btf.o
In file included from btf.c:23:0:
btf.c: In function ‘btf_rewrite_str’:
hashmap.h:126:50: error: the comparison will always evaluate as ‘false’ for the address of ‘mapped_off’ will never be NULL [-Werror=address]
  _Static_assert((__builtin_constant_p((p)) ? (p) == NULL : 0) ||   \
                                                  ^
hashmap.h:170:35: note: in expansion of macro ‘hashmap_cast_ptr’
  hashmap_find((map), (long)(key), hashmap_cast_ptr(value))
                                   ^
btf.c:1581:6: note: in expansion of macro ‘hashmap__find’
      hashmap__find(p->str_off_map, *str_off, &mapped_off)) {
      ^
btf.c: In function ‘btf_dedup_resolve_fwd’:
hashmap.h:126:50: error: the comparison will always evaluate as ‘false’ for the address of ‘cand_id’ will never be NULL [-Werror=address]
  _Static_assert((__builtin_constant_p((p)) ? (p) == NULL : 0) ||   \
                                                  ^
hashmap.h:170:35: note: in expansion of macro ‘hashmap_cast_ptr’
  hashmap_find((map), (long)(key), hashmap_cast_ptr(value))
                                   ^
btf.c:4578:7: note: in expansion of macro ‘hashmap__find’
  if (!hashmap__find(names_map, t->name_off, &cand_id))
       ^
cc1: all warnings being treated as errors

PS: if i remove 
`_Static_assert((__builtin_constant_p((p)) ? (p) == NULL : 0) ||			\
				sizeof(*(p)) == sizeof(long),				\
		       #p " pointee should be a long-sized integer or a pointer");	\  
`
i will compile successfully.

**Comment by anakryiko** [comment]
can you please try compiling with -Wno-address and report back if it helps?

**Comment by alexchowle** [comment]
> -Wno-address

Tried and now working for me

**Comment by ffashion** [comment]
> 

yes. it is useful, mybe my gcc version is low (gcc is 4.x)

**Comment by anakryiko** [comment]
@ffashion Can you try with newer gcc and *without* -Wno-address? Even when explicitly specifying `-Waddress` I can't repro this locally. If this is solved by upgrading compiler, then I'd say we shouldn't do any fix on libbpf side.

**Comment by ffashion** [comment]
> @ffashion Can you try with newer gcc and _without_ -Wno-address? Even when explicitly specifying `-Waddress` I can't repro this locally. If this is solved by upgrading compiler, then I'd say we shouldn't do any fix on libbpf side.

newer gcc without -Wno-address  can compile successfully, and explicitly specifying -Waddress also. So just upgrade compiler can resolve this problem.

**Comment by WXR343** [comment]
> @ffashion Can you try with newer gcc and _without_ -Wno-address? Even when explicitly specifying `-Waddress` I can't repro this locally. If this is solved by upgrading compiler, then I'd say we shouldn't do any fix on libbpf side.

I am unable to fix it by upgrading to gcc, Ubuntu 20.04, kernel: 5.15, gcc version: gcc-5 gcc-7 gcc-9 gcc-11 gcc-13. Help!
Once it was compiled in gcc-9, but only once, and now it cannot be compiled in any way.
