### ISSUE TITLE
Seeking support to resolve "Unsupported BTF_KIND:19" 

### ISSUE THREAD

**Issue by zxy909** [libbpf/libbpf#695]
I am facing an error message stating "`Unsupported BTF_KIND:19`" during my workflow.
  I understand that BTF_KIND refers to different kinds of BTF types within libbpf, and it appears that the version of libbpf I am using does not support BTF_KIND:19. I have made an effort to resolve this issue by exploring various options but haven't been successful so far.
  I look forward to any assistance.

many thanks.

**Comment by anakryiko** [comment]
BTF_KIND 19 is BTF_KIND_ENUM64, you need newer libbpf to be able to parse such BTF. Upstream, we are discussing ways to make parsing BTF a bit less strict, so feel free to follow along at https://lore.kernel.org/bpf/CAEf4BzYG2FFcM_0mkiARzKnYinQYHpWE8ct35Z==-Fsefv9oQw@mail.gmail.com/
