### ISSUE TITLE
1.2.0: install target fails

### ISSUE THREAD

**Issue by kloczek** [libbpf/libbpf#696]
Looks like something is wrong ..
```console
+ cd libbpf-1.2.0
+ /usr/bin/make install DESTDIR=/home/tkloczko/rpmbuild/BUILDROOT/libbpf-1.2.0-2.fc35.x86_64 'INSTALL=/usr/bin/install -p' -C src LIBDIR=/usr/lib64
make: Entering directory '/home/tkloczko/rpmbuild/BUILD/libbpf-1.2.0/src'
  INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h libbpf_version.h usdt.bpf.h
  INSTALL  ./libbpf.pc
  INSTALL
cp: missing destination file operand after '/home/tkloczko/rpmbuild/BUILDROOT/libbpf-1.2.0-2.fc35.x86_64/usr/lib64'
Try 'cp --help' for more information.
make: *** [Makefile:136: install] Error 1
make: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libbpf-1.2.0/src'
```

**Comment by kloczek** [comment]
S`<censored>`t .. my fault 😞 
I have patch which removes build and install static libbpf.a.
Looks like that patch need to be updated for new version. Because it applied without rejections I did not check it that patch could be possible cause .. sorry.

Closing.

BTW: do you have any intention to to move to "civilised" build framework like cmake, meson (IMO the best)? 🤔 
Even full GNU autotools (autoconf/automake/libtool) would be better than sat of than made Makefile files 😛

**Comment by anakryiko** [comment]
> BTW: do you have any intention to to move to "civilised" build framework like cmake, meson (IMO the best)? 

no, I think Makefile does its job just fine, there is nothing too complicated about libbpf's compilation setup.

**Comment by kloczek** [comment]
Meson automatically allows perform cov/asan/usan, with disable/enable static/shared and , PGO/LTO builds.
None of those build (except LTO) variants are correctly supported by current Makefile files.

**Comment by anakryiko** [comment]
All this could be done with Makefile, so let's improve it, if necessary. But I'd like to stick to Makefile approach which we are using in kernel repo as well (which is authoritative source for Github libbpf mirror repo).

**Comment by kloczek** [comment]
Issue is that on for example using meson you don't meed to touch anything in any files to do that.
