### ISSUE TITLE
CO-RE: BPF_FIELD_SIGNED may interpret arbitrary type data as BTF_INT_ENCODING

### ISSUE THREAD

**Issue by lmb** [libbpf/libbpf#704]
Not a big issue, just something I found while comparing cilium/ebpf to what libbpf does. Based on my understanding, libbpf may interpret (mt + 1) as a `u32` to pass it to `BTF_INT_ENCODING` without calling `btf_is_int(mt)`:

https://github.com/libbpf/libbpf/blob/ec6f716eda43fd0f4b865ddcebe0ce8cb56bf445/src/relo_core.c#L779

I've experimented a bit and I think it might not be possible to get clang to even emit such a relocation, so this has limited impact.

**Comment by anakryiko** [comment]
yep, true, needs btf_is_int() check. But why reporting here instead of bpf@vger? Or better yet just send a patch? ;)
