### ISSUE TITLE
Sums listed by Arch don't seem to match this source 1.2.1

### ISSUE THREAD

**Issue by fungilife** [libbpf/libbpf#709]
https://gitlab.archlinux.org/archlinux/packaging/packages/libbpf/-/blob/main/PKGBUILD
ver 1.2.1-1

`sha512sums=('080103800808a16cab99c445add50af2656584776b360d90a8d3abbf44bcde55b64f8ff36a2577a13918375b578ca474740f333c860962fb98957d67f0ae83d9')`

`b2sums=('fa384675be2d24f284d8384d23a395e9106d9f0456a9c34608bcc57b990addc85708b1aa17102044c03a0458949e494865316babc0d7e496d8ce902abf64a072')`

Can someone verify the actual sums of this tar ball?

These are the sums I get after downloading twice

`sha512sum 4d54b52e2f5f1ce9da31f5a72132e309d907f782f53fdca803c64ed063ab0c2be0b837f60150c128e074385e77ba84647f36d1d38a28111188e3f3a1fe949682  libbpf-1.2.1.tar.gz `

`b2sum 477ffd9fa8c4ef7e39f6f149c7c91211b27156f2af7706f9a9ef61bcfdfa2da8c41765035fe334e7e0301077db8eae56bff7a79810a70aaa972f4047f68a76eb  libbpf-1.2.1.tar.gz `

**Comment by anakryiko** [comment]
sorry, it's probably my doing. I published v1.2.1 yesterday, and then another important bug was reported. So I marked v1.2.1 as a non-production release until second bug fix landed upstream and was synced. Then I republished v1.2.1.

I was hoping I managed to mark it as non-production release soon enough to prevent any distros building it, but apparently I was wrong.

Would it be possible for you to rebuild everything based on latest v1.2.1 tag? Or how would you like to proceed here?

**Comment by anakryiko** [comment]
I see that few other distros already built v1.2.1, and probably also before I updated v1.2.1 with latest second bug fix. So I decided to go with yet another v1.2.2 release to avoid any confusion about updated in place v1.2.1 tag.

I'm sorry for confusion, I'll refrain from force-updating release tags in the future no matter how short-lived the tag is.

Please pick up v1.2.2 and skip v1.2.1, if possible. Thanks!

**Comment by fungilife** [comment]
Aaahhh  the beauty and superiority of FOSS!

Thank you for clearing it up
