### ISSUE TITLE
ringbuf_process_ring doesn't handle offset overflow

### ISSUE THREAD

**Issue by ajwerner** [libbpf/libbpf#710]
The producer and consumer offsets are 32-bit unsigned integers. When the producer offset wraps around, and the consumer has not yet processed the message to cause it to wrap around, the message will never be processed. See the logic here:

https://github.com/libbpf/libbpf/blob/05f94ddbb837f5f4b3161e341eed21be307eaa04/src/ringbuf.c#L240

If the producer offset goes from near `UINT_MAX` to near `0`, the consumer will decide there's nothing to do and will not produce another message until the producer offset gets all the way back past the consumer offset (which it very likely never will).

**Comment by kvdevel** [comment]
These offsets are continuously increasing 64 bit offsets. The actual address is taken after and'ing with the size mask as per : https://elixir.bootlin.com/linux/v6.4.3/source/kernel/bpf/ringbuf.c#L442

So, wraparound will be handled gracefully.

**Comment by ajwerner** [comment]
What is the width of `unsigned long` in C? Maybe I'm confused.
