### ISSUE TITLE
 libbpf load time error

### ISSUE THREAD

**Issue by youngjun-89** [libbpf/libbpf#713]
when libbpf load time there is an error like the below
....
[669] DATASEC .maps size=88 vlen=3
         type_id=6 offset=0 size=24
         type_id=33 offset=24 size=32
         type_id=39 offset=56 size=32
[670] DATASEC .kconfig size=4 vlen=1
         type_id=564 offset=0 size=4
[301] STRUCT perf_event size=1200 vlen=72
        waitq type_id=109 bits_offset=6016 Invalid member

-- END BTF LOAD LOG --
libbpf: Error loading .BTF into kernel: -22. BTF is optional, ignoring.

When I remove waitq field, another type of waitqueue_head_t gives an error.
I just use generated plain vmlinux.h.

Is there something I miss on?

**Comment by anakryiko** [comment]
What is the kernel version you are running this on? And can you share the BPF object file you are trying to load (specifically I need .BTF section, but it's easiest to just get ELF file)?
