### ISSUE TITLE
the brief of functions

### ISSUE THREAD

**Issue by Ephemeraler** [libbpf/libbpf#717]
I found that many functions dont have brief, https://libbpf.readthedocs.io/en/v1.2.2/api.html and even sourcecode. Now, Im learning, so I want to get some manual more detailed. Where can I get it? Thank you.

**Comment by anakryiko** [comment]
Yep, a lot of libbpf APIs were not historically well documented. All new APIs are typically landed with doc comments, but we don't have a lot of contributions adding docs for older existing APIs.

If you are just getting started, I suggest to look at simple examples at https://github.com/libbpf/libbpf-bootstrap to get yourself started. Feel free to also take a look at accompanying blog post to make more sense out of the examples: https://nakryiko.com/posts/libbpf-bootstrap/
