### ISSUE TITLE
bpf_probe_read return -14 on ARM

### ISSUE THREAD

**Issue by LittleEnough** [libbpf/libbpf#740]
kernel: 4.18.0-240.15.1.el8_3.aarch64
libbpf version: 0.7.0

I probe sys_execve and want get task cmdline from mm_struct, the code works fine on X86 but returns -14 on ARM.

`#ifdef __arm64__
SEC("kretprobe/__arm64_sys_execve")
#else
SEC("kretprobe/__x64_sys_execve")
#endif
int kretprobe_sys_execve(struct pt_regs *ctx)
{
    ......
    
    unsigned long arg_start = 0;
    unsigned long arg_end = 0;

    struct mm_struct * pmm = READ_KERN(task->mm);
    if(pmm != NULL)
    {
        arg_start = READ_KERN(pmm->arg_start);
        arg_end = READ_KERN(pmm->arg_end);

        if(arg_start != 0 && arg_end != 0 && arg_end > arg_start)
        {
            ncmdlen = arg_end - arg_start > 128 ? 128 : arg_end - arg_start;
            char cmd[128] = {0};
            int ret = bpf_probe_read(cmd, ncmdlen & 127, arg_start);
        }
    }
}`

**Comment by anakryiko** [comment]
Please see https://github.com/libbpf/libbpf#libbpf-and-general-bpf-usage-questions, this is a geberuc question about BPF.
