### ISSUE TITLE
License for include/uapi/linux/bpf.h (1.2.0)

### ISSUE THREAD

**Issue by gvarenni-rvbd** [libbpf/libbpf#741]
The file https://github.com/libbpf/libbpf/blob/v1.2.0/include/uapi/linux/bpf.h seems to have some conflicting license information

> /* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
> /* Copyright (c) 2011-2014 PLUMgrid, http://plumgrid.com
>  *
>  * This program is free software; you can redistribute it and/or
>  * modify it under the terms of version 2 of the GNU General Public
>  * License as published by the Free Software Foundation.
>  */

The first line says that it's GPL-2.0 with linux-syscall-note, but the following lines  are the GPL 2 license, without the syscall note.

Which license applies to this file? 

Thanks.

**Comment by anakryiko** [comment]
That files is a copy of Linux kernel's UAPI header, so if there is any confusion, please ask Linux kernel folks.
