### ISSUE TITLE
CI: find_vma test fails on LATEST kernel

### ISSUE THREAD

**Issue by eddyz87** [libbpf/libbpf#754]
Something is wrong with find_vma test on libbpf CI on LATEST kernel and I can't figure out what.
This test has a loop that waits for a few variables to be set by BPF program `SEC("perf_event") int handle_pe(void)`.
However, these variables are never set, log looks as follows:

```
    serial_test_find_vma:PASS:find_vma__open_and_load 0 nsec
    test_find_vma_pe:PASS:attach_perf_event 0 nsec
    test_and_reset_skel:FAIL:found_vm_exec unexpected found_vm_exec: actual 0 != expected 1
    test_and_reset_skel:FAIL:find_addr_ret unexpected find_addr_ret: actual -1 != expected 0
    test_and_reset_skel:FAIL:find_zero_ret unexpected find_zero_ret:
```

Relevant parts of the `prog_tests/find_vma.c`:

```c
static void test_and_reset_skel(struct find_vma *skel, int expected_find_zero_ret, bool need_test)
{
    if (need_test) {
        ASSERT_EQ(skel->bss->found_vm_exec, 1, "found_vm_exec");
        ASSERT_EQ(skel->data->find_addr_ret, 0, "find_addr_ret");
        ASSERT_EQ(skel->data->find_zero_ret, expected_find_zero_ret, "find_zero_ret");
        ASSERT_OK_PTR(strstr(skel->bss->d_iname, "test_progs"), "find_test_progs");
    }
    ...
}
...
static bool find_vma_pe_condition(struct find_vma *skel)
{
    return skel->bss->found_vm_exec == 0 ||
        skel->data->find_addr_ret != 0 ||
        skel->data->find_zero_ret == -1 ||
        strcmp(skel->bss->d_iname, "test_progs") != 0;
}
...
static void test_find_vma_pe(struct find_vma *skel)
{
    const int one_bn = 1000000000;
    ...
    pfd = open_pe();
    ...
    for (i = 0; i < one_bn && find_vma_pe_condition(skel); ++i)
        ++j;

    test_and_reset_skel(skel, -EBUSY /* in nmi, irq_work is busy */, i == one_bn);
                                                                  // ^^^
                                                                  // this is true on CI
cleanup:
    bpf_link__destroy(link);
    close(pfd);
}
```

Example of the failed job is [here](https://github.com/libbpf/libbpf/actions/runs/6904382140/job/18784917164) (ignore BPF verification log, the log is for sub-tests that are expected to fail).

I tried increasing waiting time up to 1sec ([here](https://github.com/libbpf/libbpf/pull/752/commits/dd9c07b07ee010970367cdff0fd8cdb7f3ad5bfa)) but that did not help. Locally, the test finishes with `i == ~60K`, not even near `1e9`. So, it looks like perf event does not occur for some reason.

Any suggestions are welcome.

**Comment by anakryiko** [comment]
> Any suggestions are welcome.

Let's add it to DENYLIST, all perf_even and send_signal tests were always finicky, the point of libbpf CI is to make sure that libbpf works, not that kernel selftests are 100% reliable.
