### ISSUE TITLE
Compiling C++ BPF programs with existing bpf_helper_defs.h is not possible due to stricter C++ type conversions.

### ISSUE THREAD

**Issue by MarioHewardt** [libbpf/libbpf#759]
Related to - https://lore.kernel.org/bpf/d20f40ba-36af-5060-d4e0-c467d59203ef@meta.com/T/

"
Compiling C++ BPF programs with existing bpf_helper_defs.h is not
possible due to stricter C++ type conversions. C++ complains
about (void *) type conversions:

bpf_helper_defs.h:57:67: error: invalid conversion from ‘void*’ to ‘void* (*)(void*, const void*)’ [-fpermissive]
   57 | static void *(*bpf_map_lookup_elem)(void *map, const void *key) = (void *) 1;
      |                                                                   ^~~~~~~~~~
      |                                                                   |
      |                                                                   void*

Extend bpf_doc.py to use proper function type instead of void.

Before:
static void *(*bpf_map_lookup_elem)(void *map, const void *key) = (void *) 1;

After:
static void *(*bpf_map_lookup_elem)(void *map, const void *key) = (void *(*)(void *map, const void *key)) 1;
"

Does libbpf need to resync with bpf_doc.py?

**Comment by anakryiko** [comment]
bpf_helper_defs.h is included from bpf_helpers.h and is supposed to be included only from BPF-side C code. It's not meant to be compilable as C++
