### ISSUE TITLE
github actions failing due to elfutils-0.176 on ubuntu-20.04

### ISSUE THREAD

**Issue by dubeyabhishek** [libbpf/libbpf#760]
I am getting this error multiple times in github action running on my forked repo:

pahole: Multithreading requires elfutils >= 0.178. Continuing with a single thread

Same issue is not observed in github action on mother branch. If its an package version issue, then it must behave same on both repositories.

Please find the attached image. 

![Screenshot from 2023-12-13 21-58-34](https://github.com/libbpf/libbpf/assets/13221952/b0420d57-2bca-456c-8e65-a151f2eae086)

Link to failed run: https://github.com/dubeyabhishek/libbpf/actions/runs/7196581888/job/19605237936

**Comment by anakryiko** [comment]
> I am getting this error multiple times in github action running on my forked repo:
> 
> pahole: Multithreading requires elfutils >= 0.178. Continuing with a single thread
> 

This is an unrelated warning, it just means BTF deduplication will be a bit slower, but it should have no effect on resulting BTF.

> Same issue is not observed in github action on mother branch. If its an package version issue, then it must behave same on both repositories.
> 

The real problem is that there is no `struct rq->cpu` field, and that could be because of the config change. Not sure, please debug.

**Comment by dubeyabhishek** [comment]
Thanks @anakryiko . CONFIG_SMP=y in bpf/config solved it.
