### ISSUE TITLE
bpf_helper_defs is not aligned with runtime uapi bpf.h

### ISSUE THREAD

**Issue by dzagorui** [libbpf/libbpf#763]
Hello,

I'm trying to write ebpf prog that should work across different LTS kernel versions (5.4, 5.15, 6.1).
Currently i'm using libbpf 0.8. It works with 5.15 and 6.1 kernels, but it fails to load with 5.4 kernel.
Verifier could not find bpf_helper that is used in this ebpf prog (trace_vprintk). Most probably this is
expected but it is not clear with which kernel it is aligned.

I see that here bpf_helper_defs.h is already provided as part of libbpf sources (for me it looks wrong)
In libbpf from kernel source tree this header file is regenerated during the build.
Maybe we should do something similar here (i may prepare a patch if you agree that this is an issue)

**Comment by anakryiko** [comment]
bpf_helper_defs.h is generated as of the latest upstream kernel version at the time of corresponding libbpf release. Old helpers are never removed, so it's backwards compatible with old kernels as long as you are not using new helpers that were added later. trace_vprintk problem is probably due to using `bpf_printk()` macro, provided by libbpf, which uses bpf_trace_vprintk() *if you are passing more than 3 arguments to format*. So if you want better backwards compatibility, please stick to using at most `bpf_printk("fmt string", arg1, arg2, arg3);`

**Comment by dzagorui** [comment]
Thank you,
It is clear, the logic with helpers is similar to syscalls
I have another issue related to userspace API from libbpf. When i tried to use bpf_map_create() API from libbpf 0.8 on the system with 5.15 kernel, it failed.
strace shows that bpf syscalls return an error, but i have not looked deeper
...
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_HASH, key_size=4, value_size=350, max_entries=0, map_flags=0, inner_map_fd=0, map_name="internal_path_m", map_ifindex=0, btf_fd=0, btf_key_type_id=0, btf_value_type_id=0, btf_vmlinux_value_type_id=0, map_extra=0}, 72) = -1 EINVAL (Invalid argument) 
...

Maybe bpf syscall was extended and old kernel does not understand some new flag/option. I see that older libbpf (that corresponds to 5.15 kernel) doesn't have this API, but it has similar bpf_create_map_name(). Does the same logic is applied for userspace API (old libbpf should work with new kernel)?

**Comment by anakryiko** [comment]
not sure why you get EINVAL, it might be because of map_name, but libbpf should have detected whether that is supported or not. Can you try updating libbpf to something more modern (v1+) and see if the problem persists?

**Comment by dzagorui** [comment]
sure, i will try v1.3

**Comment by dzagorui** [comment]
Hi, mentioned issue is in my code it passes max_entries=0 to bpf(BPF_MAP_CREATE).
I have last question related to v5.4 kernel. It doesn't have BPF_LINK_CREATE option. Is it possible to pin ebpf prog so it will be triggered on an event after process exit (as in more recent kernels where it is enough to pin link)?
I can pin ebpf prog bpf(BPF_OBJ_PIN) and it is in memory after process exit but it is not triggered any longer. I can assume that  this happen because corresponding perf_event was removed (its refcount was decremented) on process exit. Is it possible to pin perf_event?

Also i noticed that bpf_link__pin() tries to pin perf_event  and bpf(BPF_OBJ_PIN) fails. Is it expected?
Related code
https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L10598
bpf_program__attach_kprobe() inits link with perf_event fd for kernels where BPF_MAP_CREATE is not present.

**Comment by anakryiko** [comment]
>  Is it possible to pin perf_event?

I don't think so. But libbpf provides PROBE_ATTACH_MODE_LEGACY legacy mode for kprobe/uprobe programs (not any perf_event, though), so you might want to try that. In legacy mode attached BPF program will stay attached to kprobe/uprobe until explicitly detached.

**Comment by dzagorui** [comment]
Thanks
