### ISSUE TITLE
Segfault in libbpf.c on line 2909

### ISSUE THREAD

**Issue by victorstewart** [libbpf/libbpf#766]
Kernel 6.6.10
libbpf 1.3.0 and master

trying to load this XDP program in a testbed...
`xdp_obj = bpf_object__open_file("build/aes.router.ebpf.o", NULL);`

in 1.3.0 i'm segfaulting on this line because `seg->sec_idxs` is `NULL`
https://github.com/libbpf/libbpf/blob/f81eef23b33c0dbf923e863a72ce51ea4d32e291/src/libbpf.c#L2909

and just pulled and built the master branch and still the same segfault is occurring.

and not a problem with the program because it loads fine with the ip utility

```
ip link set dev lo xdpgeneric obj aes.router.ebpf.o sec xdp
ip link show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 xdpgeneric qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    prog/xdp id 25 name aes_router tag c7b62fe68dab6f3d jited 
```

i can do some more digging tomorrow.

**Comment by victorstewart** [comment]
also fails on 1.2.2

the segfault triggers here, on index 0, because sec_idxs is null. and it's null for all of them.

```
bpf_object__init_btf -> (A) ext_segs[0]->sec_idxs = (nil)
bpf_object__init_btf -> (A) ext_segs[1]->sec_idxs = (nil)
bpf_object__init_btf -> (A) ext_segs[2]->sec_idxs = (nil)
```
same error even triggers for the below test program. 

possibly something to do with a compiler update. i'm using clang version 17.0.5

```
#include <linux/in.h>
#include <linux/ipv6.h>
#include <linux/udp.h>
#include <linux/bpf.h>
#include <linux/types.h>
#include <linux/if_ether.h>

#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>


SEC("xdp")
int xdp_test(struct xdp_md *ctx) 
{
   return XDP_DROP;
}
```

**Comment by victorstewart** [comment]
downloaded the latest version of elfutils-0.190 and linked with that, still the same segfault

**Comment by anakryiko** [comment]
@victorstewart can you please share resulting BPF object file you are using? This will make it easier to reproduce.

cc @eddyz87

**Comment by victorstewart** [comment]
here's a link to the object file for `xdp_test`

https://www.dropbox.com/scl/fi/hqfimjtdnweyzmc6d1f07/xdptest.ebpf.o

**Comment by victorstewart** [comment]
@eddyz87 forgot to make the link public, but i allowed your access yesterday

**Comment by eddyz87** [comment]
> @eddyz87 forgot to make the link public, but i allowed your access yesterday

Yes, I can download it, thank you.
Will take a look later this week.

**Comment by anakryiko** [comment]
I can't, requested access.

**Comment by anakryiko** [comment]
Unfortunately I can't reproduce it. I also don't see how source code line you pointed to can cause any crash. `seg->sec_idxs` is supposed to be NULL before calloc() call, and calloc() is called with non-zero sec_cnt (we guard for zero earlier), so I'm not sure what's going on.

If you can still reproduce on latest master version, maybe you can help debug this?

**Comment by victorstewart** [comment]
<img width="771" alt="image" src="https://github.com/libbpf/libbpf/assets/17534897/cc8b5765-cc3b-4436-ad7a-20b5aa5e12bb">

@anakryiko 

```
bpf_object__init_btf -> check point 2.3
bpf_object__init_btf -> check point 2.4
bpf_object__init_btf -> check point 2.5
bpf_object__init_btf -> (A) ext_segs[0]->sec_idxs = (nil)
bpf_object__init_btf -> (A) ext_segs[1]->sec_idxs = (nil)
bpf_object__init_btf -> (A) ext_segs[2]->sec_idxs = (nil)
bpf_object__init_btf -> check point 2.6
bpf_object__init_btf -> check point 2.6.1
bpf_object__init_btf -> seg_num = 0
bpf_object__init_btf -> check point 2.6.2
bpf_object__init_btf -> seg = 0x4b9f8390078
bpf_object__init_btf -> seg->sec_cnt = 1
bpf_object__init_btf -> (A) seg->sec_idxs = (nil)
Guardian::signalHandler(11)
```

yes the master hasn't changed since i last did this. still crashes for me. here's the source code embellishment and corresponding log output i was using when i tracked this down.

just let me know how you want me to debug it further.

but the problem is that these three are all null...

```
ext_segs[0] = &obj->btf_ext->func_info;
ext_segs[1] = &obj->btf_ext->line_info;
ext_segs[2] = &obj->btf_ext->core_relo_info; 
```
... thus this `ext_segs[0]->sec_idxs `segfaults when dereferenced on the first iteration into the loop.

**Comment by victorstewart** [comment]
and i'm statically linking to libbpf.a, in case you're dynamically linking

**Comment by anakryiko** [comment]
if you are saying that `sizeof(*seg->sec_idxs)` is dereferncing `seg->sec_idxs`, that's not true. That sizeof() is compile-time calculated. seg->sec_idx is expected to be NULL, so I still see nothing wrong with the code and it's absolutely unclear why you'd get SIGSEGV. But you can try replacing entire sizeof() with just 4 and see if that makes any difference?

BTW, what are compilation flags you are using and which compiler? Is it with -O2 or not? Etc?

**Comment by victorstewart** [comment]
@anakryiko haha wow yes that was one of the dumbest things i've ever said. i first looked at this late at night 2 weeks ago and saw the deference and was like oh there's the bug. and then never checked the thinking after.

okay so i've solved it. sorry for the false alarm and wasting everyone's time. turns out the segfault was in the custom memory allocator i use.
