### ISSUE TITLE
Add elf convention into documention

### ISSUE THREAD

**Issue by kawhicurry** [libbpf/libbpf#767]
See comments:
https://github.com/libbpf/libbpf/blob/f81eef23b33c0dbf923e863a72ce51ea4d32e291/src/libbpf.c#L780-L783

And this patch:
https://lore.kernel.org/bpf/20220419002452.632125-1-andrii@kernel.org/

I got confused with such usage in selftests in kernel code but failed to find any docs. Hours later, I wanted to find a helper that prevent all ebpf programs from being set `autoload` but failed. So I dived into the code of libbpf and found docs above.

So, is this a real convention now? If it is, we are supposed to add it into documentation:
https://github.com/libbpf/libbpf/blob/master/docs/program_types.rst

**Comment by anakryiko** [comment]
Yes, it would be great to add a sentence in that document to mention SEC("?...") convention. Would you like to contribute upstream patch for this? The source of truth for this documentation lives in `Documentation/bpf/libbpf/program_types.rst` in kernel repository

**Comment by kawhicurry** [comment]
Sure, it'll be my first patch for linux kernel :)
