### ISSUE TITLE
Create map failed

### ISSUE THREAD

**Issue by chentao-kernel** [libbpf/libbpf#770]
Hi，guys
Recently, I met a problem, i wrote a ebpf tool with bcc/libbpf-tools, and refer to the implementation of other tools, the
problem is create map failed in my code.
![image](https://github.com/libbpf/libbpf/assets/86768822/23c767ed-abff-44ed-a395-eed208c2fb3d)

souce code like:
![image](https://github.com/libbpf/libbpf/assets/86768822/af200b4a-3c0a-4137-90af-dbf889e7817d)

I add some debug info in libbpf, it seems that the map max_entries is 0
![image](https://github.com/libbpf/libbpf/assets/86768822/8fb441c5-dcee-4c5c-a0ac-6af2c57c7b4e)

![image](https://github.com/libbpf/libbpf/assets/86768822/de542050-bb65-4d88-914d-ebb96764813f)

What confuses me is that the stackmap with same implemented is no problem in offcputime tool or wakeuptime tool, 
until i set the max_entriyes, the problem solved. like:
![image](https://github.com/libbpf/libbpf/assets/86768822/1d38eaf3-fa9b-4783-ac13-64e269194e65)

My develop enviroment:
ubuntu 22.04, clang 14
My source code:
https://github.com/iovisor/bcc/compare/master...chentao-kernel:bcc:tao/master
Can anyone do me a favour, thanks a lot

**Comment by anakryiko** [comment]
wakeuptime tool sets it dynamically in user-space: https://github.com/iovisor/bcc/blob/master/libbpf-tools/wakeuptime.c#L239

**Comment by chentao-kernel** [comment]
Thanks a lot
