### ISSUE TITLE
cast discards 'const' qualifier warning in skeleton generated code

### ISSUE THREAD

**Issue by shemminger** [libbpf/libbpf#772]
Building a function with skeleton has warning about discarded const qualifier.

In file included from ../drivers/net/tap/tap_flow.c:23:
../drivers/net/tap/tap_bpf.skel.h: In function ‘tap_bpf__create_skeleton’:
../drivers/net/tap/tap_bpf.skel.h:168:19: warning: cast discards ‘const’ qualifier from pointer target type [-Wcast-qual]
  168 |         s->data = (void *)tap_bpf__elf_bytes(&s->data_sz);

Since this is autogenerated code the problem is in bpftool.

Should be obvious, but can reduce this to a toy/test example if necessary.

**Comment by anakryiko** [comment]
This has already been fixed a few months back (https://lore.kernel.org/bpf/20230907090210.968612-1-dzagorui@cisco.com/), so this should go away with updating bpftool.
