### ISSUE TITLE
Comments mismatch for `bpf_program__set_attach_target`

### ISSUE THREAD

**Issue by kawhicurry** [libbpf/libbpf#774]
See:
https://github.com/libbpf/libbpf/blob/3b0973892891744d20ae79e99c0d1a26a59c4222/src/libbpf.h#L900C1-L913C41
```c
/**
 * @brief **bpf_program__set_attach_target()** sets BTF-based attach target
 * for supported BPF program types:
 *   - BTF-aware raw tracepoints (tp_btf);
 *   - fentry/fexit/fmod_ret;
 *   - lsm;
 *   - freplace.
 * @param prog BPF program to set the attach type for
 * @param type attach type to set the BPF map to have
 * @return error code; or 0 if no error occurred.
 */
LIBBPF_API int
bpf_program__set_attach_target(struct bpf_program *prog, int attach_prog_fd,
			       const char *attach_func_name);
```

The `@param` in comments mismatch the real one.

Looks like those comments are copied from `bpf_program__set_expected_attach_type`:
https://github.com/libbpf/libbpf/blob/3b0973892891744d20ae79e99c0d1a26a59c4222/src/libbpf.h#L872C1-L886C38
```c
/**
 * @brief **bpf_program__set_expected_attach_type()** sets the
 * attach type of the passed BPF program. This is used for
 * auto-detection of attachment when programs are loaded.
 * @param prog BPF program to set the attach type for
 * @param type attach type to set the BPF map to have
 * @return error code; or 0 if no error. An error occurs
 * if the object is already loaded.
 *
 * This must be called before the BPF object is loaded,
 * otherwise it has no effect and an error is returned.
 */
LIBBPF_API int
bpf_program__set_expected_attach_type(struct bpf_program *prog,
				      enum bpf_attach_type type);
```

There's a lot of discussion about `bpf_program__set_attach_target`. But I'm still confused about how those parameters works. I try to write a new piece of new comments:

```c
/**
 * @brief **bpf_program__set_attach_target()** sets BTF-based attach target
 * for supported BPF program types:
 *   - BTF-aware raw tracepoints (tp_btf);
 *   - fentry/fexit/fmod_ret;
 *   - lsm;
 *   - freplace.
 * @param prog BPF program to set the attach target for
 * @param attach_prog_fd deprecated now, set to 0
 * @param attach_func_name the name of function you want to attach for
 * @return error code; or 0 if no error occurred.
 */
LIBBPF_API int
bpf_program__set_attach_target(struct bpf_program *prog, int attach_prog_fd,
			       const char *attach_func_name);
 ```
Any advice about that?

**Comment by anakryiko** [comment]
Please see https://github.com/libbpf/libbpf?tab=readme-ov-file#libbpf-and-general-bpf-usage-questions, this is best addressed on BPF mailing list directly, so we don't split discussions. You are right that parameter descriptions are out of sync and we need to fix that. Please send another upstream patch for this.

But attach_prog_fd is not deprecated, please see BPF selftests in kernel repository for its uses.

See also https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/tree/Documentation/bpf/bpf_devel_QA.rst and there are generic "how to submit kernel patch" FAQs that should be easy to find online. Thanks!
