### ISSUE TITLE
bpf_program__attach interface extension

### ISSUE THREAD

**Issue by chentao-kernel** [libbpf/libbpf#780]
I see bpf_program__attach not according to the specified name(prog name/sec name) to attach specifed target, so
can we add a interface like bpf_program__attach_by_name?
Problem solved scenario like：
1.*.isra.0 func problem
may be we can define two section meantime, and attach the specifed sec in the specifed kernel
kernel:
```
SEC("kprobe/finish_task")
int do_finish_task() {}

SEC("kprobe/finish_task.isra.0")
int do finish_task_isra(){}
```
user:
```
bpf_program__attach_by_name(,"do_finish_task")
or
bpf_program__attach_by_name(,"do_finish_task_isra")
```

If this seems to make sense， i can submit a patch to upstream.
Thanks a lot!

**Comment by anakryiko** [comment]
For kprobe programs, there is already `bpf_program__attach_kprobe()` and `bpf_program__attach_kprobe_opts()`. Similarly for other types of programs there is normally an API that allows to specify attachment target more dynamically.

One big difference is fentry/fexit/fmod_ret programs. For them, attachment target has to be specified before BPF program is *loaded* (as opposed to *attached*), so for them there is `bpf_program__set_attach_target()` which has to be called before BPF object/skeleton is loaded.

**Comment by chentao-kernel** [comment]
> For kprobe programs, there is already `bpf_program__attach_kprobe()` and `bpf_program__attach_kprobe_opts()`. Similarly for other types of programs there is normally an API that allows to specify attachment target more dynamically.
> 
> One big difference is fentry/fexit/fmod_ret programs. For them, attachment target has to be specified before BPF program is _loaded_ (as opposed to _attached_), so for them there is `bpf_program__set_attach_target()` which has to be called before BPF object/skeleton is loaded.

Thank you for your reply, got it ! You can close this issue.
