### ISSUE TITLE
when use bpf hook  tracepoint/sched/sched_switch  ， the cpu is hang

### ISSUE THREAD

**Issue by lichm1007** [libbpf/libbpf#783]
0xffffffc0376438c8:('ktime_get_mono_fast_ns', 92)
0xffffffc0376438d8:('htab_percpu_map_lookup_elem$cc60407cff2dc048b7fcd61e22c98b5a', 40)
0xffffffc0376438e8:('lock_acquire', 164)
0xffffffc037643938:('lock_release', 92)
0xffffffc037643948:('lock_release', 80)
0xffffffc037643978:('htab_map_update_elem$cc60407cff2dc048b7fcd61e22c98b5a', 532)
0xffffffc037643988:('_raw_spin_unlock_irqrestore', 44)
0xffffffc037643998:('_raw_spin_unlock_irqrestore', 52)
0xffffffc0376439b8:('htab_map_update_elem$cc60407cff2dc048b7fcd61e22c98b5a', 532)
0xffffffc0376439d8:('ktime_get_mono_fast_ns', 92)
0xffffffc0376439f8:('__htab_map_lookup_elem$cc60407cff2dc048b7fcd61e22c98b5a', 36)
0xffffffc037643a38:('lock_release', 92)
0xffffffc037643a48:('lock_release', 80)
0xffffffc037643a78:('rcu_lock_release', 0)
0xffffffc037643a88:('rcu_lock_release', 36)
0xffffffc037643ab8:('trace_call_bpf', 156)
0xffffffc037643ac8:('perf_trace_run_bpf_submit', 84)
0xffffffc037643ad0:('pick_next_task_fair$b601a1dbcc3b38bc5b22cc81fa26794b.cfi_jt', 0)
0xffffffc037643b28:('perf_trace_sched_switch$9f3f973902601718a9a7a341611142c3', 384)
0xffffffc037643b38:('trace_sched_switch', 360)
0xffffffc037643b88:('lock_release', 92)
0xffffffc037643b98:('lock_release', 80)
0xffffffc037643bb8:('__switch_to', 140)
0xffffffc037643bc8:('__switch_to', 348)

**Comment by lichm1007** [comment]
is a kernel bug? i used 5.4

**Comment by lichm1007** [comment]
when i hook sched switch and ipi interrupts ， during load testing, after running for about two days, the CPU core 0  became unresponsive

**Comment by lichm1007** [comment]
sched_switch, sched_wakeup, ipi_entry ipi_exit  when hook this points, the system is hang

**Comment by anakryiko** [comment]
see https://github.com/libbpf/libbpf?tab=readme-ov-file#libbpf-and-general-bpf-usage-questions, best asked elsewhere
