### ISSUE TITLE
libbpf build error,  fatal error: linux/bpf_perf_event.h: No such file or directory

### ISSUE THREAD

**Issue by bigdogs** [libbpf/libbpf#785]
hi, 
It seems that libpbf requires the header <linux/bpf_perf_event.h>, which is not present in the Linux kernel 4.4 (the default kernel version of Ubuntu 16.04). Does libbpf no longer support Ubuntu 16.04?

**Comment by anakryiko** [comment]
I think this header is used in libbpf.c, so it is needed only to *build* libbpf, not necessarily at runtime. I can't check libbpf on 4.4 kernel, but it should support BPF features that are available in 4.4 kernel. You just need to use more modern **build** environment.
