### ISSUE TITLE
I want to access the parameter values of kprobe or uprobe ，not have BTF，use vmlinux+offset

### ISSUE THREAD

**Issue by lichm1007** [libbpf/libbpf#787]
I want to access the parameter values of kprobe or uprobe, but the kernel does not have BTF enabled. I tried to access them using vmlinux+offset, but it resulted in an error indicating that BTF functionality is not enabled in the kernel. How can I access the parameter values in this case?

**Comment by anakryiko** [comment]
https://github.com/libbpf/libbpf?tab=readme-ov-file#libbpf-and-general-bpf-usage-questions
