### ISSUE TITLE
bpf cookie consult

### ISSUE THREAD

**Issue by chentao-kernel** [libbpf/libbpf#791]
Hi, anakryiko, i saw the bpf cookie can be added in libbpf and insert in into kernel, but  i was confused with how to use it, so what we can do with bpf cookie.

**Comment by anakryiko** [comment]
you can specify cookie value during attachment and then retrieve that value from BPF program. This value can be different for each attached hook (kernel function, user function, etc). See https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/prog_tests/bpf_cookie.c and https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/progs/test_bpf_cookie.c for a test/example.
