### ISSUE TITLE
libbpf keeps unsetting O_CLOEXEC on its own fds

### ISSUE THREAD

**Issue by poettering** [libbpf/libbpf#812]
Kernel bpf() syscall sets O_CLOEXEC on its fd, but libbpf userspace then unsets it, due to 4d68ea90c23e224e020434f1e42d41a05bae0029 which calls dup2(), i.e. duplicates the fd without O_CLOEXEC.

Please make sure to always keep the O_CLOEXEC in place, i.e. in this specific case please use dup3() with O_CLOEXEC flag.

This broke systemd upstream where we generally are very careful to never allow fds without O_CLOEXEC into PID1's fd table, but libbpf now breaks that. This matters for some processes we fork off which suddenly get a bpf map fd inherited they really shouldn't get inherited.

**Comment by anakryiko** [comment]
Fixed by https://github.com/libbpf/libbpf/commit/805b689cd23296da88a1282ae353851c57007f70
