### ISSUE TITLE
libbpf:xdp prog detach

### ISSUE THREAD

**Issue by chentao-kernel** [libbpf/libbpf#814]
hi anakryiko, i use the bpf_program__attach_xdp api to attach xdp prog on  kernel 6.5 on ubuntu, and use the api bpf_link__detach api to
detach it, but it seems that the xdp prog still exist, when i use `bpftool prog list` to query, so how can i delete the xdp prog?
![image](https://github.com/libbpf/libbpf/assets/86768822/d3e57da6-4e9a-4490-b765-9fe065c4f7a7)

**Comment by anakryiko** [comment]
yes, that's expected. BPF program first is verified/loaded. It's not yet active, not attached. bpf_program__attach_xdp() takes loaded program and attaches it to a device, creating a BPF link. That BPF link represents *attachment*. When you detach program, program itself doesn't go away, it is still loaded in kernel, just not being triggered.

**Comment by anakryiko** [comment]
Yes, that's how all BPF links behave. And attachments that don't use BPF link behave also the same, because lifetime of BPF program and BPF program's attachment are two separate things in kernel.

**Comment by chentao-kernel** [comment]
> Yes, that's how all BPF links behave. And attachments that don't use BPF link behave also the same, because lifetime of BPF program and BPF program's attachment are two separate things in kernel.

I read the source code again, what you said above is rellay for me, thanks a lot.
