### ISSUE TITLE
BPF_MAP_TYPE_ARRAY_OF_MAPS inner map inconsistencies

### ISSUE THREAD

**Issue by davidcoles** [libbpf/libbpf#816]
Hello. I seem to be coming across some inconsistencies with creating inner maps from userspace in an array of maps created in BPF.

If I use the struct name as the inner map template value definition, then on some kernels the map will be created, but cannot be associated with an outer map element (bpf_map_update_elem) at runtime: EINVAL (-22) is returned.

However, if I use an arrary of bytes declared with the sizeof the struct in question in the template map, then the code works on all the systems I have tested on.

I'm sure that this is my misunderstanding of how the map creation/association process works, so I would be most grateful if someone could clarify the process that I should be using.

I have created a Gist with the code I'm using, a Makefile which show the build process, and a README file with the results on various systems (with the userspace/BPF code attached below):

https://gist.github.com/davidcoles/ce5b4bda25f46cb11d6f54afbacd1bbb (edited to correct URL)

I also notice that the max entries value for the inner map created in userspace can be different from the template - it would seem logical that this would be safe (presumably the update helper function check the size on each invocation), but I would be most grateful if someone could confirm this for me.

Many thanks!

## kern.c:

```
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

struct foo {
    __u32 x;
    __u32 y;
    __u32 z;
} bar;

struct {
    __uint(type, BPF_MAP_TYPE_ARRAY_OF_MAPS);
    __type(key, __u32);
    __type(value, __u32);
    __uint(max_entries, 10);
    __array(
	    values,
	    struct {
		__uint(type, BPF_MAP_TYPE_LRU_HASH);
		__type(key, __u32);
		__type(value, struct foo); // this fails in some instances, but the following line always works
		//__type(value, __u8[sizeof(struct foo)]);
		__uint(max_entries, 10);
	    });
} array_of_maps SEC(".maps");

SEC("xdp")
int  xdp_pass_func(struct xdp_md *ctx)
{
    return XDP_PASS;
}

char _license[] SEC("license") = "GPL";
```

## user.c:

```
#include <bpf/bpf.h>
#include <bpf/libbpf.h>

#include <errno.h>
#include <stdlib.h>
#include <stdio.h>

void main() {

  char *filename = "kern.o";
  char *map_name = "array_of_maps";

  struct bpf_object *obj_prog = NULL;
  struct bpf_map *map;
  int ret, fd;

  obj_prog = bpf_object__open(filename);
  if (!obj_prog) {
    ret = -errno;
    fprintf(stderr, "Couldn't open file: %s\n", strerror(-ret));
    return;
  }

  ret = bpf_object__load(obj_prog);
  if (ret) {
    ret = -errno;
    fprintf(stderr, "Couldn't load object: %s\n", strerror(-ret));
    return;
  }

  map = bpf_object__find_map_by_name(obj_prog, map_name);
  if (!map) {
    ret = -errno;
    fprintf(stderr, "Couldn't find map: %s\n", strerror(-ret));
    return;
  }

  int outer = bpf_map__fd(map);

  fd = bpf_map_create(BPF_MAP_TYPE_LRU_HASH, NULL, 4, 12, 10, NULL);

  if (fd < 0) {
    ret = -errno;
    fprintf(stderr, "Couldn't create inner map: %s\n", strerror(-ret));
    return;
  }

  int index = 0;

  ret = bpf_map_update_elem(outer, &index, &fd, BPF_ANY);

  if (ret != 0) {
    fprintf(stderr, "Couldn't add inner map: %s\n", strerror(-ret));
    return;
  }

  printf("Hello, World! %d\n", fd);
}
```

**Comment by anakryiko** [comment]
It could be some Clang "optimization" stripping out type information, not sure. Can you try something like below

```
struct my_inner_map {
		__uint(type, BPF_MAP_TYPE_LRU_HASH);
		__type(key, __u32);
		__type(value, struct foo); // this fails in some instances, but the following line always works
		//__type(value, __u8[sizeof(struct foo)]);
		__uint(max_entries, 10);
	    };
```

and then use `struct my_inner_map` in `__array(values, struct my_inner_map);`?

As for 

> I also notice that the max entries value for the inner map created in userspace can be different from the template - it would seem logical that this would be safe (presumably the update helper function check the size on each invocation), but I would be most grateful if someone could confirm this for me.

I think you'll need to create inner ARRAY maps with BPF_F_INNER_MAP flag, which, starting at some kernel version, would allow to have ARRAY maps inside outer map with varying number of max_entries.

BTW, I can't access the gist you posted.

**Comment by davidcoles** [comment]
Just tried and that didn't work, sadly.

That format was how I had written the code initially - I should have posted that simpler example really, I guess.

Point taken about the clang optimisation; it kind of seems like some symbol is not visible to be able to calculate the required size, because the --u8[sizeof(...)] version does work fine. I shall investigate there.

Oops, looks like I managed to post the gist with /edit appended, it should have been https://gist.github.com/davidcoles/ce5b4bda25f46cb11d6f54afbacd1bbb 

Thanks for the tips about the BPF_F_INNER_MAP flag - I shall give that a go!

All good - I've got a workaround for the inner map size issue which works on all the systems I have tested on, so feel free to close.

Thank you ever so much for your help!

**Comment by davidcoles** [comment]
[kern.o.gz](https://github.com/user-attachments/files/15570141/kern.o.gz)

Here's a (gzipped) copy of the BPF from the gist/inline code above. It's using v1.3.0 of libbpf, same version across every system that I have tried (Makefile in the gist used to build).

I shall have a look at the retsnoop utility - thank very much for your assistance.

Seperately, I have also tried the 1.4.3 version of libbpf - still the same issue.

**Comment by davidcoles** [comment]
Worth noting that it will work on some systems (eg. Ubuntu 24.04) but not on others, eg. Debian Bookworm:

# cat /etc/debian_version
12.5
# uname -a
Linux test1 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
# ./user
Couldn't add inner map: Invalid argument

**Comment by anakryiko** [comment]
This looks to be kernel version dependent, but I'm not sure why this would happen. BTF data looks fine.

**Comment by davidcoles** [comment]
OK, I'll have a look at the retsnoop tool and see if I can find anything. Thanks again for your help :-)
