### ISSUE TITLE
geting rid of fmemopen

### ISSUE THREAD

**Issue by aminassadi** [libbpf/libbpf#817]
I use c++ for the user mode and my binary is dependent to fmemopen that used here:
`static int bpf_object__read_kconfig_mem(struct bpf_object *obj,
					const char *config, void *data)
{
	char buf[PATH_MAX];
	int err = 0;
	FILE *file;

	file = fmemopen((void *)config, strlen(config), "r");
	if (!file) {
		err = -errno;
		pr_warn("failed to open in-memory Kconfig: %d\n", err);
		return err;
	}

	while (fgets(buf, sizeof(buf), file)) {
		err = bpf_object__process_kconfig_line(obj, buf, data);
		if (err) {
			pr_warn("error parsing in-memory Kconfig line '%s': %d\n",
				buf, err);
			break;
		}
	}

	fclose(file);
	return err;
}`
is there any way to get rid of this. I want to not dependent to the newer version of GLIBC due to portabiliry.

**Comment by eddyz87** [comment]
Hello,

How old is your glibc? Quick look at the man page shows:

```
SYNOPSIS
       #include <stdio.h>

       FILE *fmemopen(void *buf, size_t size, const char *mode);

   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       fmemopen():
           Since glibc 2.10:
               _POSIX_C_SOURCE >= 200809L
           Before glibc 2.10:
               _GNU_SOURCE
```
It also lists a bunch of bugs for versions of glibc before 2.22, but non of these seem applicable for "r" mode.
