### ISSUE TITLE
Memory mapping a `BPF_MAP_TYPE_ARRAY` into userspace

### ISSUE THREAD

**Issue by blonded04** [libbpf/libbpf#822]
Is there a way to directly `mmap` into userspace a `BPF_MAP_TYPE_ARRAY` to freely read from it (or maybe even write to it) without invoking a syscall, because it's pretty costy?

I'm not well qualified in nor kernel programming and eBPF so all the answers I found online don't seem to answer my question :( Seen some answers related to `bpf_map__initial_value` but it doesn't seem to help much

**Comment by anakryiko** [comment]
Yes, see https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/progs/test_mmap.c and https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/prog_tests/mmap.c for an example.

The key is to define ARRAY map with BPF_F_MMAPABLE flag. Then you can just mmap() its contents into user space by BPF map FD.

**Comment by blonded04** [comment]
> Yes, see https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/progs/test_mmap.c and https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/prog_tests/mmap.c for an example.
> 
> The key is to define ARRAY map with BPF_F_MMAPABLE flag. Then you can just mmap() its contents into user space by BPF map FD.

thank you!
