### ISSUE TITLE
[question] Modifying a map of a tracepoint eBPF program after attaching it

### ISSUE THREAD

**Issue by blonded04** [libbpf/libbpf#830]
Is there a way to modify map (`BPF_MAP_TYPE_ARRAY` in my case) of a eBPF program before attaching it to a tracepoint? Simply doing `bpf_map_update_elem` results in an error and sets `errno` to `File exists` :( . 

If it's not achievable using a map -- are there any other ways to pass some data from userspace to eBPF program during its runtime? Or maybe I can simply write to `mmap`ed pointer of `BPF_MAP_TYPE_ARRAY` from userspace? Which options do I have?

**Comment by anakryiko** [comment]
This should work, please show a bit of code, not enough details provided.

**Comment by blonded04** [comment]
I'm sorry, but after trying to build minimal reproducible example it turned out that "File open" result is actually what happens when trying to access `BPF_MAP_TYPE_ARRAY` with flag `BPF_NOEXIST` doesn't make much sense (I thought of it as if there is an additional bit of memory per each cell of an array). 

Changing map to e. g. `BPF_MAP_TYPE_HASH` made it work. Thank you for your time
