### ISSUE TITLE
link update in tracing prog  consult

### ISSUE THREAD

**Issue by chentao-kernel** [libbpf/libbpf#833]
Hi, anakryiko
When i saw the bpf_link source code, i saw update_prog not realised in tracing prog, but xdp prog was realised, so is there
any difference between both.

![image](https://github.com/user-attachments/assets/bd3e61ab-ebb0-4c59-ace8-aba0e665b7d3)

![image](https://github.com/user-attachments/assets/264cc75d-bbac-4a64-bd84-8280022b9179)

**Comment by anakryiko** [comment]
yes, link update is not implemented for tracing program types

**Comment by chentao-kernel** [comment]
> yes, link update is not implemented for tracing program types

So, we also can realise it in tracing prog, right?

**Comment by anakryiko** [comment]
if someone implements in the kernel, sure. It's more important for XDP, though, because there you can only attach one BPF program, while with tracing programs it's easy to have multiple programs attached. So if you need to update program, you might as well just attach a new version and detach the old one.

**Comment by chentao-kernel** [comment]
Hi anakryiko, thank you for your patient reply，

> if someone implements in the kernel, sure. It's more important for XDP, though, because there you can only attach one BPF program, while with tracing programs it's easy to have multiple programs attached. So if you need to update program, you might as well just attach a new version and detach the old one.

Hi anakryiko, thank you for your patient reply，got it. I close this issue.
