### ISSUE TITLE
[Question] How to add new entries to an eBPF map of maps from userspace

### ISSUE THREAD

**Issue by pvvm** [libbpf/libbpf#834]
Hello, I want to create an eBPF hash of maps and add entries to this map gradually. Since BPF programs cannot add new entries to outer maps, my only option is to do that in the userspace program. And I found out a way to do that by defining a outer map and the expected inner map in the BPF program:
```
struct inner_array {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __type(key, __u32);
    __type(value, __u32);
    __uint(max_entries, 4);
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH_OF_MAPS);
    __uint(max_entries, 10);
    __type(key, __u32);
    __array(values, struct inner_array);
} outer_hash SEC(".maps");
```

While the userspace program uses **bpf_map_create** to create a new inner map and **bpf_map_update_elem** to include it in the outer map.

However, instead of the inner map being an array of integers, I'd like for it to be an array map containing structs. So, I first tried this version:
```
struct test {
    __u64 value;
    __u64 value2;
};

struct inner_array {
	__uint(type, BPF_MAP_TYPE_ARRAY);
	__type(key, __u32);
	__type(value, struct test);
	__uint(max_entries, 4);
};
```

But the following error was announced:
> libbpf: map 'outer_hash.inner': can't determine value size for type [37]: -22.

And then I tried this version:
```
struct inner_array {
	__uint(type, BPF_MAP_TYPE_ARRAY);
	__type(key, __u32);
	__type(value, sizeof(struct test));
	__uint(max_entries, 4);
};
```
But, in my userspace program, when I try to update the outer map with a new inner map, such as:
```
int inner_fd = bpf_map_create(BPF_MAP_TYPE_ARRAY, "test", sizeof(__u32), sizeof(struct test), 4, 0);
int err = bpf_map_update_elem(map_fd, &key, &inner_fd, BPF_ANY);
```

**bpf_map_update_elem** returns -22.

So, what should I do?
Thanks in advance

**Comment by anakryiko** [comment]
See https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/progs/timer_mim.c#L10-L33 for an example, it seems to work fine.
