### ISSUE TITLE
Dealing with renamed tracepoints

### ISSUE THREAD

**Issue by koonwen** [libbpf/libbpf#835]
Hi, I'm using libbpf to attach to io-uring tracepoints. However, it seems that linux 6.3 and more recent versions had a tracepoint named `io_uring_submit_sqe` renamed as `io_uring_submit_req`. I'm wondering if CO-RE is able to handle this case and if so, what is the correct way to do this. 

On my machine (linux 6.1), I did something like this
```c
/* Shim for newer kernels */
struct trace_event_raw_io_uring_submit_req {
  struct trace_entry ent;
  void *ctx;
  void *req;
  long long unsigned int user_data;
  u8 opcode;
  u32 flags;
  bool sq_thread;
  u32 __data_loc_op_str;
  char __data[0];
} __attribute__((preserve_access_index));

SEC("tp/io_uring/io_uring_submit_sqe")
int handle_submit_req(void *ctx) {

  if (bpf_core_type_exists(struct trace_even_raw_io_uring_req)) {
    struct trace_event_raw_io_uring_submit_req *args = ctx;
    ....
  } else {
    struct trace_event_raw_io_uring_submit_sqe *args = ctx;
    ....
  };
  return 0;
}
```
then porting it to run on a VM with (linux 6.7), I got
```
failed to resolve CO-RE relocation <byte_off> [49] struct trace_event_raw_io_uring_submit_sqe.req (0:2 @ offset 16)
```

What is the issue here? I'm also guessing that `SEC("tp/io_uring/io_uring_submit_sqe")` needs to be renamed to `SEC("tp/io_uring/io_uring_submit_req")`?

**Comment by anakryiko** [comment]
You can detect if trace_event_raw_xxx type exists in kernel with bpf_core_type_exists(), but you'll need to manually attach tracepoint through bpf_program__attach_tracepoint() and provide the right name of the tracepoint. Libbpf can't handle stuff like this automagically, but it provides building blocks to work with this.

**Comment by koonwen** [comment]
Gotcha, I'll give that a shot thanks!
