### ISSUE TITLE
[question] Is there a way to read a map from an unprivileged process?

### ISSUE THREAD

**Issue by blonded04** [libbpf/libbpf#838]
Hello, can you please tell me whether it's possible to do what I'm desiring to do.

I'd like to read from an eBPF map (of a tracepoint bpf program) from a process that didn't create this map and has no root rights. Therefore, this process needs to obtain this map's file-descriptor, which looks impossible with no pinning: AFAIK libbpf supports pinning only in bpf filesystem, which is inaccessible without root rights :(, therefore -- it's impossible, with libbpf means, to read an eBPF map from an unprivileged userspace process. Am I right?

**Comment by anakryiko** [comment]
BPF file system does support normal file permissions, so one process can ping BPF map there, change file permissions to allow other processes access to that file, and then other processes won't need any special capabilities to create FD for that map. This should work.

**Comment by blonded04** [comment]
Sorry for coming back after a month. 

Hovewer I can't make my example work, as I set `/sys/fs/bpf/my_map` to `-rw-r--r--`, and still get error in my user space program:

```
#include "libbpf.h"

int main(void)
{
    int fd;

    fd = bpf_obj_get("/sys/fs/bpf/per_process_counts");
    if (fd < 0) {
        fprintf(stderr, "No way to open map file: %d %s!\n", fd, strerror(errno));
        return 1;
    }
    
    return 0;
}
```

It keeps returning `-1` as long as I don't run it with `sudo` :( 
Can you please help?
