### ISSUE TITLE
[question] I guess up to the size limit of eBPF Maps.

### ISSUE THREAD

**Issue by Bobcat-yang** [libbpf/libbpf#840]
Hello,
I would like to know what is the size limit of eBPF Maps in Linux? How much data can I store when using it?
I did not find the answer in the documentation, so I asked this question here. Hope to get your reply.

Thank you.

**Comment by anakryiko** [comment]
This is not a libbpf question, please see https://github.com/libbpf/libbpf?tab=readme-ov-file#libbpf-and-general-bpf-usage-questions
