### ISSUE TITLE
Sync: bpf_perf_event.h

### ISSUE THREAD

**Issue by nkapron** [libbpf/libbpf#841]
Following up to https://github.com/libbpf/libbpf/issues/785, is there a reason we are not syncing `include/uapi/linux/bpf_perf_event.h` to the libbpf local includes, or was it an oversight?

I have a change [1] which add this and enables x86 builds, but ultimately, would introduce a fair amount of arch-specifc headers.

Should I proceed in adding the directory structure and includes to satisfy the `"../../arch/xyz/include/uapi/asm/bpf_perf_event.h"` includes (and their included `ptrace.h` headers)?

[1] https://github.com/libbpf/libbpf/compare/master...nkapron:libbpf:sync

**Comment by anakryiko** [comment]
That header hasn't changed in a long while and unlikely to be changing (given those types are effectively set in stone). What sort of problem are you trying to solve? Why can't you rely on system-provided UAPI header for this?

**Comment by nkapron** [comment]
Unfortunately, Android's sandboxed build environment for host tools is using a very old version of glibc (2.17-4.8), which does not have this header. There is work to change, but that is unlikely to land any time soon. 

Your point that the header hasn't changed and shouldn't change makes sense though, so don't think it is necessary for upstream to carry this- I'll work around it downstream. 

Thanks for the insight!

**Comment by anakryiko** [comment]
Sounds good. I'd prefer to not get into arch-specific includes, if at all possible.
