### ISSUE TITLE
Is `name_len` fields in `bpf_link_info.perf_event` intended to be zero?

### ISSUE THREAD

**Issue by tyrone-wu** [libbpf/libbpf#850]
Hi 👋,

When retrieving `bpf_link_info.perf_event` data, I'm observing that the `name_len` fields for `uprobe`, `kprobe`, and `tracepoint` are zero on the first `bpf_link_get_info_by_fd()` call. I expected it to behave similar to `bpf_link_info.raw_tracepoint`, where `tp_name_len` had a non-zero value.

Is this the expected behavior for `bpf_link_info.perf_event`?

I also noticed that `bpftool` uses a static `4096` sized array to handle `bpf_link_info` names, however, I ideally don't want to rely on this method if possible.

Thank you in advance! 😄

**Comment by anakryiko** [comment]
Please report this issue to bpf@vger.kernel.org, this is kernel-side issue, not libbpf one.
