### ISSUE TITLE
[question] Reading eBPF map from unpreviliged process (again)

### ISSUE THREAD

**Issue by blonded04** [libbpf/libbpf#851]
Hello, I've already asked it, but answer didn't seem to work :(

I have a priveleged process that loads and attaches BPF program of type tracepoint, it pins the `BPF_MAP_TYPE_ARRAY`, and I `chmod` map-file `/sys/fs/bpf/map` and its directory `/sys/fs/bpf` to be readable and executable.

However, my goal is to `mmap` that map from an unpreviliged process and read data from that chunk of bytes. When I call `bpf_obj_get` (even using raw syscall, not libbpf wrapper) on that `/sys/fs/bpf/map` file I keep getting `Permission denied` (and it fixes immediately when I run my reader process as sudo)

What am I doing wrong?

**Comment by anakryiko** [comment]
See `file_flags` in `union bpf_attr`. In libbpf API that's `file_flags` in `bpf_obj_get_opts`. Pass `BPF_F_RDONLY` as file flag to open map FD only for reads. By default it will open FD that can be used for read and write, which is why it's failing for you.

**Comment by blonded04** [comment]
> See `file_flags` in `union bpf_attr`. In libbpf API that's `file_flags` in `bpf_obj_get_opts`. Pass `BPF_F_RDONLY` as file flag to open map FD only for reads. By default it will open FD that can be used for read and write, which is why it's failing for you.

At this point to achieve `bpf_obj_get` I'm doing raw syscall to avoid the following problem in libbpf, however I still fail miserably, getting `Permission denied`

**Comment by blonded04** [comment]
> @blonded04 do you pass BPF_F_RDONLY to BPF_OBJ_GET?

Yes :( The following fails for me

```c
#include "libbpf.h"
#include <linux/bpf.h>
#include <unistd.h>
#include <stdio.h>
#include <errno.h>

const char *map_path = "/sys/fs/bpf/my_map";

#ifndef __NR_bpf
# if defined(__i386__)
#  define __NR_bpf 357
# elif defined(__x86_64__)
#  define __NR_bpf 321
# elif defined(__aarch64__)
#  define __NR_bpf 280
# elif defined(__sparc__)
#  define __NR_bpf 349
# elif defined(__s390__)
#  define __NR_bpf 351
# elif defined(__arc__)
#  define __NR_bpf 280
# elif defined(__mips__) && defined(_ABIO32)
#  define __NR_bpf 4355
# elif defined(__mips__) && defined(_ABIN32)
#  define __NR_bpf 6319
# elif defined(__mips__) && defined(_ABI64)
#  define __NR_bpf 5315
# else
#  error __NR_bpf not defined. libbpf does not support your arch.
# endif
#endif

int main(void)
{
    int fd;
    union bpf_attr attr;

    attr = (union bpf_attr) {};
    attr.pathname = (uintptr_t) map_path;
    attr.file_flags = BPF_F_RDONLY;

    fd = syscall(__NR_bpf, BPF_OBJ_GET, &attr, sizeof(attr));
    if (fd < 0) {
        fprintf(stderr, "Unable to get BPF object: %d %s!\n", fd, strerror(errno));
        return 1;
    }

    // .-----------------------------------------------------------
    // ^ Program doesn't get here if not run with `sudo`

    printf("Ok\n");
    
    return 0;
}
```

**Comment by anakryiko** [comment]
Should have asked from the very beginning. What kernel version are you on? See https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=c8644cd0efe71 which went into 5.19 kernel. You need that for this to work without privileges.

**Comment by blonded04** [comment]
> Should have asked from the very beginning. What kernel version are you on? See https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=c8644cd0efe71 which went into 5.19 kernel. You need that for this to work without privileges.

😱😱😱😱

Thank you, it now makes sense... I've only read that 5.5 is needed for something-something I'm using while I use 5.13 and 5.15.

Also, sorry for asking unrelated questions here, hard to dig something about eBPF when there is near zero info online and community is very small
